from enum import StrEnum

__all__ = ["KnownMap"]


class KnownMap(StrEnum):
    ARENA = "arena"
    BATTLEBOT = "battlebot"
    CHEMISTRY_CLASS = "chemistry_class"
    CINNAMON_ROLL = "cinnamon_roll"
    CORRIDORS = "corridors"
    DEFAULT_LARGE1 = "default_large1"
    DEFAULT_LARGE2 = "default_large2"
    DEFAULT_MEDIUM1 = "default_medium1"
    DEFAULT_MEDIUM2 = "default_medium2"
    DEFAULT_SMALL1 = "default_small1"
    DEFAULT_SMALL2 = "default_small2"
    DNA = "dna"
    FACE = "face"
    GALAXY = "galaxy"
    HOOKS = "hooks"
    HOURGLASS = "hourglass"
    LANDSCAPE = "landscape"
    MINIMAZE = "minimaze"
    PLS_BUY_CUCATS_MERCH = "pls_buy_cucats_merch"
    SHISH_KEBAB = "shish_kebab"
    THREAD_OF_CONNECTION = "thread_of_connection"
    TREE_OF_LIFE = "tree_of_life"
    WASTELAND = "wasteland"
    BAR_CHART = "bar_chart"
    BINARY_TREE = "binary_tree"
    BUTTERFLY = "butterfly"
    COLD = "cold"
    CUBES = "cubes"
    GAUSSIAN = "gaussian"
    GIT_BRANCHES = "git_branches"
    MANDELBROT = "mandelbrot"
    PIXEL_FOREST = "pixel_forest"
    SETTLEMENT = "settlement"
    SIERPINSKI_EVIL = "sierpinski_evil"
    SOCKET = "socket"
    STARRY_NIGHT = "starry_night"
    TILES = "tiles"
    WASTELAND_OASIS = "wasteland_oasis"
