"""Hardcoded map data for known official maps.

Key: (w, h, core_a_x, core_a_y)
Value: (encoded_tiles_b64, core_b)
Tiles: 4 tiles packed per byte (2 bits each), base64 encoded.
Tile values: 0=empty, 1=wall, 2=ore_ti, 3=ore_ax
"""

import base64

from cambc import Environment, Position

from .known import KnownMap, MapKey

__all__ = ["MAPS", "KnownMap", "MapKey", "decode"]


_TILE_TO_ENV: dict[int, Environment] = {
    0: Environment.EMPTY,
    1: Environment.WALL,
    2: Environment.ORE_TITANIUM,
    3: Environment.ORE_AXIONITE,
}


def _encode(tiles: list[int]) -> str:
    packed = bytearray()
    for i in range(0, len(tiles), 4):
        b = 0
        for j in range(4):
            if i + j < len(tiles):
                b |= (tiles[i + j] & 3) << (j * 2)
        packed.append(b)
    return base64.b64encode(bytes(packed)).decode("ascii")


def decode(data: str, n: int) -> list[Environment]:
    packed = base64.b64decode(data)
    tiles: list[Environment] = []
    for b in packed:
        for j in range(4):
            if len(tiles) >= n:
                break
            tiles.append(_TILE_TO_ENV[(b >> (j * 2)) & 3])
    return tiles


MAPS: dict[MapKey, tuple[str, Position]] = {
    # arena
    KnownMap.ARENA: (
        "AAAAAAAAAAAAAAAAAAAAVFUAAAAAgAAUAACAAAAAAQAAAAAgBAAAAAAAQAAAAMAAAAEAAgAAAAQAAABABRIAAAAAAEAAAABAwAAAAAAAAQAAAAAMBAAAAAQAAAAAABBCBQAAAEAAAAAAAgABAAwAAAAEAAAAAABAIAAAAAAAAQAACAAAUAAIAAAAAFRVAAAAAAAAAAAAAAAAAAAAAA==",
        Position(16, 14),
    ),
    # battlebot
    KnownMap.BATTLEBOT: (
        "AAAAAABQVVVVVUEAAAAABAEAAAAQBAAgAEAQAAAAAEFAAAIEBAEBABAQBBAgEEAQQABAAEEABEEABAFAUQAQBEAABEAQQgBAIEFAAAAEBAFBURAQBMRFTUAQECgKAUFAoCgEBAEEAAQQhEAABEgQCBQFCEEBAAEABRQAAAAFQAHMAAUAFDADBQAAAQABAABQUQEAAAAQAAAA",
        Position(16, 4),
    ),
    # chemistry_class
    KnownMap.CHEMISTRY_CLASS: (
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAwAAAAAzAAAAAAzAAAAADAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAIAACACAAAAAIAIAACAAAAQBAAAAgAAAAAAEAQAAAAAAAAAABAEAAAAAAAAIAAQBAAIAAAAAIgAEAQAIgAAAAAgABAEAAgAAAAAAAAQBAAAAAAAAAAAEAQAAAAAAFBQABAEAAUFAABAEAAQBAAEAQAAQBAAEAQABAEAAEAQABAEAAQBAAAQQAAQBAABBAAAEEAAEAQAAQQAAAQAARAEQAAQAAAEAAEQBEAAEAAAAQAEEAQQAEAAAAEABNAHEABAAEAIghBAAQSCIAFAIAAQAAAEAAgBkAAgYAAACQgABhCAAEgAACEAAgRAVVUVAABUVVUBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        Position(25, 23),
    ),
    # cinnamon_roll
    KnownMap.CINNAMON_ROLL: (
        "AAAAAAAAAAAAAAAAAAAAAABQVRUAAAAAUAAAFAAAAEAAgAAUAAAAAQAAAAQAAARAVQUAAQAQQAEABRAAAAEBIAABBAAEBAAAEEAAQBBAVSAEBAAkAcEQQEAAQAQEVAQEBABEQFB0QBABQAQhXQQkEQBEGBB1SBABQAQBHQUBEQAQEBAVEBABAAEBBENAGAAQEAhVAQQBAAEEAAAQEAAQQAAIQEAAAARQAEABBABAAFBVARAAABAAAABAAAAAFAACAAEAAAAUAAAFAAAAAFRVBQAAAAAAAAAAAAAAAAAAAAAA",
        Position(27, 2),
    ),
    # corridors
    KnownMap.CORRIDORS: (
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAUBAQEBAQEAAEBAQEBAQEAAEBAQEBAQEICEhISEhISFAQEBAQEBAABAQEBAQEBAABAQEBAQEBCAhITExISEhQEBAQEBAQAAQEBAQEBAQAAQEBAQEBAQgASExMSEBIUBAQEBAQEAAEBAQEBAQEAAEBAQEBAQEICEhMTEhISFAQEBAQEBAABAQEBAQEBAABAQEBAQEBCAhISEhISEhQEBAQEBAQAAQEBAQEBAQAAQEBAQEBAQAAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        Position(25, 15),
    ),
    # default_large1
    KnownMap.DEFAULT_LARGE1: (
        "AAAAAAAAAgAAAAAgAAAAAAAAAAAAAAIAVVVVBQACMAAAUAAAAFQAAAAAABUAAAAABQAAAEABAAAAABQAACBQAAAAAABQAAAAFAAAAAAAQAAAAAUAAAAAMAAAAAwBAAAAA6gAAABAAAAAAQAAAAAAQAAAAAEAAAAAAFAACAAFAAAAAAAQAAAABAAAACAAAAAAAAQAAAAAAAAAAAAQAAAAAAAAAAAAUAAAAAAAAAAAAEABQAEAAAAAAAAAVFUAAAAAAAAADAAAAAAAAAAAMAAAAAAAAABVFQAAAAAAAABAAUABAAAAAAAAAAAABQAAAAAAAAAAAAQAAAAAAAAAAAAQAAAAAAAIAAAAEAAAAAQAAAAAAFAAIAAFAAAAAABAAAAAAQAAAAAAQAAAAAEAAAAqwAAAAEAwAAAADAAAAABQAAAAAQAAAAAAFAAAAAUAAAAAAAUIAAAUAAAAAEABAAAAUAAAAABUAAAAAAAVAAAABQAADIAAUFVVVQCAAAAAAAAAAAAAAAgAAAAAgAAAAAAAAA==",
        Position(28, 14),
    ),
    # default_large2
    KnownMap.DEFAULT_LARGE2: (
        "AAAAAAAAAAAAAAAAAAAAAAAgDIMAAAAAAAAAAAAIAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAUIAAAAAAACBQAAAFABAAAAAAAAVAAAAAAUAFBVVVUAQAEAAABABVBVVVVVABUAAAAAWEAFAAAAFVACAAAAAAUFAAAAAAUFAAAAAFAAAAAAAABQAAAAAAAFAAAAAAAABQAAACBQACAAAIAAUIAAAAAABQAAAAAAAAUAAAAAVAAAAAAAAFABAAAAQAEAQgEUCAAUAAAAABUAABRAAQBABQAAAFAAAEABFAAAUAAAAAAAAAIUQAEIAAAAAAAAAABAARQAAAAAAAAAACAAFEABgAAAAAAAACAAUAFUAIAAAAAAACAAABVABQCAAAAAACAAAFTwUAEAgAAACAgAAEABABQAAAACAgAAAAAVAEAFAAAAAAAAAEBVwDBQFQAAAAAAAFVVAAAAUFUFAAAAAFBVAQwAA1RVAAAAAAAAAAAAAAAAAAAA",
        Position(46, 16),
    ),
    # default_medium1
    KnownMap.DEFAULT_MEDIUM1: (
        "AAAAAAAAAAAAAAAAAAAAMAAAgAIAgAAAAAAIAAAAQFUAAAAEAAAABAAAQAEAAEAAAABQCAAoBAAAAAQAAEIAAABAVQAAAAAEAAAAAAAAQAAAAAAAAAAEAAAACAAAQAAAAAAAAMAAAAAAAAAA4FUBAAAAQFULAAAAAAAAAAMAAAAAAAABAAAgAAAAEAAAAAAAAAABAAAAAAAAEAAAAABVAQAAAIEAABAAAAAQKAAgBQAAAAEAAEABAAAQAAAAEAAAAFUBAAAAIAAAAAACAIACAAAMAAAAAAAAAAAAAAAAAAAA",
        Position(19, 10),
    ),
    # default_medium2
    KnownMap.DEFAULT_MEDIUM2: (
        "AAAAAAAAAAAAAAQAAQAAAABAABAAAAAAADTAAQAAAABAABAAAAAAAAQAAQAAAABAABAAAAAACAAAAAIAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAQBAAAIACBAAAAQAAAAAAQBAAFRVARAAAAQAAAAAAQBAAAAAABAAAAQAAAAAAQAAAIAgAAAAAAAACAIAAAACAMAwAAAIIABAABAAgAAAAAQAAQAAAABAABAAAABUBQQAAVUBAABAABAAAACAAgQAASgAIAhAABAAggAAAwAAAAwAAAAACAIAAAAAAAAAAAAA",
        Position(26, 3),
    ),
    # default_small1
    KnownMap.DEFAULT_SMALL1: (
        "AAAAAAAAIAAAAAAAAAAAAAFVAQJAAQAAAAAAAAQAgCAIFAAAAAAAAADAAAAEAAAMAAQQADAAABAAAAMAAAAAAAAAFCAIAgAQAAAAAAAAQAGAQFVAAAAAAAAAAAAACAAAAAAAAA==",
        Position(18, 18),
    ),
    # default_small2
    KnownMap.DEFAULT_SMALL2: (
        "AAAAAAAgAAAAAAIAAAAAAAABABAAABQgUAAAQAFQAAACVFUAAkAAAEAAUIEACBUAADADAAAAAAAAAAAAMwAAUIEACBUABAAABAACVFUAAgAUAAUAABQgUAAAEAAAAQAAAAAAAAIAAAAgAAAAAAAA",
        Position(10, 19),
    ),
    # dna
    KnownMap.DNA: (
        "AAAAAAAAAAAAAAAAAAAAAIAAAMAAAFpV1QMAIAAAAwCAAgAPAABoVQ8AAIDKDwAAAKADAAAAwAoAAADwowIAAPBVKQAA8ACAAgDAAAAIAMBXVaUAAAMAAAIADAAACABwVVUlAMADAKAAAAwAgAAA8FWVAgAAD4ACAADwowIAAAC8AAAAAOADAAAAqPwAAAAoAA8AAGhV9QAAIAAAAwCgAAA8AIBVVdUAAAIAAAMACAAADACgVVU9AAACADAAACgA8AAAgFb1AAAAqPwAAAAAOgAAAACsAAAAAD8qAAAAX5UCAAAPACgAAAwAgAAAfFVVCgAwAAAgAAAAAAAAAAAAAAAAAAAAAAA=",
        Position(10, 1),
    ),
    # face
    KnownMap.FACE: (
        "AIAAAgAMAAAAMEBVAFUBEABBAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAgAFAAgAAAUAAAAABQAAAAAVQAAAAAAAAAAgQBCAAABAEAAABQAFAAIQFUBIAAAAAAAAAwAMAAAAAAAAA==",
        Position(14, 7),
    ),
    # galaxy
    KnownMap.GALAXY: (
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAACAAACAAAAAFQAAAAAAAAAAUAEAAAAAAAAAABQACAAAAAAAAAAFAAADAAAAAAAAAQAAAAAAAACAQAAAAAAACAAAAFAAQFUFAAAAAAAQMBQAUAEAAAAAEAAFAAAUAAAAABQAAQKAQAEAAAAEQAAAAAAFAAAABEIAVAEABAAAAARAAAAUABAAQAAQQAAAQABAAEAAUAABDEABAwFAwEABMEAABQABAAEAAQAAAQQAAQAEABQAAAEQAAAAEABAFQCBEAAAAFAAAAAAARAAAABAAQKAQAAUAAAAABQAAFAABAAAAABABQAUDAQAAAAAAFBVAQAFAAAAIAAAAAAAAQIAAAAAAAAAQAAAAAAAAMAAAFAAAAAAAAAAIAAUAAAAAAAAAABABQAAAAAAAAAAVAAAAAIAAAIAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        Position(35, 4),
    ),
    # hooks
    KnownMap.HOOKS: (
        "AAAAAAAAAAAAABAAAAAAgAoABCoAAAAAAgCBAEBVAQAAQAAAEAAAAFQVVAEEAAAAAAABAAEAAAAAQABAAAAAAIASGhAAAEBVgAQGAAAAEAAAAQEAAAAEAEBAAAAAAAAAABBQVQEACgA8BABAAIBQFQMBABBAAADETAAABBAAAAFTFQgABABA8ACAAgBVFRAAAAAAAAAABAQAQAAAAAABAQAQAAAAQEIIVAUAABCQEgoAAAAABAAEAAAAAAABAAEAAAAAQABVUFUAAAAQAAAEAAAAVQUACAEAAgAAAKBCAIAKAAAAABAAAAAAAAAAAAAAAA==",
        Position(27, 8),
    ),
    # hourglass
    KnownMap.HOURGLASS: (
        "BAEAAAAQBAEBAAAAAUEAAQAAEEAQAAEAAAEQFAABABAABQQABUABQAABAKgKABBAAAAAAAAEUACAAABAARAAACAAEAAEACAAAAQABQCAAEABAAEAAAAQAEAAACIABABQAAgAQAEAEACAABAAABQAAAAFAAAUgABQAAAAFAACBQAAABQAUAAAAACUqgUAAAAA1F8AAAAAAAQEAAAAAED9BQAAAACUqgUAAABAAQAFAAAAFAACBQAAQAEIAAUAABQAAAAFAAABAAgAAQBQAAgAQAEABAAgAkAAAAEAAAAQAFAAAAgAFAAEACAAAAQAAQAAAgABUACAAABAAQQAAAAAQAABAKgKABBAAFAAFAAEFAABABAABQEQAAAQAEEAAQAAEEAQEAAAABAQBAEAAAAQBA==",
        Position(13, 1),
    ),
    # landscape
    KnownMap.LANDSCAPE: (
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAACoAAAAAFRVAQMAAAAVAEAxAIAABAAAQAUAKhAAAAAABcBQAAAAAABVVQAAAAAAAAAAIAACAAIACKCoiqqKqiqqAAAAAAAAAAAAAAAAAAAAiqqoqqiqogoCIAAgAIAAAAAAAAAAAAAAAAAAUFUFAQAAAFAADEUAAABUAKACUAEAFAMACABAVRUwAAAAAAAAgAoAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        Position(3, 27),
    ),
    # minimaze
    KnownMap.MINIMAZE: (
        "KAMAAQCjIAAABAAAUlUIEIBUFQBBQEAQAAAEoSlBAEAQhIAEQQBBEAAQBAEkQVVVEAaQBMANQBhAFQAEAFUAABACEgAAAEAwQwAAFVBVVRVQQUAAAEBAAAEAAgIAAQQAQAAABABUBUFVAAAQEAQBAQBVQBAEVAEAIEEQAgAAAARBAAAAVBUEVQUAAACYAAAAAABgAgAAAAAAAQAAAA==",
        Position(23, 23),
    ),
    # pls_buy_cucats_merch
    KnownMap.PLS_BUY_CUCATS_MERCH: (
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAEEAAMwgAAAAAAAAAEEEEMIgAAAAAAAAAQERAAAgIAAAAAAAAAAEAAYAIAAAAAAAAAAQABAAIAAAAAAAAABAAEAAAAAAAAAAAABAAAAEAgAAAAAAAAAARBAEFAAAAAAAAAABBEBBBgIgAAAAAAAAQABAEBAAAAAAAAAAAFRAQEIAAAABVVRUAEAABQQAAAAoEAEAAQAAEBAEAAIIQAAABAAFAEAQAAwgCAQAQAAQARAQAP4ACBABAABAAQBAAMAAAEAAAAUAAAEEAAAAAAgEAEAARAUQAAAAAAAQAQABEBFAAIAAAIlJVVVVBVRUAIAIAAAAAAAAAAAAAAAIAAAIAAAAAAAAADAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAACAAACAAAAAAAAAAAAAAAiAFBVBVVVVRUiAgAgABRARAAEAEAAAAAAAEQAEQEQAAABAgAAAAQBAAQAAQAQAAAwABAEABAABABAAArwA0BEAEAAEAAAAYIAA0AQBAABAAEAEAgCAABBQAAEAAQAQIACAAAEAQEQAFBVVQEAAAgQEBBQAQAAAAAAAABAQBAAEAAAAAAAAIgIBBEQBAEAAAAAAAAAQAFBEAEAAAAAAAAIAAABABAAAAAAAAAAAAAQABAAAAAAAAAAgABAAEAAAAAAAAAAgAgAAQABAAAAAAAAgIAABEQEAAAAAAAAAIgwQAQRAAAAAAAAAIAwAwQQAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        Position(35, 31),
    ),
    # shish_kebab
    KnownMap.SHISH_KEBAB: (
        "AAAAAAAAACAABQAAAEABAAAAVQAAAEBgIAAAQEMAAABQFQAACAQHAAAAJAQAAABUAQAAQBUAAAAQGAAAANAQIAAAVAUAAADBAQAACAkBAAAAVQAAAEABAAAAUAAIAAAAAAAAAA==",
        Position(17, 17),
    ),
    # thread_of_connection
    KnownMap.THREAD_OF_CONNECTION: (
        "AAAAAQAAAEABAAAAQAAAgApQAAAgIBAIAAiAEAIACAUTQgEIFFMIVSAQTCAAgFBMgQAAQjEFAgAIMQQIVSDFFCBAgcRQIACABAIgACAECAgAAAWgAgAAAQAAAEABAAAAQAAAAA==",
        Position(16, 3),
    ),
    # tree_of_life
    KnownMap.TREE_OF_LIFE: (
        "AAAIAAIgAAgAACAAgAAAAAgAIAAAAwAAMwAAMAAAAAAAAQABAAAAAAIIcABAAwggAABUBUAABEBVAAAAABRAQAAFAAAAACBQAAAUIAAAAAAAQABAAAAAAAAAAEIABAIAAAAAAABAQAAAAAAAAAAAEBAAAAAAAAAAAAQEAAAAAAAAAAABAQAAAAAAAABAQAAAAAAAAAAAEBAAAAAAAAAAAAQEAAAAAAAAAAABAQAAAAAAAAAQAAEAAAAAAAAABEAAAAAAAAAAAAEQAAAAAAAAAFAAFAAAAAAAAAABABAAAAAAAEBVVVVVBQAAQFUFAAAAAFRVQAWAAAgAgAAIQAUAAAAAAAAAAAAAAIAAAAAACAAAIAAAAAgIAAAAAgAAAAAAAAAAAAA=",
        Position(34, 22),
    ),
    # wasteland
    KnownMap.WASTELAND: (
        "AARAAIEAREAAAAABAgAEAFAEAAABAAAlAFAAEAEAAFIVAAEgYQQAAAEQBAREAAFQAAAAgABQAUAEBAAAMAEgBMAFEBQBAAAAAREEBUEQEQRAUREEBRAEBARBBEBENIREQAAABRQQgABBQABRFBEQAAAQABFVABAABFQQFUEFYBRAFQQBEQRQAAEBQVCARAAFAQBBQGAEAAQQAAABAAAUFAARAIQEAxQEASFABEgBEBQEQVUAQAABAAEQBQwBBRBAABFACAFAAEFBAAFAIAFEAAEEUEAwUARAAEAAAQBVQRAUBEAhEAFIQBAUwBASAEQAFBQAAEAAAAQQABAJAUEAQFAAEQIFQUBAAAUQREAQVAEUCVBBVAQVEAAEAFVEAAQAAAREFEUAAUEAAgQUUAAAARESHBEBEEEQEBAEUBBERQEQRARBUBBEQAAAAEAUBFADEAhADAAAEBABQAUAAgAAAAVAABEQEARAAAAQSQhAAFSFAABABAAFAFgAAEAAABAFABAAgEAAAAABEQBCAAEQAA==",
        Position(36, 3),
    ),
}
