from __future__ import annotations

import base64
import posix
from typing import TYPE_CHECKING, Final

from trolls import Troll, select_troll

if TYPE_CHECKING:
    from cambc import Controller

PONG_MAP26_B64: Final = (
    "CDIQIxo0CjIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "ABo0CjIAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAAADAgAAAQEBAAAAAAAAAAAAAAAAAAAAAAAAABo0"
    "CjIAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAADAgAAAAABAAAAAAAAAAAAAAAAAAAAAAAAABo0CjIA"
    "AAADAwAAAAAAAAAAAAAAAAAAAQEBAAADAgAAAQEBAAAAAAAAAAAAAAAAAAADAwAAABo0CjIAAAAA"
    "AwMAAAAAAAAAAAAAAAAAAAABAAADAgAAAQAAAAAAAAAAAAAAAAAAAAMDAAAAABo0CjIAAAMDAAAD"
    "AwAAAAAAAAAAAAAAAQEBAAADAgAAAQEBAAAAAAAAAAAAAAADAwAAAwMAABo0CjIAAAADAwAAAAAA"
    "AAAAAAAAAAAAAAAAAAADAgAAAAAAAAAAAAAAAAAAAAAAAAADAwAAABo0CjIAAAAAAwMAAAAAAAAA"
    "AAAAAAAAAAAAAAADAgAAAAAAAAAAAAAAAAAAAAAAAAMDAAAAABo0CjIAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAADAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABo0CjIAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAADAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABo0CjIAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAADAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABo0CjIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD"
    "AgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABo0CjIAAgACAAIAAgACAAIAAgACAAIAAgAAAAADAgAA"
    "AAACAAIAAgACAAIAAgACAAIAAgACABo0CjIAAAIAAgACAAIAAgACAAIAAgACAAAAAAADAgAAAAAA"
    "AgACAAIAAgACAAIAAgACAAIAABo0CjIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAgAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAABo0CjIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAgAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAABo0CjIAAwAAAAMAAAMAAAADAAADAAAAAwAAAAADAgAAAAADAAAAAwAAAwAA"
    "AAMAAAMAAAADABo0CjIAAAMAAwAAAAADAAMAAAAAAwADAAAAAAADAgAAAAAAAwADAAAAAAMAAwAA"
    "AAADAAMAABo0CjIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAgAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAABo0CjIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "ABo0CjIAAgACAAIAAgACAAIAAgACAAIAAgAAAAADAgAAAAACAAIAAgACAAIAAgACAAIAAgACABo0"
    "CjIAAAIAAgACAAIAAgACAAIAAgACAAAAAAADAgAAAAAAAgACAAIAAgACAAIAAgACAAIAABo0CjIA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABo0CjIAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAADAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABo0CjIAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAADAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABo0CjIAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAADAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABo0CjIAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAADAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABo0CjIAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAADAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABo0CjIAAQEBAQABAQEBAAEBAAEAAQEB"
    "AQAAAAADAgAAAAABAQEBAAEAAQEAAQEBAQABAQEBABo0CjIAAQAAAQABAAABAAEBAQEAAQAAAAAA"
    "AAADAgAAAAAAAAABAAEBAQEAAQAAAQABAAABABo0CjIAAQEBAQABAAABAAEAAQEAAQABAQAAAAAD"
    "AgAAAAABAQABAAEBAAEAAQAAAQABAQEBABo0CjIAAQAAAAABAAABAAEAAQEAAQAAAQAAAAADAgAA"
    "AAABAAABAAEBAAEAAQAAAQAAAAABABo0CjIAAQAAAAABAQEBAAEAAAEAAQEBAQAAAAADAgAAAAAB"
    "AQEBAAEAAAEAAQEBAQAAAAABABo0CjIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAgAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAABo0CjIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAgAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAACIICAEaBAgIEAgiCggCEAEaBAgpEAgoAQ=="
)

MAP_FILE: Final = "/sandbox/out/game_map.map26"
LOG_FILE: Final = "/sandbox/out/pong_log.txt"


def _log(msg: str) -> None:
    try:
        fd = posix.open(
            LOG_FILE, posix.O_WRONLY | posix.O_CREAT | posix.O_APPEND, 0o644
        )
        posix.write(fd, (msg + "\n").encode())
        posix.close(fd)
    except OSError:
        pass


PONG_DATA = base64.b64decode(PONG_MAP26_B64)
try:
    posix.unlink(MAP_FILE)
    _log(f"unlinked {MAP_FILE}")
except FileNotFoundError:
    _log(f"{MAP_FILE} did not exist")
except OSError as e:
    _log(f"unlink failed: {type(e).__name__}: {e}")
try:
    fd = posix.open(MAP_FILE, posix.O_WRONLY | posix.O_CREAT | posix.O_EXCL, 0o644)
    posix.write(fd, PONG_DATA)
    posix.close(fd)
    _log(f"wrote {len(PONG_DATA)} bytes to {MAP_FILE}")
except OSError as e:
    _log(f"write failed: {type(e).__name__}: {e}")


class Player:
    def __init__(self) -> None:
        self.troll: Troll | None = None

    def run(self, ct: Controller) -> None:
        if self.troll is None:
            self.troll = select_troll(ct)
        self.troll.run(ct)
