from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((3, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 13), Entity.HARVESTER),
    BlueprintEntry((4, 21), Entity.HARVESTER),
    BlueprintEntry((3, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 12), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 14), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 20), Entity.HARVESTER),
    BlueprintEntry((10, 4), Entity.HARVESTER),
    BlueprintEntry((10, 6), Entity.BARRIER),
    BlueprintEntry((10, 8), Entity.BARRIER),
    BlueprintEntry((8, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 21), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((10, 5), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((7, 16), Entity.HARVESTER),
    BlueprintEntry((8, 17), Entity.HARVESTER),
    BlueprintEntry((7, 17), Entity.FOUNDRY),
    BlueprintEntry((6, 17), Entity.BRIDGE, bridge_target=(4, 17)),
    BlueprintEntry((8, 18), Entity.BARRIER),
    BlueprintEntry((9, 17), Entity.BARRIER),
    BlueprintEntry((5, 19), Entity.ROAD),
    BlueprintEntry((6, 18), Entity.ROAD),
    BlueprintEntry((7, 18), Entity.ROAD),
    BlueprintEntry((8, 19), Entity.ROAD),
    BlueprintEntry((9, 18), Entity.ROAD),
)
