from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 4), Entity.FOUNDRY),
    BlueprintEntry((5, 18), Entity.FOUNDRY),
    BlueprintEntry((5, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 9), Entity.HARVESTER),
    BlueprintEntry((5, 3), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 4), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 17), Entity.BRIDGE, bridge_target=(5, 18)),
    BlueprintEntry((4, 20), Entity.BRIDGE, bridge_target=(5, 18)),
    BlueprintEntry((5, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 4), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((1, 17), Entity.BRIDGE, bridge_target=(3, 17)),
    BlueprintEntry((3, 20), Entity.HARVESTER),
    BlueprintEntry((5, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 14), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 7), Entity.HARVESTER),
    BlueprintEntry((3, 3), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 1), Entity.BRIDGE, bridge_target=(6, 3)),
    BlueprintEntry((0, 17), Entity.HARVESTER),
    BlueprintEntry((5, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 6), Entity.SENTINEL, direction=Direction.SOUTHEAST),
    BlueprintEntry((2, 3), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 18), Entity.HARVESTER),
    BlueprintEntry((8, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 0), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 1), Entity.HARVESTER),
    BlueprintEntry((8, 5), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 14), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((5, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 5), Entity.HARVESTER),
    BlueprintEntry((9, 2), Entity.HARVESTER),
    BlueprintEntry((9, 19), Entity.HARVESTER),
    BlueprintEntry((9, 0), Entity.HARVESTER),
    BlueprintEntry((0, 1), Entity.BRIDGE, bridge_target=(2, 3)),
    BlueprintEntry((8, 4), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 15), Entity.HARVESTER),
    BlueprintEntry((5, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 4), Entity.HARVESTER),
    BlueprintEntry((9, 3), Entity.HARVESTER),
    BlueprintEntry((1, 1), Entity.HARVESTER),
    BlueprintEntry((0, 0), Entity.HARVESTER),
    BlueprintEntry((8, 3), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 16), Entity.ROAD),
    BlueprintEntry((8, 2), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 8), Entity.ROAD),
    BlueprintEntry((5, 19), Entity.ROAD),
    BlueprintEntry((9, 10), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((9, 11), Entity.HARVESTER),
    BlueprintEntry((9, 12), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((9, 17), Entity.ROAD),
    BlueprintEntry((8, 9), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 11), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 20), Entity.ROAD),
    BlueprintEntry((8, 15), Entity.ROAD),
    BlueprintEntry((9, 8), Entity.HARVESTER),
    BlueprintEntry((8, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
)
