from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((4, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 17), Entity.HARVESTER),
    BlueprintEntry((16, 18), Entity.HARVESTER),
    BlueprintEntry((16, 16), Entity.ROAD),
    BlueprintEntry((17, 17), Entity.BRIDGE, bridge_target=(14, 17)),
    BlueprintEntry((17, 18), Entity.HARVESTER),
    BlueprintEntry((18, 17), Entity.HARVESTER),
    BlueprintEntry((18, 16), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((18, 18), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((3, 17), Entity.HARVESTER),
    BlueprintEntry((3, 18), Entity.HARVESTER),
    BlueprintEntry((12, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((15, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 18), Entity.FOUNDRY),
    BlueprintEntry((18, 20), Entity.BARRIER),
    BlueprintEntry((12, 8), Entity.BARRIER),
    BlueprintEntry((12, 9), Entity.BARRIER),
    BlueprintEntry((13, 10), Entity.BARRIER),
    BlueprintEntry((14, 11), Entity.BARRIER),
    BlueprintEntry((15, 12), Entity.BARRIER),
    BlueprintEntry((16, 29), Entity.BARRIER),
    BlueprintEntry((12, 27), Entity.HARVESTER),
    BlueprintEntry((11, 26), Entity.HARVESTER),
    BlueprintEntry((12, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((15, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 14), Entity.ROAD),
    BlueprintEntry((11, 13), Entity.ROAD),
    BlueprintEntry((11, 10), Entity.ROAD),
    BlueprintEntry((11, 9), Entity.ROAD),
    BlueprintEntry((11, 12), Entity.ROAD),
    BlueprintEntry((12, 11), Entity.ROAD),
    BlueprintEntry((13, 12), Entity.ROAD),
    BlueprintEntry((14, 13), Entity.ROAD),
    BlueprintEntry((15, 19), Entity.ROAD),
    BlueprintEntry((16, 20), Entity.ROAD),
    BlueprintEntry((17, 20), Entity.ROAD),
    BlueprintEntry((13, 27), Entity.ROAD),
    BlueprintEntry((14, 28), Entity.ROAD),
    BlueprintEntry((15, 28), Entity.ROAD),
)
