from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((7, 16), Entity.BARRIER),
    BlueprintEntry((8, 16), Entity.BARRIER),
    BlueprintEntry((13, 27), Entity.BARRIER),
    BlueprintEntry((13, 26), Entity.BARRIER),
    BlueprintEntry((13, 24), Entity.BARRIER),
    BlueprintEntry((13, 25), Entity.BARRIER),
    BlueprintEntry((13, 23), Entity.BARRIER),
    BlueprintEntry((13, 21), Entity.BARRIER),
    BlueprintEntry((13, 20), Entity.BARRIER),
    BlueprintEntry((13, 19), Entity.BARRIER),
    BlueprintEntry((13, 18), Entity.BARRIER),
    BlueprintEntry((13, 17), Entity.BARRIER),
    BlueprintEntry((12, 17), Entity.BARRIER),
    BlueprintEntry((2, 16), Entity.BARRIER),
    BlueprintEntry((1, 16), Entity.BARRIER),
    BlueprintEntry((1, 17), Entity.BARRIER),
    BlueprintEntry((1, 18), Entity.BARRIER),
    BlueprintEntry((3, 17), Entity.HARVESTER),
    BlueprintEntry((4, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 16), Entity.BARRIER),
    BlueprintEntry((5, 16), Entity.BARRIER),
    BlueprintEntry((10, 26), Entity.HARVESTER),
    BlueprintEntry((9, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 20), Entity.BRIDGE, bridge_target=(3, 18)),
    BlueprintEntry((3, 18), Entity.FOUNDRY),
    BlueprintEntry((4, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 18), Entity.HARVESTER),
    BlueprintEntry((10, 27), Entity.HARVESTER),
    BlueprintEntry((9, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 17), Entity.BARRIER),
    BlueprintEntry((17, 18), Entity.BARRIER),
    BlueprintEntry((12, 29), Entity.BARRIER),
)
