from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((29, 46), Entity.FOUNDRY),
    BlueprintEntry((27, 46), Entity.HARVESTER),
    BlueprintEntry((33, 47), Entity.HARVESTER),
    BlueprintEntry((28, 46), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((29, 47), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((30, 47), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((31, 47), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((32, 47), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((29, 45), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 44), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 43), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 42), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 41), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 40), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 39), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 38), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 37), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 36), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 35), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 34), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((27, 27), Entity.HARVESTER),
    BlueprintEntry((26, 27), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((26, 28), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((26, 29), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((26, 30), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((25, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((24, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((23, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((21, 30), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((22, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((21, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((21, 31), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((21, 29), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((21, 28), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((21, 27), Entity.HARVESTER),
    BlueprintEntry((27, 36), Entity.ROAD),
    BlueprintEntry((23, 38), Entity.HARVESTER),
    BlueprintEntry((23, 37), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((23, 36), Entity.FOUNDRY),
    BlueprintEntry((23, 35), Entity.BRIDGE, bridge_target=(23, 32)),
    BlueprintEntry((26, 36), Entity.ROAD),
    BlueprintEntry((25, 36), Entity.ROAD),
    BlueprintEntry((24, 36), Entity.ROAD),
    BlueprintEntry((18, 36), Entity.HARVESTER),
    BlueprintEntry((19, 36), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((20, 36), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((21, 36), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((22, 36), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((17, 27), Entity.HARVESTER),
    BlueprintEntry((17, 28), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((18, 28), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((19, 28), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((20, 28), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((19, 38), Entity.BARRIER),
    BlueprintEntry((19, 37), Entity.ROAD),
    BlueprintEntry((28, 35), Entity.ROAD),
    BlueprintEntry((28, 34), Entity.ROAD),
    BlueprintEntry((17, 26), Entity.BARRIER),
    BlueprintEntry((28, 27), Entity.BARRIER),
)
