from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((8, 27), Entity.HARVESTER),
    BlueprintEntry((11, 24), Entity.HARVESTER),
    BlueprintEntry((11, 23), Entity.HARVESTER),
    BlueprintEntry((9, 27), Entity.HARVESTER),
    BlueprintEntry((8, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 20), Entity.HARVESTER),
    BlueprintEntry((8, 20), Entity.HARVESTER),
    BlueprintEntry((9, 20), Entity.HARVESTER),
    BlueprintEntry((7, 21), Entity.FOUNDRY),
    BlueprintEntry((7, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 19), Entity.BARRIER),
    BlueprintEntry((14, 20), Entity.ROAD),
    BlueprintEntry((13, 21), Entity.ROAD),
    BlueprintEntry((12, 22), Entity.ROAD),
    BlueprintEntry((11, 22), Entity.ROAD),
    BlueprintEntry((6, 18), Entity.BRIDGE, bridge_target=(6, 21)),
    BlueprintEntry((6, 21), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 12), Entity.HARVESTER),
    BlueprintEntry((6, 11), Entity.HARVESTER),
    BlueprintEntry((6, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 20), Entity.ROAD),
    BlueprintEntry((9, 19), Entity.ROAD),
    BlueprintEntry((8, 19), Entity.ROAD),
    BlueprintEntry((7, 19), Entity.ROAD),
)
