from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 27), Entity.HARVESTER),
    BlueprintEntry((5, 28), Entity.HARVESTER),
    BlueprintEntry((5, 29), Entity.HARVESTER),
    BlueprintEntry((4, 27), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 30), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 31), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 32), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 30), Entity.HARVESTER),
    BlueprintEntry((5, 31), Entity.HARVESTER),
    BlueprintEntry((5, 32), Entity.HARVESTER),
    BlueprintEntry((5, 24), Entity.HARVESTER),
    BlueprintEntry((5, 25), Entity.HARVESTER),
    BlueprintEntry((5, 26), Entity.HARVESTER),
    BlueprintEntry((4, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 25), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 26), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 39), Entity.BRIDGE, bridge_target=(4, 37)),
    BlueprintEntry((6, 39), Entity.HARVESTER),
    BlueprintEntry((5, 38), Entity.ROAD),
    BlueprintEntry((4, 37), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 30), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 31), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 32), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 33), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 34), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 35), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 36), Entity.FOUNDRY),
    BlueprintEntry((5, 33), Entity.HARVESTER),
    BlueprintEntry((5, 34), Entity.HARVESTER),
    BlueprintEntry((5, 35), Entity.HARVESTER),
    BlueprintEntry((5, 36), Entity.HARVESTER),
    BlueprintEntry((3, 36), Entity.ROAD),
)
