from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((28, 41), Entity.HARVESTER),
    BlueprintEntry((27, 40), Entity.HARVESTER),
    BlueprintEntry((28, 39), Entity.HARVESTER),
    BlueprintEntry((28, 40), Entity.BRIDGE, bridge_target=(28, 43)),
    BlueprintEntry((28, 43), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((21, 43), Entity.HARVESTER),
    BlueprintEntry((18, 42), Entity.BARRIER),
    BlueprintEntry((18, 36), Entity.BARRIER),
    BlueprintEntry((36, 42), Entity.BARRIER),
    BlueprintEntry((36, 36), Entity.BARRIER),
    BlueprintEntry((33, 39), Entity.BARRIER),
    BlueprintEntry((27, 39), Entity.BARRIER),
    BlueprintEntry((23, 35), Entity.BARRIER),
    BlueprintEntry((25, 35), Entity.BARRIER),
    BlueprintEntry((29, 35), Entity.BARRIER),
    BlueprintEntry((31, 35), Entity.BARRIER),
    BlueprintEntry((21, 40), Entity.HARVESTER),
    BlueprintEntry((22, 39), Entity.HARVESTER),
    BlueprintEntry((21, 39), Entity.BARRIER),
    BlueprintEntry((22, 40), Entity.BRIDGE, bridge_target=(22, 43)),
    BlueprintEntry((22, 43), Entity.FOUNDRY),
    BlueprintEntry((21, 44), Entity.HARVESTER),
    BlueprintEntry((21, 45), Entity.HARVESTER),
    BlueprintEntry((22, 41), Entity.HARVESTER),
    BlueprintEntry((22, 44), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((22, 45), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((23, 43), Entity.BRIDGE, bridge_target=(25, 44)),
    BlueprintEntry((25, 44), Entity.CONVEYOR, direction=Direction.EAST),
)
