from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((26, 41), Entity.HARVESTER),
    BlueprintEntry((28, 41), Entity.HARVESTER),
    BlueprintEntry((27, 40), Entity.HARVESTER),
    BlueprintEntry((26, 39), Entity.HARVESTER),
    BlueprintEntry((28, 39), Entity.HARVESTER),
    BlueprintEntry((26, 40), Entity.BRIDGE, bridge_target=(26, 43)),
    BlueprintEntry((28, 40), Entity.BRIDGE, bridge_target=(28, 43)),
    BlueprintEntry((28, 43), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((25, 43), Entity.ROAD),
    BlueprintEntry((24, 42), Entity.ROAD),
    BlueprintEntry((25, 41), Entity.ROAD),
    BlueprintEntry((29, 41), Entity.ROAD),
    BlueprintEntry((30, 42), Entity.ROAD),
    BlueprintEntry((29, 43), Entity.ROAD),
    BlueprintEntry((26, 43), Entity.FOUNDRY),
    BlueprintEntry((23, 43), Entity.BRIDGE, bridge_target=(26, 43)),
    BlueprintEntry((23, 44), Entity.HARVESTER),
    BlueprintEntry((22, 43), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((21, 43), Entity.HARVESTER),
    BlueprintEntry((18, 42), Entity.BARRIER),
    BlueprintEntry((18, 36), Entity.BARRIER),
    BlueprintEntry((24, 36), Entity.BARRIER),
    BlueprintEntry((30, 36), Entity.BARRIER),
    BlueprintEntry((36, 42), Entity.BARRIER),
    BlueprintEntry((36, 36), Entity.BARRIER),
    BlueprintEntry((23, 41), Entity.ROAD),
    BlueprintEntry((22, 41), Entity.ROAD),
    BlueprintEntry((21, 41), Entity.ROAD),
    BlueprintEntry((20, 41), Entity.ROAD),
    BlueprintEntry((25, 39), Entity.ROAD),
    BlueprintEntry((25, 38), Entity.ROAD),
    BlueprintEntry((25, 37), Entity.ROAD),
    BlueprintEntry((29, 39), Entity.ROAD),
    BlueprintEntry((29, 38), Entity.ROAD),
    BlueprintEntry((29, 37), Entity.ROAD),
    BlueprintEntry((19, 41), Entity.ROAD),
    BlueprintEntry((19, 40), Entity.ROAD),
    BlueprintEntry((19, 39), Entity.ROAD),
    BlueprintEntry((19, 38), Entity.ROAD),
    BlueprintEntry((19, 37), Entity.ROAD),
    BlueprintEntry((31, 41), Entity.ROAD),
    BlueprintEntry((32, 41), Entity.ROAD),
    BlueprintEntry((33, 41), Entity.ROAD),
    BlueprintEntry((34, 41), Entity.ROAD),
    BlueprintEntry((35, 41), Entity.ROAD),
    BlueprintEntry((35, 40), Entity.ROAD),
    BlueprintEntry((35, 39), Entity.ROAD),
    BlueprintEntry((35, 37), Entity.ROAD),
    BlueprintEntry((35, 38), Entity.ROAD),
)
