from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((14, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 19), Entity.FOUNDRY),
    BlueprintEntry((11, 19), Entity.HARVESTER),
    BlueprintEntry((15, 21), Entity.HARVESTER),
    BlueprintEntry((13, 16), Entity.HARVESTER),
    BlueprintEntry((13, 17), Entity.BRIDGE, bridge_target=(12, 19)),
    BlueprintEntry((11, 20), Entity.BARRIER),
    BlueprintEntry((16, 21), Entity.BARRIER),
    BlueprintEntry((15, 20), Entity.BARRIER),
    BlueprintEntry((15, 22), Entity.BARRIER),
    BlueprintEntry((11, 28), Entity.BARRIER),
    BlueprintEntry((11, 29), Entity.BARRIER),
    BlueprintEntry((14, 18), Entity.BARRIER),
    BlueprintEntry((11, 18), Entity.BARRIER),
    BlueprintEntry((10, 19), Entity.BARRIER),
    BlueprintEntry((3, 29), Entity.BARRIER),
    BlueprintEntry((3, 25), Entity.BARRIER),
    BlueprintEntry((4, 25), Entity.BARRIER),
    BlueprintEntry((5, 25), Entity.BARRIER),
    BlueprintEntry((6, 25), Entity.BARRIER),
    BlueprintEntry((12, 22), Entity.BRIDGE, bridge_target=(10, 24)),
    BlueprintEntry((12, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 24), Entity.BRIDGE, bridge_target=(8, 26)),
    BlueprintEntry((8, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 24), Entity.BARRIER),
    BlueprintEntry((12, 26), Entity.BARRIER),
    BlueprintEntry((12, 25), Entity.BARRIER),
    BlueprintEntry((8, 22), Entity.BARRIER),
    BlueprintEntry((8, 23), Entity.BARRIER),
    BlueprintEntry((8, 24), Entity.BARRIER),
    BlueprintEntry((10, 20), Entity.BARRIER),
    BlueprintEntry((10, 18), Entity.BARRIER),
    BlueprintEntry((16, 20), Entity.BARRIER),
    BlueprintEntry((16, 22), Entity.BARRIER),
    BlueprintEntry((8, 21), Entity.BARRIER),
)
