from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((10, 16), Entity.HARVESTER),
    BlueprintEntry((10, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 23), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 25), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 26), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 27), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 23), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 25), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 26), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 27), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 16), Entity.HARVESTER),
    BlueprintEntry((11, 16), Entity.HARVESTER),
    BlueprintEntry((8, 16), Entity.HARVESTER),
    BlueprintEntry((8, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 16), Entity.HARVESTER),
    BlueprintEntry((13, 16), Entity.HARVESTER),
    BlueprintEntry((13, 17), Entity.CONVEYOR, direction=Direction.WEST),
)
