from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((10, 16), Entity.HARVESTER),
    BlueprintEntry((10, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 23), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 25), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 26), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 27), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 23), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 25), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 26), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 27), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 16), Entity.HARVESTER),
    BlueprintEntry((11, 16), Entity.HARVESTER),
    BlueprintEntry((8, 16), Entity.HARVESTER),
    BlueprintEntry((8, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 16), Entity.HARVESTER),
    BlueprintEntry((13, 16), Entity.HARVESTER),
    BlueprintEntry((13, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 24), Entity.HARVESTER),
    BlueprintEntry((16, 24), Entity.HARVESTER),
    BlueprintEntry((5, 24), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 24), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 24), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 23), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 24), Entity.FOUNDRY),
    BlueprintEntry((15, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 24), Entity.FOUNDRY),
    BlueprintEntry((13, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 23), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 16), Entity.BARRIER),
    BlueprintEntry((6, 16), Entity.BARRIER),
    BlueprintEntry((14, 16), Entity.BARRIER),
    BlueprintEntry((7, 17), Entity.ROAD),
    BlueprintEntry((6, 17), Entity.ROAD),
    BlueprintEntry((5, 18), Entity.ROAD),
    BlueprintEntry((3, 18), Entity.ROAD),
    BlueprintEntry((14, 17), Entity.ROAD),
    BlueprintEntry((15, 18), Entity.ROAD),
    BlueprintEntry((17, 18), Entity.ROAD),
    BlueprintEntry((18, 17), Entity.BARRIER),
    BlueprintEntry((19, 17), Entity.BARRIER),
    BlueprintEntry((2, 18), Entity.ROAD),
    BlueprintEntry((1, 17), Entity.BARRIER),
    BlueprintEntry((2, 17), Entity.BARRIER),
    BlueprintEntry((4, 17), Entity.BARRIER),
    BlueprintEntry((4, 18), Entity.ROAD),
    BlueprintEntry((16, 17), Entity.BARRIER),
    BlueprintEntry((16, 18), Entity.ROAD),
    BlueprintEntry((18, 18), Entity.ROAD),
)
