from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((21, 5), Entity.HARVESTER),
    BlueprintEntry((21, 7), Entity.HARVESTER),
    BlueprintEntry((24, 4), Entity.BARRIER),
    BlueprintEntry((24, 9), Entity.BARRIER),
    BlueprintEntry((10, 15), Entity.BARRIER),
    BlueprintEntry((7, 12), Entity.BARRIER),
    BlueprintEntry((14, 16), Entity.BARRIER),
    BlueprintEntry((18, 12), Entity.BARRIER),
    BlueprintEntry((19, 11), Entity.BARRIER),
    BlueprintEntry((20, 7), Entity.FOUNDRY),
    BlueprintEntry((12, 13), Entity.HARVESTER),
    BlueprintEntry((13, 13), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((14, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 11), Entity.BRIDGE, bridge_target=(16, 9)),
    BlueprintEntry((16, 9), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((15, 10), Entity.ROAD),
    BlueprintEntry((17, 8), Entity.ROAD),
    BlueprintEntry((17, 9), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((18, 9), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((19, 9), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((20, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((21, 6), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((20, 6), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 12), Entity.ROAD),
    BlueprintEntry((9, 12), Entity.ROAD),
    BlueprintEntry((10, 12), Entity.ROAD),
    BlueprintEntry((11, 12), Entity.ROAD),
    BlueprintEntry((12, 12), Entity.ROAD),
    BlueprintEntry((11, 15), Entity.ROAD),
    BlueprintEntry((12, 15), Entity.ROAD),
    BlueprintEntry((13, 15), Entity.ROAD),
    BlueprintEntry((14, 14), Entity.ROAD),
    BlueprintEntry((19, 10), Entity.ROAD),
    BlueprintEntry((15, 12), Entity.ROAD),
    BlueprintEntry((16, 12), Entity.ROAD),
    BlueprintEntry((17, 12), Entity.ROAD),
    BlueprintEntry((22, 6), Entity.ROAD),
    BlueprintEntry((23, 5), Entity.ROAD),
    BlueprintEntry((23, 7), Entity.ROAD),
    BlueprintEntry((23, 8), Entity.ROAD),
)
