from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((21, 5), Entity.HARVESTER),
    BlueprintEntry((21, 7), Entity.HARVESTER),
    BlueprintEntry((20, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((20, 5), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 13), Entity.HARVESTER),
    BlueprintEntry((19, 16), Entity.HARVESTER),
    BlueprintEntry((13, 13), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((14, 13), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((15, 13), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((16, 13), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((17, 13), Entity.BRIDGE, bridge_target=(19, 14)),
    BlueprintEntry((19, 13), Entity.BRIDGE, bridge_target=(19, 10)),
    BlueprintEntry((19, 14), Entity.FOUNDRY),
    BlueprintEntry((19, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((19, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((19, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((19, 11), Entity.ROAD),
    BlueprintEntry((18, 12), Entity.ROAD),
    BlueprintEntry((20, 12), Entity.ROAD),
    BlueprintEntry((20, 13), Entity.ROAD),
    BlueprintEntry((20, 14), Entity.ROAD),
    BlueprintEntry((20, 15), Entity.ROAD),
    BlueprintEntry((19, 15), Entity.CONVEYOR, direction=Direction.NORTH),
)
