from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((10, 15), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 22), Entity.HARVESTER),
    BlueprintEntry((9, 22), Entity.HARVESTER),
    BlueprintEntry((11, 22), Entity.HARVESTER),
    BlueprintEntry((11, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 22), Entity.HARVESTER),
    BlueprintEntry((3, 21), Entity.HARVESTER),
    BlueprintEntry((4, 21), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 21), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 21), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 21), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 21), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((13, 22), Entity.HARVESTER),
    BlueprintEntry((14, 22), Entity.HARVESTER),
    BlueprintEntry((15, 22), Entity.HARVESTER),
    BlueprintEntry((16, 22), Entity.HARVESTER),
    BlueprintEntry((16, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((13, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((13, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((13, 18), Entity.BRIDGE, bridge_target=(13, 15)),
    BlueprintEntry((9, 21), Entity.FOUNDRY),
    BlueprintEntry((10, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 20), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 16), Entity.HARVESTER),
    BlueprintEntry((3, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((17, 22), Entity.SENTINEL, direction=Direction.EAST),
)
