from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 19), Entity.HARVESTER),
    BlueprintEntry((5, 11), Entity.HARVESTER),
    BlueprintEntry((4, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 7), Entity.HARVESTER),
    BlueprintEntry((4, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 23), Entity.HARVESTER),
    BlueprintEntry((1, 15), Entity.HARVESTER),
    BlueprintEntry((1, 11), Entity.HARVESTER),
    BlueprintEntry((1, 7), Entity.HARVESTER),
    BlueprintEntry((1, 19), Entity.HARVESTER),
    BlueprintEntry((1, 23), Entity.HARVESTER),
    BlueprintEntry((2, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 19), Entity.BRIDGE, bridge_target=(4, 19)),
    BlueprintEntry((2, 11), Entity.BRIDGE, bridge_target=(4, 11)),
    BlueprintEntry((2, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 6), Entity.ROAD),
    BlueprintEntry((2, 6), Entity.ROAD),
    BlueprintEntry((2, 5), Entity.ROAD),
    BlueprintEntry((2, 4), Entity.ROAD),
    BlueprintEntry((2, 3), Entity.ROAD),
    BlueprintEntry((3, 2), Entity.ROAD),
    BlueprintEntry((4, 3), Entity.ROAD),
    BlueprintEntry((4, 4), Entity.ROAD),
    BlueprintEntry((4, 5), Entity.ROAD),
    BlueprintEntry((2, 24), Entity.ROAD),
    BlueprintEntry((2, 25), Entity.ROAD),
    BlueprintEntry((2, 26), Entity.ROAD),
    BlueprintEntry((2, 27), Entity.ROAD),
    BlueprintEntry((3, 28), Entity.ROAD),
    BlueprintEntry((4, 27), Entity.ROAD),
    BlueprintEntry((4, 26), Entity.ROAD),
    BlueprintEntry((4, 25), Entity.ROAD),
    BlueprintEntry((4, 24), Entity.ROAD),
    BlueprintEntry((2, 15), Entity.BRIDGE, bridge_target=(4, 15)),
    BlueprintEntry((13, 11), Entity.HARVESTER),
    BlueprintEntry((12, 11), Entity.BRIDGE, bridge_target=(9, 11)),
    BlueprintEntry((9, 11), Entity.BRIDGE, bridge_target=(6, 11)),
    BlueprintEntry((6, 11), Entity.FOUNDRY),
    BlueprintEntry((6, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 8), Entity.ROAD),
    BlueprintEntry((5, 3), Entity.ROAD),
    BlueprintEntry((6, 3), Entity.ROAD),
    BlueprintEntry((7, 2), Entity.ROAD),
    BlueprintEntry((8, 3), Entity.ROAD),
    BlueprintEntry((9, 4), Entity.ROAD),
    BlueprintEntry((9, 5), Entity.ROAD),
    BlueprintEntry((9, 6), Entity.ROAD),
    BlueprintEntry((9, 7), Entity.ROAD),
    BlueprintEntry((9, 8), Entity.ROAD),
    BlueprintEntry((9, 9), Entity.ROAD),
    BlueprintEntry((9, 10), Entity.ROAD),
    BlueprintEntry((10, 3), Entity.ROAD),
    BlueprintEntry((11, 2), Entity.ROAD),
    BlueprintEntry((12, 3), Entity.ROAD),
    BlueprintEntry((13, 4), Entity.ROAD),
    BlueprintEntry((13, 5), Entity.ROAD),
    BlueprintEntry((13, 6), Entity.ROAD),
    BlueprintEntry((13, 7), Entity.ROAD),
    BlueprintEntry((13, 8), Entity.ROAD),
    BlueprintEntry((13, 9), Entity.ROAD),
    BlueprintEntry((13, 10), Entity.ROAD),
    BlueprintEntry((6, 19), Entity.FOUNDRY),
    BlueprintEntry((6, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((15, 0), Entity.BARRIER),
    BlueprintEntry((15, 1), Entity.BARRIER),
    BlueprintEntry((15, 2), Entity.BARRIER),
    BlueprintEntry((14, 3), Entity.ROAD),
    BlueprintEntry((14, 2), Entity.ROAD),
    BlueprintEntry((14, 1), Entity.ROAD),
    BlueprintEntry((15, 28), Entity.BARRIER),
    BlueprintEntry((15, 29), Entity.BARRIER),
    BlueprintEntry((15, 30), Entity.BARRIER),
    BlueprintEntry((14, 11), Entity.ROAD),
    BlueprintEntry((13, 12), Entity.ROAD),
    BlueprintEntry((13, 13), Entity.ROAD),
    BlueprintEntry((13, 14), Entity.ROAD),
    BlueprintEntry((13, 15), Entity.ROAD),
    BlueprintEntry((13, 16), Entity.ROAD),
    BlueprintEntry((13, 17), Entity.ROAD),
    BlueprintEntry((13, 18), Entity.ROAD),
    BlueprintEntry((13, 19), Entity.HARVESTER),
    BlueprintEntry((9, 12), Entity.ROAD),
    BlueprintEntry((9, 13), Entity.ROAD),
    BlueprintEntry((9, 14), Entity.ROAD),
    BlueprintEntry((9, 15), Entity.ROAD),
    BlueprintEntry((9, 16), Entity.ROAD),
    BlueprintEntry((9, 17), Entity.ROAD),
    BlueprintEntry((9, 18), Entity.ROAD),
    BlueprintEntry((9, 19), Entity.BRIDGE, bridge_target=(6, 19)),
    BlueprintEntry((12, 19), Entity.BRIDGE, bridge_target=(9, 19)),
    BlueprintEntry((14, 19), Entity.ROAD),
    BlueprintEntry((14, 20), Entity.ROAD),
    BlueprintEntry((14, 21), Entity.ROAD),
    BlueprintEntry((14, 22), Entity.ROAD),
    BlueprintEntry((14, 23), Entity.ROAD),
    BlueprintEntry((14, 24), Entity.ROAD),
    BlueprintEntry((14, 25), Entity.ROAD),
    BlueprintEntry((14, 26), Entity.ROAD),
    BlueprintEntry((14, 27), Entity.ROAD),
    BlueprintEntry((14, 28), Entity.ROAD),
    BlueprintEntry((14, 29), Entity.ROAD),
    BlueprintEntry((6, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 18), Entity.CONVEYOR, direction=Direction.NORTH),
)
