from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 19), Entity.HARVESTER),
    BlueprintEntry((5, 11), Entity.HARVESTER),
    BlueprintEntry((4, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 7), Entity.HARVESTER),
    BlueprintEntry((4, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 23), Entity.HARVESTER),
    BlueprintEntry((1, 15), Entity.HARVESTER),
    BlueprintEntry((1, 11), Entity.HARVESTER),
    BlueprintEntry((1, 7), Entity.HARVESTER),
    BlueprintEntry((1, 19), Entity.HARVESTER),
    BlueprintEntry((1, 23), Entity.HARVESTER),
    BlueprintEntry((2, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 19), Entity.BRIDGE, bridge_target=(4, 19)),
    BlueprintEntry((2, 11), Entity.BRIDGE, bridge_target=(4, 11)),
    BlueprintEntry((2, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 6), Entity.ROAD),
    BlueprintEntry((2, 6), Entity.ROAD),
    BlueprintEntry((2, 5), Entity.ROAD),
    BlueprintEntry((2, 4), Entity.ROAD),
    BlueprintEntry((2, 3), Entity.ROAD),
    BlueprintEntry((3, 2), Entity.ROAD),
    BlueprintEntry((4, 3), Entity.ROAD),
    BlueprintEntry((4, 4), Entity.ROAD),
    BlueprintEntry((4, 5), Entity.ROAD),
    BlueprintEntry((2, 24), Entity.ROAD),
    BlueprintEntry((2, 25), Entity.ROAD),
    BlueprintEntry((2, 26), Entity.ROAD),
    BlueprintEntry((2, 27), Entity.ROAD),
    BlueprintEntry((3, 28), Entity.ROAD),
    BlueprintEntry((4, 27), Entity.ROAD),
    BlueprintEntry((4, 26), Entity.ROAD),
    BlueprintEntry((4, 25), Entity.ROAD),
    BlueprintEntry((4, 24), Entity.ROAD),
    BlueprintEntry((2, 15), Entity.BRIDGE, bridge_target=(4, 15)),
)
