from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((10, 16), Entity.HARVESTER),
    BlueprintEntry((10, 14), Entity.HARVESTER),
    BlueprintEntry((10, 15), Entity.FOUNDRY),
    BlueprintEntry((11, 17), Entity.HARVESTER),
    BlueprintEntry((12, 17), Entity.HARVESTER),
    BlueprintEntry((12, 13), Entity.HARVESTER),
    BlueprintEntry((13, 13), Entity.HARVESTER),
    BlueprintEntry((14, 14), Entity.HARVESTER),
    BlueprintEntry((13, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 17), Entity.HARVESTER),
    BlueprintEntry((13, 18), Entity.HARVESTER),
    BlueprintEntry((14, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 15), Entity.HARVESTER),
    BlueprintEntry((15, 16), Entity.HARVESTER),
    BlueprintEntry((14, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 14), Entity.ROAD),
    BlueprintEntry((22, 12), Entity.BARRIER),
    BlueprintEntry((16, 13), Entity.ROAD),
    BlueprintEntry((17, 13), Entity.ROAD),
    BlueprintEntry((18, 13), Entity.ROAD),
    BlueprintEntry((19, 12), Entity.ROAD),
    BlueprintEntry((21, 12), Entity.ROAD),
    BlueprintEntry((20, 12), Entity.ROAD),
    BlueprintEntry((23, 4), Entity.BARRIER),
    BlueprintEntry((19, 27), Entity.BARRIER),
    BlueprintEntry((21, 11), Entity.ROAD),
    BlueprintEntry((21, 10), Entity.ROAD),
    BlueprintEntry((21, 9), Entity.ROAD),
    BlueprintEntry((21, 7), Entity.ROAD),
    BlueprintEntry((21, 8), Entity.ROAD),
    BlueprintEntry((22, 6), Entity.ROAD),
    BlueprintEntry((22, 5), Entity.ROAD),
    BlueprintEntry((14, 18), Entity.ROAD),
    BlueprintEntry((14, 19), Entity.ROAD),
    BlueprintEntry((14, 20), Entity.ROAD),
    BlueprintEntry((15, 21), Entity.ROAD),
    BlueprintEntry((15, 22), Entity.ROAD),
    BlueprintEntry((15, 23), Entity.ROAD),
    BlueprintEntry((15, 24), Entity.ROAD),
    BlueprintEntry((16, 25), Entity.ROAD),
    BlueprintEntry((17, 26), Entity.ROAD),
    BlueprintEntry((18, 27), Entity.ROAD),
    BlueprintEntry((13, 11), Entity.BRIDGE, bridge_target=(13, 14)),
    BlueprintEntry((11, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 13), Entity.HARVESTER),
    BlueprintEntry((11, 12), Entity.HARVESTER),
    BlueprintEntry((13, 12), Entity.HARVESTER),
    BlueprintEntry((12, 11), Entity.HARVESTER),
    BlueprintEntry((14, 11), Entity.HARVESTER),
    BlueprintEntry((15, 12), Entity.HARVESTER),
    BlueprintEntry((14, 12), Entity.FOUNDRY),
    BlueprintEntry((14, 13), Entity.BRIDGE, bridge_target=(13, 14)),
    BlueprintEntry((15, 13), Entity.HARVESTER),
    BlueprintEntry((10, 17), Entity.BRIDGE, bridge_target=(11, 16)),
    BlueprintEntry((9, 17), Entity.HARVESTER),
    BlueprintEntry((10, 18), Entity.HARVESTER),
    BlueprintEntry((11, 19), Entity.HARVESTER),
    BlueprintEntry((11, 18), Entity.FOUNDRY),
    BlueprintEntry((12, 19), Entity.HARVESTER),
    BlueprintEntry((12, 18), Entity.BRIDGE, bridge_target=(12, 16)),
)
