from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((1, 1), Entity.HARVESTER),
    BlueprintEntry((10, 4), Entity.HARVESTER),
    BlueprintEntry((19, 1), Entity.HARVESTER),
    BlueprintEntry((2, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 3), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 2), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 3), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 4), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 2), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 3), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 4), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 6), Entity.HARVESTER),
    BlueprintEntry((2, 6), Entity.HARVESTER),
)
