from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 7), Entity.HARVESTER),
    BlueprintEntry((2, 19), Entity.HARVESTER),
    BlueprintEntry((2, 20), Entity.HARVESTER),
    BlueprintEntry((1, 4), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((1, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 14), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 26), Entity.HARVESTER),
    BlueprintEntry((6, 27), Entity.HARVESTER),
    BlueprintEntry((5, 26), Entity.HARVESTER),
    BlueprintEntry((2, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 27), Entity.BRIDGE, bridge_target=(3, 25)),
    BlueprintEntry((3, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 26), Entity.ROAD),
)
