from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((10, 30), Entity.HARVESTER),
    BlueprintEntry((9, 30), Entity.HARVESTER),
    BlueprintEntry((8, 30), Entity.HARVESTER),
    BlueprintEntry((9, 31), Entity.HARVESTER),
    BlueprintEntry((10, 31), Entity.FOUNDRY),
    BlueprintEntry((11, 31), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 28), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 29), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 29), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 29), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((1, 26), Entity.HARVESTER),
    BlueprintEntry((3, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 28), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 29), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 30), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 31), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 32), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 33), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 34), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 35), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 36), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 37), Entity.HARVESTER),
    BlueprintEntry((4, 36), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 36), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 36), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((7, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 39), Entity.HARVESTER),
    BlueprintEntry((7, 30), Entity.ROAD),
    BlueprintEntry((8, 31), Entity.BRIDGE, bridge_target=(10, 31)),
    BlueprintEntry((11, 30), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 29), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 28), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 37), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 38), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 36), Entity.BRIDGE, bridge_target=(9, 34)),
    BlueprintEntry((8, 35), Entity.ROAD),
    BlueprintEntry((9, 34), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 34), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 33), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 32), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((11, 32), Entity.CONVEYOR, direction=Direction.NORTH),
)
