from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((1, 1), Entity.HARVESTER),
    BlueprintEntry((10, 4), Entity.HARVESTER),
    BlueprintEntry((19, 1), Entity.HARVESTER),
    BlueprintEntry((2, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 3), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 2), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 3), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 4), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 2), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 3), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 4), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 6), Entity.HARVESTER),
    BlueprintEntry((2, 6), Entity.HARVESTER),
    BlueprintEntry((9, 9), Entity.HARVESTER),
    BlueprintEntry((7, 7), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 6), Entity.ROAD),
    BlueprintEntry((5, 5), Entity.ROAD),
    BlueprintEntry((4, 4), Entity.ROAD),
    BlueprintEntry((3, 4), Entity.ROAD),
    BlueprintEntry((4, 3), Entity.ROAD),
    BlueprintEntry((4, 2), Entity.ROAD),
    BlueprintEntry((11, 9), Entity.HARVESTER),
    BlueprintEntry((9, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 4), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 3), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 8), Entity.FOUNDRY),
    BlueprintEntry((10, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((13, 8), Entity.HARVESTER),
    BlueprintEntry((9, 8), Entity.BRIDGE, bridge_target=(9, 5)),
    BlueprintEntry((17, 5), Entity.ROAD),
    BlueprintEntry((16, 5), Entity.ROAD),
    BlueprintEntry((15, 5), Entity.ROAD),
    BlueprintEntry((14, 6), Entity.ROAD),
    BlueprintEntry((13, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 8), Entity.HARVESTER),
    BlueprintEntry((8, 7), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 7), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 8), Entity.BREACH, direction=Direction.SOUTH),
    BlueprintEntry((5, 8), Entity.BARRIER),
    BlueprintEntry((6, 8), Entity.BARRIER),
    BlueprintEntry((8, 9), Entity.BARRIER),
    BlueprintEntry((12, 9), Entity.BARRIER),
    BlueprintEntry((13, 9), Entity.BARRIER),
    BlueprintEntry((14, 8), Entity.BARRIER),
    BlueprintEntry((15, 8), Entity.BARRIER),
    BlueprintEntry((7, 9), Entity.BARRIER),
    BlueprintEntry((1, 8), Entity.BARRIER),
    BlueprintEntry((0, 8), Entity.BARRIER),
    BlueprintEntry((19, 8), Entity.BARRIER),
    BlueprintEntry((20, 8), Entity.BARRIER),
    BlueprintEntry((19, 7), Entity.ROAD),
    BlueprintEntry((19, 6), Entity.ROAD),
    BlueprintEntry((1, 7), Entity.ROAD),
    BlueprintEntry((1, 6), Entity.ROAD),
    BlueprintEntry((6, 7), Entity.ROAD),
    BlueprintEntry((14, 7), Entity.ROAD),
    BlueprintEntry((8, 8), Entity.ROAD),
)
