from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 24), Entity.HARVESTER),
    BlueprintEntry((8, 23), Entity.HARVESTER),
    BlueprintEntry((10, 22), Entity.HARVESTER),
    BlueprintEntry((3, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((21, 28), Entity.HARVESTER),
    BlueprintEntry((20, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((19, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 29), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 28), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((23, 26), Entity.HARVESTER),
    BlueprintEntry((22, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((21, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((20, 28), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((20, 26), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((20, 27), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 23), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 25), Entity.FOUNDRY),
    BlueprintEntry((9, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 25), Entity.SPLITTER, direction=Direction.WEST),
    BlueprintEntry((7, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 22), Entity.BARRIER),
    BlueprintEntry((10, 24), Entity.BARRIER),
    BlueprintEntry((11, 23), Entity.BARRIER),
    BlueprintEntry((9, 20), Entity.BARRIER),
    BlueprintEntry((9, 19), Entity.BARRIER),
    BlueprintEntry((9, 18), Entity.BARRIER),
    BlueprintEntry((10, 25), Entity.BARRIER),
    BlueprintEntry((10, 26), Entity.BARRIER),
    BlueprintEntry((5, 17), Entity.BARRIER),
    BlueprintEntry((6, 17), Entity.BARRIER),
    BlueprintEntry((7, 17), Entity.BARRIER),
    BlueprintEntry((19, 28), Entity.LAUNCHER),
    BlueprintEntry((8, 26), Entity.SENTINEL, direction=Direction.SOUTHEAST),
    BlueprintEntry((11, 21), Entity.BARRIER),
    BlueprintEntry((10, 21), Entity.BARRIER),
    BlueprintEntry((10, 23), Entity.BARRIER),
    BlueprintEntry((9, 21), Entity.BARRIER),
    BlueprintEntry((1, 24), Entity.HARVESTER),
    BlueprintEntry((2, 24), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 22), Entity.BARRIER),
    BlueprintEntry((7, 23), Entity.BARRIER),
    BlueprintEntry((8, 24), Entity.BARRIER),
    BlueprintEntry((5, 23), Entity.BARRIER),
    BlueprintEntry((6, 24), Entity.BARRIER),
    BlueprintEntry((1, 25), Entity.BARRIER),
    BlueprintEntry((0, 24), Entity.BARRIER),
    BlueprintEntry((1, 23), Entity.BARRIER),
    BlueprintEntry((1, 17), Entity.BARRIER),
    BlueprintEntry((0, 17), Entity.BARRIER),
)
