from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((6, 12), Entity.HARVESTER),
    BlueprintEntry((1, 24), Entity.HARVESTER),
    BlueprintEntry((5, 24), Entity.HARVESTER),
    BlueprintEntry((8, 23), Entity.HARVESTER),
    BlueprintEntry((10, 22), Entity.HARVESTER),
    BlueprintEntry((12, 21), Entity.HARVESTER),
    BlueprintEntry((6, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((2, 24), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 20), Entity.HARVESTER),
    BlueprintEntry((15, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((16, 18), Entity.HARVESTER),
    BlueprintEntry((21, 28), Entity.HARVESTER),
    BlueprintEntry((20, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((19, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 29), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 28), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((23, 26), Entity.HARVESTER),
    BlueprintEntry((22, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((21, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((1, 23), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((20, 28), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((20, 26), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((20, 27), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 23), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 25), Entity.FOUNDRY),
    BlueprintEntry((9, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 20), Entity.ROAD),
    BlueprintEntry((9, 21), Entity.ROAD),
    BlueprintEntry((15, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((16, 19), Entity.SENTINEL, direction=Direction.WEST),
)
