from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((10, 30), Entity.HARVESTER),
    BlueprintEntry((9, 30), Entity.HARVESTER),
    BlueprintEntry((8, 30), Entity.HARVESTER),
    BlueprintEntry((9, 31), Entity.HARVESTER),
    BlueprintEntry((15, 30), Entity.HARVESTER),
    BlueprintEntry((15, 31), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 32), Entity.FOUNDRY),
    BlueprintEntry((12, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 33), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 33), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 33), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 33), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 30), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 33), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 31), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 29), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 28), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 31), Entity.BARRIER),
    BlueprintEntry((9, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 30), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 29), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 31), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 32), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 31), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((10, 29), Entity.SENTINEL, direction=Direction.WEST),
)
