from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((11, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 27), Entity.HARVESTER),
    BlueprintEntry((10, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 25), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 27), Entity.HARVESTER),
    BlueprintEntry((4, 23), Entity.HARVESTER),
    BlueprintEntry((12, 27), Entity.SENTINEL, direction=Direction.NORTH),
    BlueprintEntry((14, 14), Entity.BARRIER),
    BlueprintEntry((27, 27), Entity.HARVESTER),
    BlueprintEntry((27, 26), Entity.FOUNDRY),
    BlueprintEntry((26, 22), Entity.HARVESTER),
    BlueprintEntry((27, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((27, 23), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((27, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((27, 25), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((25, 22), Entity.BARRIER),
    BlueprintEntry((26, 21), Entity.BARRIER),
    BlueprintEntry((26, 23), Entity.BARRIER),
    BlueprintEntry((25, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((26, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((24, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((23, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((22, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((21, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((20, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((19, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 27), Entity.HARVESTER),
    BlueprintEntry((13, 28), Entity.BARRIER),
    BlueprintEntry((14, 28), Entity.BARRIER),
    BlueprintEntry((15, 27), Entity.BARRIER),
    BlueprintEntry((15, 15), Entity.HARVESTER),
    BlueprintEntry((15, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 14), Entity.ROAD),
    BlueprintEntry((14, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((16, 15), Entity.ROAD),
    BlueprintEntry((5, 23), Entity.BARRIER),
    BlueprintEntry((28, 26), Entity.ROAD),
)
