from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((4, 46), Entity.HARVESTER),
    BlueprintEntry((5, 45), Entity.HARVESTER),
    BlueprintEntry((15, 45), Entity.HARVESTER),
    BlueprintEntry((16, 46), Entity.HARVESTER),
    BlueprintEntry((5, 46), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 46), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 46), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 46), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 46), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 46), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 46), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 46), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 46), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 46), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 46), Entity.FOUNDRY),
    BlueprintEntry((4, 45), Entity.HARVESTER),
    BlueprintEntry((5, 44), Entity.HARVESTER),
    BlueprintEntry((15, 44), Entity.HARVESTER),
    BlueprintEntry((16, 45), Entity.HARVESTER),
    BlueprintEntry((4, 47), Entity.ROAD),
    BlueprintEntry((3, 46), Entity.ROAD),
    BlueprintEntry((3, 45), Entity.ROAD),
    BlueprintEntry((4, 44), Entity.BRIDGE, bridge_target=(6, 46)),
    BlueprintEntry((16, 44), Entity.BRIDGE, bridge_target=(14, 46)),
    BlueprintEntry((16, 47), Entity.ROAD),
    BlueprintEntry((17, 46), Entity.ROAD),
    BlueprintEntry((17, 45), Entity.ROAD),
    BlueprintEntry((5, 43), Entity.BARRIER),
    BlueprintEntry((4, 43), Entity.BARRIER),
    BlueprintEntry((3, 43), Entity.BARRIER),
    BlueprintEntry((2, 43), Entity.BARRIER),
    BlueprintEntry((0, 43), Entity.BARRIER),
    BlueprintEntry((1, 43), Entity.BARRIER),
    BlueprintEntry((15, 43), Entity.BARRIER),
    BlueprintEntry((16, 43), Entity.BARRIER),
    BlueprintEntry((17, 43), Entity.BARRIER),
    BlueprintEntry((18, 43), Entity.BARRIER),
    BlueprintEntry((19, 43), Entity.BARRIER),
    BlueprintEntry((20, 43), Entity.BARRIER),
    BlueprintEntry((18, 44), Entity.ROAD),
    BlueprintEntry((19, 44), Entity.ROAD),
    BlueprintEntry((20, 44), Entity.ROAD),
    BlueprintEntry((1, 44), Entity.ROAD),
    BlueprintEntry((2, 44), Entity.ROAD),
    BlueprintEntry((0, 44), Entity.ROAD),
)
