from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((4, 46), Entity.HARVESTER),
    BlueprintEntry((5, 45), Entity.HARVESTER),
    BlueprintEntry((15, 45), Entity.HARVESTER),
    BlueprintEntry((16, 46), Entity.HARVESTER),
    BlueprintEntry((5, 46), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 46), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 46), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 46), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 46), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 46), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 46), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 46), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 46), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 46), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 46), Entity.FOUNDRY),
    BlueprintEntry((4, 45), Entity.HARVESTER),
    BlueprintEntry((5, 44), Entity.HARVESTER),
    BlueprintEntry((15, 44), Entity.HARVESTER),
    BlueprintEntry((16, 45), Entity.HARVESTER),
    BlueprintEntry((4, 47), Entity.ROAD),
    BlueprintEntry((3, 46), Entity.ROAD),
    BlueprintEntry((3, 45), Entity.ROAD),
    BlueprintEntry((4, 44), Entity.BRIDGE, bridge_target=(6, 46)),
    BlueprintEntry((16, 44), Entity.BRIDGE, bridge_target=(14, 46)),
    BlueprintEntry((16, 47), Entity.ROAD),
    BlueprintEntry((17, 46), Entity.ROAD),
    BlueprintEntry((17, 45), Entity.ROAD),
)
