from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((11, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 12), Entity.FOUNDRY),
    BlueprintEntry((6, 15), Entity.HARVESTER),
    BlueprintEntry((7, 11), Entity.HARVESTER),
    BlueprintEntry((4, 12), Entity.HARVESTER),
    BlueprintEntry((5, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 11), Entity.ROAD),
    BlueprintEntry((8, 9), Entity.HARVESTER),
    BlueprintEntry((11, 11), Entity.HARVESTER),
    BlueprintEntry((7, 9), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 9), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 14), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 13), Entity.BRIDGE, bridge_target=(13, 14)),
    BlueprintEntry((13, 14), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((14, 14), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((15, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 16), Entity.SPLITTER, direction=Direction.SOUTH),
    BlueprintEntry((16, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((17, 16), Entity.BREACH, direction=Direction.SOUTHEAST),
    BlueprintEntry((15, 17), Entity.ROAD),
    BlueprintEntry((8, 10), Entity.ROAD),
)
