from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((11, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 18), Entity.HARVESTER),
    BlueprintEntry((17, 22), Entity.HARVESTER),
    BlueprintEntry((17, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 18), Entity.BRIDGE, bridge_target=(12, 17)),
    BlueprintEntry((12, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 17), Entity.ROAD),
    BlueprintEntry((10, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 13), Entity.ROAD),
    BlueprintEntry((13, 12), Entity.BRIDGE, bridge_target=(14, 14)),
    BlueprintEntry((13, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 8), Entity.HARVESTER),
    BlueprintEntry((13, 8), Entity.FOUNDRY),
    BlueprintEntry((14, 8), Entity.ROAD),
    BlueprintEntry((13, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 4), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 4), Entity.HARVESTER),
    BlueprintEntry((12, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 5), Entity.HARVESTER),
    BlueprintEntry((8, 7), Entity.HARVESTER),
)
