from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((18, 18), Entity.HARVESTER),
    BlueprintEntry((17, 22), Entity.HARVESTER),
    BlueprintEntry((17, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 13), Entity.ROAD),
    BlueprintEntry((13, 12), Entity.BRIDGE, bridge_target=(13, 15)),
    BlueprintEntry((13, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 8), Entity.HARVESTER),
    BlueprintEntry((13, 8), Entity.FOUNDRY),
    BlueprintEntry((14, 8), Entity.ROAD),
    BlueprintEntry((13, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 4), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 4), Entity.HARVESTER),
    BlueprintEntry((12, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 5), Entity.HARVESTER),
    BlueprintEntry((8, 7), Entity.HARVESTER),
    BlueprintEntry((14, 14), Entity.ROAD),
    BlueprintEntry((9, 21), Entity.BARRIER),
    BlueprintEntry((10, 21), Entity.BARRIER),
    BlueprintEntry((11, 21), Entity.BARRIER),
    BlueprintEntry((12, 21), Entity.BARRIER),
    BlueprintEntry((19, 14), Entity.BARRIER),
    BlueprintEntry((19, 15), Entity.BARRIER),
    BlueprintEntry((16, 12), Entity.BARRIER),
    BlueprintEntry((17, 12), Entity.BARRIER),
    BlueprintEntry((18, 12), Entity.BARRIER),
    BlueprintEntry((4, 18), Entity.BARRIER),
    BlueprintEntry((4, 19), Entity.BARRIER),
    BlueprintEntry((4, 20), Entity.BARRIER),
    BlueprintEntry((10, 19), Entity.ROAD),
    BlueprintEntry((9, 20), Entity.ROAD),
    BlueprintEntry((11, 20), Entity.ROAD),
    BlueprintEntry((6, 18), Entity.ROAD),
    BlueprintEntry((5, 19), Entity.ROAD),
    BlueprintEntry((16, 14), Entity.ROAD),
    BlueprintEntry((17, 13), Entity.ROAD),
    BlueprintEntry((18, 14), Entity.ROAD),
    BlueprintEntry((17, 15), Entity.ROAD),
    BlueprintEntry((14, 18), Entity.BRIDGE, bridge_target=(11, 18)),
    BlueprintEntry((11, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 17), Entity.ROAD),
    BlueprintEntry((12, 16), Entity.ROAD),
    BlueprintEntry((12, 18), Entity.ROAD),
    BlueprintEntry((7, 17), Entity.ROAD),
    BlueprintEntry((15, 14), Entity.ROAD),
    BlueprintEntry((17, 2), Entity.BARRIER),
    BlueprintEntry((17, 3), Entity.BARRIER),
    BlueprintEntry((17, 1), Entity.BARRIER),
    BlueprintEntry((17, 0), Entity.BARRIER),
    BlueprintEntry((16, 2), Entity.ROAD),
    BlueprintEntry((16, 1), Entity.ROAD),
    BlueprintEntry((15, 3), Entity.ROAD),
    BlueprintEntry((14, 4), Entity.ROAD),
)
