from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((4, 23), Entity.HARVESTER),
    BlueprintEntry((4, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 14), Entity.FOUNDRY),
    BlueprintEntry((3, 12), Entity.HARVESTER),
    BlueprintEntry((4, 11), Entity.HARVESTER),
    BlueprintEntry((4, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 13), Entity.HARVESTER),
    BlueprintEntry((3, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 12), Entity.HARVESTER),
    BlueprintEntry((2, 14), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 11), Entity.SENTINEL, direction=Direction.SOUTH),
    BlueprintEntry((3, 23), Entity.HARVESTER),
    BlueprintEntry((3, 22), Entity.CONVEYOR, direction=Direction.EAST),
)
