from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((3, 5), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 5), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 5), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 5), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 5), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 4), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 3), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 1), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 0), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 2), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 14), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 14), Entity.HARVESTER),
    BlueprintEntry((6, 15), Entity.HARVESTER),
    BlueprintEntry((6, 10), Entity.HARVESTER),
    BlueprintEntry((6, 11), Entity.HARVESTER),
    BlueprintEntry((3, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((13, 18), Entity.HARVESTER),
    BlueprintEntry((13, 19), Entity.HARVESTER),
    BlueprintEntry((14, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 19), Entity.HARVESTER),
    BlueprintEntry((6, 18), Entity.HARVESTER),
    BlueprintEntry((7, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 0), Entity.HARVESTER),
    BlueprintEntry((6, 1), Entity.HARVESTER),
    BlueprintEntry((6, 2), Entity.HARVESTER),
    BlueprintEntry((14, 11), Entity.BARRIER),
    BlueprintEntry((13, 11), Entity.BARRIER),
    BlueprintEntry((14, 12), Entity.ROAD),
    BlueprintEntry((14, 13), Entity.ROAD),
    BlueprintEntry((14, 14), Entity.ROAD),
    BlueprintEntry((13, 12), Entity.ROAD),
    BlueprintEntry((12, 12), Entity.ROAD),
    BlueprintEntry((10, 12), Entity.ROAD),
    BlueprintEntry((9, 12), Entity.ROAD),
    BlueprintEntry((11, 12), Entity.ROAD),
    BlueprintEntry((8, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 10), Entity.FOUNDRY),
    BlueprintEntry((8, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 14), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 16), Entity.BRIDGE, bridge_target=(7, 13)),
    BlueprintEntry((7, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 12), Entity.CONVEYOR, direction=Direction.NORTH),
)
