from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((33, 38), Entity.HARVESTER),
    BlueprintEntry((35, 38), Entity.HARVESTER),
    BlueprintEntry((34, 38), Entity.FOUNDRY),
    BlueprintEntry((33, 37), Entity.HARVESTER),
    BlueprintEntry((33, 36), Entity.HARVESTER),
    BlueprintEntry((34, 37), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((34, 36), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((34, 35), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((35, 35), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((36, 35), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((37, 35), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 7), Entity.BARRIER),
    BlueprintEntry((9, 8), Entity.BARRIER),
    BlueprintEntry((9, 9), Entity.BARRIER),
    BlueprintEntry((9, 10), Entity.BARRIER),
    BlueprintEntry((7, 5), Entity.ROAD),
    BlueprintEntry((6, 4), Entity.ROAD),
    BlueprintEntry((7, 3), Entity.ROAD),
    BlueprintEntry((8, 3), Entity.ROAD),
    BlueprintEntry((9, 3), Entity.ROAD),
    BlueprintEntry((10, 4), Entity.BARRIER),
    BlueprintEntry((10, 2), Entity.BARRIER),
    BlueprintEntry((8, 8), Entity.ROAD),
    BlueprintEntry((8, 9), Entity.ROAD),
)
