from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((15, 31), Entity.HARVESTER),
    BlueprintEntry((18, 32), Entity.HARVESTER),
    BlueprintEntry((8, 35), Entity.HARVESTER),
    BlueprintEntry((20, 36), Entity.BARRIER),
    BlueprintEntry((20, 37), Entity.BARRIER),
    BlueprintEntry((20, 38), Entity.BARRIER),
    BlueprintEntry((20, 39), Entity.BARRIER),
    BlueprintEntry((17, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 32), Entity.FOUNDRY),
    BlueprintEntry((16, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 33), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 35), Entity.BARRIER),
    BlueprintEntry((8, 36), Entity.BARRIER),
    BlueprintEntry((18, 31), Entity.BARRIER),
    BlueprintEntry((7, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 35), Entity.BARRIER),
    BlueprintEntry((5, 33), Entity.BARRIER),
    BlueprintEntry((6, 33), Entity.BARRIER),
    BlueprintEntry((7, 33), Entity.BARRIER),
    BlueprintEntry((8, 33), Entity.BARRIER),
    BlueprintEntry((9, 33), Entity.BARRIER),
    BlueprintEntry((10, 33), Entity.BARRIER),
    BlueprintEntry((11, 33), Entity.BARRIER),
    BlueprintEntry((5, 37), Entity.BARRIER),
    BlueprintEntry((5, 38), Entity.BARRIER),
    BlueprintEntry((5, 39), Entity.BARRIER),
    BlueprintEntry((18, 33), Entity.BARRIER),
    BlueprintEntry((19, 32), Entity.BARRIER),
    BlueprintEntry((18, 30), Entity.BARRIER),
    BlueprintEntry((18, 29), Entity.BARRIER),
    BlueprintEntry((19, 33), Entity.BARRIER),
    BlueprintEntry((19, 34), Entity.BARRIER),
    BlueprintEntry((19, 35), Entity.BARRIER),
    BlueprintEntry((19, 31), Entity.BARRIER),
    BlueprintEntry((11, 28), Entity.BARRIER),
    BlueprintEntry((11, 29), Entity.BARRIER),
    BlueprintEntry((11, 30), Entity.BARRIER),
    BlueprintEntry((11, 31), Entity.BARRIER),
    BlueprintEntry((11, 32), Entity.BARRIER),
    BlueprintEntry((13, 28), Entity.BARRIER),
)
