from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((6, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 31), Entity.HARVESTER),
    BlueprintEntry((15, 32), Entity.FOUNDRY),
    BlueprintEntry((6, 29), Entity.HARVESTER),
    BlueprintEntry((18, 32), Entity.HARVESTER),
    BlueprintEntry((5, 32), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 33), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 30), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 31), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 33), Entity.ROAD),
)
