from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((13, 16), Entity.HARVESTER),
    BlueprintEntry((6, 18), Entity.HARVESTER),
    BlueprintEntry((11, 10), Entity.HARVESTER),
    BlueprintEntry((11, 11), Entity.HARVESTER),
    BlueprintEntry((12, 12), Entity.HARVESTER),
    BlueprintEntry((12, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 6), Entity.HARVESTER),
    BlueprintEntry((12, 11), Entity.HARVESTER),
    BlueprintEntry((12, 7), Entity.FOUNDRY),
    BlueprintEntry((13, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 13), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 13), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 7), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 7), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((16, 5), Entity.HARVESTER),
    BlueprintEntry((16, 2), Entity.BARRIER),
    BlueprintEntry((16, 3), Entity.BARRIER),
    BlueprintEntry((16, 4), Entity.BARRIER),
    BlueprintEntry((16, 6), Entity.BARRIER),
    BlueprintEntry((16, 7), Entity.BARRIER),
    BlueprintEntry((16, 8), Entity.BARRIER),
    BlueprintEntry((15, 10), Entity.BARRIER),
    BlueprintEntry((15, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 3), Entity.ROAD),
    BlueprintEntry((14, 4), Entity.ROAD),
    BlueprintEntry((14, 10), Entity.ROAD),
    BlueprintEntry((12, 8), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((13, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 12), Entity.ROAD),
    BlueprintEntry((13, 6), Entity.ROAD),
    BlueprintEntry((13, 5), Entity.ROAD),
)
