from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((13, 16), Entity.HARVESTER),
    BlueprintEntry((6, 18), Entity.HARVESTER),
    BlueprintEntry((11, 10), Entity.HARVESTER),
    BlueprintEntry((11, 11), Entity.HARVESTER),
    BlueprintEntry((12, 12), Entity.HARVESTER),
    BlueprintEntry((12, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 6), Entity.HARVESTER),
    BlueprintEntry((12, 11), Entity.HARVESTER),
    BlueprintEntry((12, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 7), Entity.FOUNDRY),
    BlueprintEntry((13, 7), Entity.SPLITTER, direction=Direction.EAST),
    BlueprintEntry((14, 7), Entity.BREACH, direction=Direction.EAST),
    BlueprintEntry((13, 6), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((13, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 14), Entity.BRIDGE, bridge_target=(11, 16)),
    BlueprintEntry((12, 15), Entity.ROAD),
    BlueprintEntry((16, 5), Entity.HARVESTER),
    BlueprintEntry((15, 5), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 5), Entity.BRIDGE, bridge_target=(12, 7)),
    BlueprintEntry((14, 6), Entity.LAUNCHER),
)
