from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((4, 6), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 14), Entity.BRIDGE, bridge_target=(8, 11)),
    BlueprintEntry((8, 11), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((24, 15), Entity.ROAD),
    BlueprintEntry((23, 15), Entity.ROAD),
    BlueprintEntry((22, 15), Entity.ROAD),
    BlueprintEntry((20, 14), Entity.ROAD),
    BlueprintEntry((19, 14), Entity.ROAD),
    BlueprintEntry((18, 14), Entity.ROAD),
    BlueprintEntry((17, 14), Entity.ROAD),
    BlueprintEntry((16, 15), Entity.ROAD),
    BlueprintEntry((15, 17), Entity.ROAD),
    BlueprintEntry((15, 16), Entity.ROAD),
    BlueprintEntry((15, 18), Entity.ROAD),
    BlueprintEntry((5, 20), Entity.HARVESTER),
    BlueprintEntry((6, 19), Entity.HARVESTER),
    BlueprintEntry((7, 20), Entity.HARVESTER),
    BlueprintEntry((6, 21), Entity.HARVESTER),
    BlueprintEntry((5, 21), Entity.HARVESTER),
    BlueprintEntry((7, 21), Entity.HARVESTER),
    BlueprintEntry((8, 20), Entity.HARVESTER),
    BlueprintEntry((9, 20), Entity.HARVESTER),
    BlueprintEntry((7, 19), Entity.HARVESTER),
    BlueprintEntry((5, 19), Entity.HARVESTER),
    BlueprintEntry((4, 20), Entity.HARVESTER),
    BlueprintEntry((3, 20), Entity.HARVESTER),
    BlueprintEntry((8, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 21), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 21), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((24, 16), Entity.BARRIER),
    BlueprintEntry((25, 16), Entity.BARRIER),
    BlueprintEntry((6, 20), Entity.BRIDGE, bridge_target=(6, 17)),
    BlueprintEntry((6, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 14), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 14), Entity.BRIDGE, bridge_target=(3, 11)),
    BlueprintEntry((3, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 5), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 5), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 22), Entity.ROAD),
    BlueprintEntry((6, 22), Entity.ROAD),
    BlueprintEntry((5, 22), Entity.ROAD),
    BlueprintEntry((4, 21), Entity.BRIDGE, bridge_target=(3, 19)),
    BlueprintEntry((4, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 19), Entity.ROAD),
    BlueprintEntry((13, 19), Entity.ROAD),
    BlueprintEntry((12, 19), Entity.ROAD),
    BlueprintEntry((11, 19), Entity.ROAD),
    BlueprintEntry((21, 14), Entity.ROAD),
    BlueprintEntry((25, 15), Entity.ROAD),
    BlueprintEntry((26, 15), Entity.ROAD),
    BlueprintEntry((28, 14), Entity.ROAD),
    BlueprintEntry((29, 14), Entity.ROAD),
    BlueprintEntry((30, 14), Entity.ROAD),
    BlueprintEntry((31, 14), Entity.ROAD),
    BlueprintEntry((32, 14), Entity.ROAD),
    BlueprintEntry((33, 15), Entity.ROAD),
    BlueprintEntry((34, 16), Entity.ROAD),
    BlueprintEntry((34, 17), Entity.BARRIER),
    BlueprintEntry((22, 13), Entity.ROAD),
    BlueprintEntry((23, 12), Entity.ROAD),
    BlueprintEntry((24, 11), Entity.ROAD),
    BlueprintEntry((24, 10), Entity.ROAD),
    BlueprintEntry((24, 9), Entity.BARRIER),
    BlueprintEntry((25, 9), Entity.BARRIER),
    BlueprintEntry((7, 15), Entity.ROAD),
    BlueprintEntry((7, 17), Entity.ROAD),
    BlueprintEntry((4, 17), Entity.ROAD),
    BlueprintEntry((5, 17), Entity.ROAD),
    BlueprintEntry((25, 12), Entity.ROAD),
    BlueprintEntry((26, 13), Entity.ROAD),
    BlueprintEntry((27, 14), Entity.ROAD),
)
