from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((4, 6), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 14), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 20), Entity.HARVESTER),
    BlueprintEntry((4, 20), Entity.HARVESTER),
    BlueprintEntry((5, 19), Entity.HARVESTER),
    BlueprintEntry((6, 19), Entity.HARVESTER),
    BlueprintEntry((4, 5), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 5), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 15), Entity.BRIDGE, bridge_target=(3, 12)),
    BlueprintEntry((5, 17), Entity.BRIDGE, bridge_target=(3, 15)),
    BlueprintEntry((6, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 19), Entity.HARVESTER),
    BlueprintEntry((8, 20), Entity.HARVESTER),
    BlueprintEntry((9, 20), Entity.HARVESTER),
    BlueprintEntry((9, 19), Entity.CONVEYOR, direction=Direction.WEST),
)
