from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 22), Entity.HARVESTER),
    BlueprintEntry((14, 22), Entity.HARVESTER),
    BlueprintEntry((2, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 28), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 27), Entity.HARVESTER),
    BlueprintEntry((16, 28), Entity.HARVESTER),
    BlueprintEntry((15, 28), Entity.HARVESTER),
    BlueprintEntry((14, 28), Entity.HARVESTER),
    BlueprintEntry((13, 29), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 27), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 27), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 27), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 21), Entity.HARVESTER),
    BlueprintEntry((0, 18), Entity.BARRIER),
    BlueprintEntry((2, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((15, 17), Entity.HARVESTER),
    BlueprintEntry((16, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 16), Entity.HARVESTER),
    BlueprintEntry((15, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((17, 19), Entity.BARRIER),
    BlueprintEntry((17, 17), Entity.BARRIER),
    BlueprintEntry((16, 26), Entity.BARRIER),
    BlueprintEntry((17, 28), Entity.BARRIER),
    BlueprintEntry((17, 29), Entity.BARRIER),
    BlueprintEntry((17, 30), Entity.BARRIER),
    BlueprintEntry((14, 17), Entity.ROAD),
    BlueprintEntry((10, 19), Entity.ROAD),
    BlueprintEntry((10, 20), Entity.ROAD),
    BlueprintEntry((1, 19), Entity.ROAD),
    BlueprintEntry((1, 20), Entity.ROAD),
    BlueprintEntry((14, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 21), Entity.FOUNDRY),
    BlueprintEntry((15, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 21), Entity.BRIDGE, bridge_target=(15, 24)),
    BlueprintEntry((15, 22), Entity.ROAD),
    BlueprintEntry((14, 23), Entity.ROAD),
    BlueprintEntry((10, 18), Entity.BARRIER),
    BlueprintEntry((1, 18), Entity.BARRIER),
    BlueprintEntry((14, 16), Entity.BARRIER),
    BlueprintEntry((13, 16), Entity.BARRIER),
    BlueprintEntry((15, 16), Entity.BARRIER),
    BlueprintEntry((17, 16), Entity.BARRIER),
    BlueprintEntry((17, 18), Entity.BARRIER),
    BlueprintEntry((9, 18), Entity.BARRIER),
    BlueprintEntry((11, 18), Entity.BARRIER),
)
