from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((11, 27), Entity.HARVESTER),
    BlueprintEntry((4, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 27), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 27), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 27), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 27), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 27), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 27), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 26), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 25), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 26), Entity.FOUNDRY),
    BlueprintEntry((13, 25), Entity.HARVESTER),
    BlueprintEntry((15, 23), Entity.BARRIER),
    BlueprintEntry((14, 24), Entity.ROAD),
    BlueprintEntry((13, 24), Entity.ROAD),
    BlueprintEntry((8, 28), Entity.ROAD),
    BlueprintEntry((9, 29), Entity.ROAD),
    BlueprintEntry((10, 30), Entity.ROAD),
    BlueprintEntry((11, 31), Entity.ROAD),
    BlueprintEntry((12, 32), Entity.BARRIER),
    BlueprintEntry((14, 14), Entity.HARVESTER),
    BlueprintEntry((11, 16), Entity.HARVESTER),
    BlueprintEntry((11, 17), Entity.FOUNDRY),
    BlueprintEntry((10, 17), Entity.BRIDGE, bridge_target=(7, 17)),
    BlueprintEntry((7, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 16), Entity.ROAD),
    BlueprintEntry((8, 15), Entity.ROAD),
    BlueprintEntry((8, 14), Entity.ROAD),
    BlueprintEntry((8, 13), Entity.ROAD),
    BlueprintEntry((9, 12), Entity.ROAD),
    BlueprintEntry((10, 13), Entity.ROAD),
    BlueprintEntry((10, 14), Entity.ROAD),
    BlueprintEntry((10, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 15), Entity.ROAD),
    BlueprintEntry((12, 16), Entity.ROAD),
    BlueprintEntry((12, 39), Entity.BARRIER),
    BlueprintEntry((11, 38), Entity.ROAD),
    BlueprintEntry((11, 37), Entity.ROAD),
    BlueprintEntry((11, 36), Entity.ROAD),
    BlueprintEntry((11, 35), Entity.ROAD),
    BlueprintEntry((11, 34), Entity.ROAD),
    BlueprintEntry((11, 33), Entity.ROAD),
    BlueprintEntry((11, 32), Entity.ROAD),
    BlueprintEntry((9, 11), Entity.ROAD),
    BlueprintEntry((9, 10), Entity.ROAD),
    BlueprintEntry((9, 9), Entity.ROAD),
    BlueprintEntry((9, 8), Entity.BARRIER),
    BlueprintEntry((8, 8), Entity.ROAD),
    BlueprintEntry((8, 6), Entity.ROAD),
    BlueprintEntry((8, 7), Entity.ROAD),
    BlueprintEntry((8, 5), Entity.ROAD),
    BlueprintEntry((8, 4), Entity.ROAD),
    BlueprintEntry((8, 3), Entity.ROAD),
    BlueprintEntry((8, 2), Entity.ROAD),
    BlueprintEntry((8, 1), Entity.ROAD),
    BlueprintEntry((9, 1), Entity.BARRIER),
    BlueprintEntry((9, 0), Entity.BARRIER),
)
