from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((14, 14), Entity.HARVESTER),
    BlueprintEntry((11, 16), Entity.HARVESTER),
    BlueprintEntry((14, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 18), Entity.BARRIER),
    BlueprintEntry((6, 18), Entity.BARRIER),
    BlueprintEntry((7, 18), Entity.BARRIER),
    BlueprintEntry((8, 18), Entity.BARRIER),
    BlueprintEntry((1, 18), Entity.BARRIER),
    BlueprintEntry((0, 18), Entity.BARRIER),
    BlueprintEntry((10, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 14), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 12), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 12), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 12), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 12), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 12), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 12), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((13, 15), Entity.FOUNDRY),
    BlueprintEntry((13, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 14), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 14), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 20), Entity.ROAD),
    BlueprintEntry((6, 21), Entity.ROAD),
    BlueprintEntry((7, 22), Entity.ROAD),
    BlueprintEntry((8, 23), Entity.ROAD),
    BlueprintEntry((8, 24), Entity.ROAD),
    BlueprintEntry((8, 26), Entity.ROAD),
    BlueprintEntry((8, 25), Entity.ROAD),
    BlueprintEntry((9, 27), Entity.ROAD),
    BlueprintEntry((10, 27), Entity.ROAD),
    BlueprintEntry((11, 26), Entity.ROAD),
    BlueprintEntry((13, 25), Entity.BARRIER),
    BlueprintEntry((17, 25), Entity.BARRIER),
    BlueprintEntry((12, 25), Entity.ROAD),
    BlueprintEntry((13, 24), Entity.ROAD),
    BlueprintEntry((14, 24), Entity.ROAD),
    BlueprintEntry((15, 23), Entity.ROAD),
    BlueprintEntry((11, 27), Entity.BARRIER),
    BlueprintEntry((13, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 17), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((11, 15), Entity.LAUNCHER),
)
