from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((12, 41), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 41), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 41), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 40), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 40), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 40), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 39), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 39), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 39), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 39), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((15, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 38), Entity.HARVESTER),
    BlueprintEntry((12, 38), Entity.HARVESTER),
    BlueprintEntry((14, 38), Entity.HARVESTER),
    BlueprintEntry((15, 38), Entity.HARVESTER),
    BlueprintEntry((13, 38), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 37), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 36), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 36), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((14, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 35), Entity.HARVESTER),
    BlueprintEntry((11, 36), Entity.HARVESTER),
    BlueprintEntry((13, 35), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 34), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 34), Entity.HARVESTER),
    BlueprintEntry((14, 33), Entity.HARVESTER),
    BlueprintEntry((13, 33), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 32), Entity.SENTINEL, direction=Direction.NORTH),
    BlueprintEntry((12, 33), Entity.SENTINEL, direction=Direction.NORTH),
    BlueprintEntry((11, 35), Entity.SENTINEL, direction=Direction.NORTHWEST),
    BlueprintEntry((15, 34), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((12, 37), Entity.SENTINEL, direction=Direction.NORTHWEST),
    BlueprintEntry((14, 37), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((12, 35), Entity.LAUNCHER),
    BlueprintEntry((14, 34), Entity.LAUNCHER),
    BlueprintEntry((14, 36), Entity.LAUNCHER),
)
