from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((12, 41), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 41), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 41), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 40), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 40), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 40), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 39), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 39), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 39), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 39), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((15, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 38), Entity.HARVESTER),
    BlueprintEntry((12, 38), Entity.HARVESTER),
    BlueprintEntry((14, 38), Entity.HARVESTER),
    BlueprintEntry((15, 38), Entity.HARVESTER),
    BlueprintEntry((13, 38), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 37), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 36), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 36), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((14, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 35), Entity.HARVESTER),
    BlueprintEntry((11, 36), Entity.HARVESTER),
    BlueprintEntry((13, 35), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 34), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 34), Entity.HARVESTER),
    BlueprintEntry((13, 33), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 24), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 27), Entity.HARVESTER),
    BlueprintEntry((14, 26), Entity.HARVESTER),
    BlueprintEntry((14, 29), Entity.HARVESTER),
    BlueprintEntry((13, 29), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((13, 28), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((13, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((13, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 25), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 26), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 27), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 28), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 30), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 29), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 31), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((14, 23), Entity.HARVESTER),
    BlueprintEntry((13, 23), Entity.HARVESTER),
    BlueprintEntry((12, 23), Entity.HARVESTER),
    BlueprintEntry((13, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 25), Entity.FOUNDRY),
    BlueprintEntry((12, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((13, 32), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 30), Entity.ROAD),
    BlueprintEntry((13, 31), Entity.ROAD),
)
