from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((12, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 14), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((18, 13), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 13), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 13), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 13), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 13), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 13), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((19, 18), Entity.HARVESTER),
    BlueprintEntry((18, 19), Entity.HARVESTER),
    BlueprintEntry((0, 16), Entity.HARVESTER),
    BlueprintEntry((1, 15), Entity.HARVESTER),
    BlueprintEntry((1, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 13), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 13), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 13), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 7), Entity.HARVESTER),
    BlueprintEntry((7, 6), Entity.HARVESTER),
    BlueprintEntry((10, 10), Entity.BRIDGE, bridge_target=(10, 13)),
    BlueprintEntry((9, 10), Entity.HARVESTER),
    BlueprintEntry((10, 9), Entity.HARVESTER),
    BlueprintEntry((0, 15), Entity.ROAD),
    BlueprintEntry((1, 14), Entity.ROAD),
    BlueprintEntry((2, 13), Entity.ROAD),
    BlueprintEntry((3, 12), Entity.ROAD),
    BlueprintEntry((3, 11), Entity.ROAD),
    BlueprintEntry((3, 10), Entity.ROAD),
    BlueprintEntry((3, 9), Entity.ROAD),
    BlueprintEntry((3, 8), Entity.ROAD),
    BlueprintEntry((3, 7), Entity.ROAD),
    BlueprintEntry((3, 6), Entity.ROAD),
    BlueprintEntry((4, 5), Entity.ROAD),
    BlueprintEntry((5, 4), Entity.ROAD),
    BlueprintEntry((6, 3), Entity.ROAD),
    BlueprintEntry((7, 2), Entity.ROAD),
    BlueprintEntry((8, 1), Entity.ROAD),
    BlueprintEntry((9, 1), Entity.ROAD),
    BlueprintEntry((10, 1), Entity.ROAD),
    BlueprintEntry((11, 1), Entity.ROAD),
    BlueprintEntry((12, 2), Entity.ROAD),
    BlueprintEntry((11, 3), Entity.ROAD),
    BlueprintEntry((10, 4), Entity.ROAD),
    BlueprintEntry((10, 5), Entity.ROAD),
    BlueprintEntry((11, 6), Entity.ROAD),
    BlueprintEntry((12, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 9), Entity.ROAD),
    BlueprintEntry((12, 10), Entity.BRIDGE, bridge_target=(12, 13)),
    BlueprintEntry((19, 6), Entity.HARVESTER),
    BlueprintEntry((18, 7), Entity.HARVESTER),
    BlueprintEntry((18, 6), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 6), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 6), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 6), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 6), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 6), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((19, 7), Entity.ROAD),
    BlueprintEntry((20, 6), Entity.ROAD),
    BlueprintEntry((21, 12), Entity.BRIDGE, bridge_target=(19, 13)),
    BlueprintEntry((19, 13), Entity.FOUNDRY),
    BlueprintEntry((19, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((21, 13), Entity.HARVESTER),
    BlueprintEntry((22, 12), Entity.HARVESTER),
    BlueprintEntry((21, 5), Entity.ROAD),
    BlueprintEntry((22, 4), Entity.ROAD),
    BlueprintEntry((23, 4), Entity.ROAD),
    BlueprintEntry((24, 5), Entity.ROAD),
    BlueprintEntry((24, 6), Entity.ROAD),
    BlueprintEntry((24, 7), Entity.ROAD),
    BlueprintEntry((24, 8), Entity.ROAD),
    BlueprintEntry((23, 9), Entity.ROAD),
    BlueprintEntry((22, 10), Entity.ROAD),
    BlueprintEntry((21, 11), Entity.ROAD),
    BlueprintEntry((18, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((19, 14), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((21, 3), Entity.ROAD),
    BlueprintEntry((21, 2), Entity.BARRIER),
    BlueprintEntry((22, 2), Entity.BARRIER),
)
