from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 7), Entity.HARVESTER),
    BlueprintEntry((16, 6), Entity.HARVESTER),
    BlueprintEntry((15, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 4), Entity.HARVESTER),
    BlueprintEntry((17, 0), Entity.BARRIER),
    BlueprintEntry((17, 1), Entity.BARRIER),
    BlueprintEntry((17, 2), Entity.BARRIER),
    BlueprintEntry((17, 3), Entity.BARRIER),
    BlueprintEntry((17, 5), Entity.HARVESTER),
    BlueprintEntry((15, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((15, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((16, 5), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 5), Entity.FOUNDRY),
    BlueprintEntry((15, 4), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((13, 6), Entity.BARRIER),
    BlueprintEntry((14, 8), Entity.BARRIER),
    BlueprintEntry((14, 5), Entity.ROAD),
    BlueprintEntry((16, 1), Entity.ROAD),
    BlueprintEntry((15, 2), Entity.ROAD),
    BlueprintEntry((16, 3), Entity.ROAD),
    BlueprintEntry((18, 5), Entity.BARRIER),
    BlueprintEntry((17, 4), Entity.ROAD),
    BlueprintEntry((18, 4), Entity.BARRIER),
    BlueprintEntry((17, 6), Entity.BARRIER),
)
