from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((10, 35), Entity.HARVESTER),
    BlueprintEntry((10, 36), Entity.HARVESTER),
    BlueprintEntry((10, 37), Entity.HARVESTER),
    BlueprintEntry((10, 38), Entity.HARVESTER),
    BlueprintEntry((5, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 37), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 36), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 35), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 38), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 37), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 36), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 35), Entity.FOUNDRY),
    BlueprintEntry((12, 34), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 34), Entity.HARVESTER),
    BlueprintEntry((11, 35), Entity.HARVESTER),
    BlueprintEntry((15, 26), Entity.HARVESTER),
    BlueprintEntry((16, 26), Entity.HARVESTER),
    BlueprintEntry((16, 27), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 27), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 28), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 29), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 30), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 31), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 32), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 33), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((17, 27), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 26), Entity.HARVESTER),
    BlueprintEntry((15, 34), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 27), Entity.HARVESTER),
    BlueprintEntry((12, 32), Entity.HARVESTER),
    BlueprintEntry((11, 33), Entity.HARVESTER),
    BlueprintEntry((12, 33), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 26), Entity.ROAD),
    BlueprintEntry((19, 25), Entity.ROAD),
    BlueprintEntry((19, 24), Entity.BARRIER),
    BlueprintEntry((12, 31), Entity.BARRIER),
    BlueprintEntry((11, 31), Entity.BARRIER),
    BlueprintEntry((10, 31), Entity.BARRIER),
    BlueprintEntry((8, 31), Entity.BARRIER),
    BlueprintEntry((9, 31), Entity.BARRIER),
    BlueprintEntry((7, 31), Entity.BARRIER),
    BlueprintEntry((12, 26), Entity.BARRIER),
    BlueprintEntry((12, 27), Entity.BARRIER),
    BlueprintEntry((12, 28), Entity.BARRIER),
    BlueprintEntry((12, 29), Entity.BARRIER),
    BlueprintEntry((12, 30), Entity.BARRIER),
    BlueprintEntry((14, 27), Entity.ROAD),
    BlueprintEntry((13, 28), Entity.ROAD),
    BlueprintEntry((13, 26), Entity.ROAD),
    BlueprintEntry((14, 29), Entity.ROAD),
    BlueprintEntry((13, 30), Entity.ROAD),
    BlueprintEntry((14, 31), Entity.ROAD),
    BlueprintEntry((13, 32), Entity.ROAD),
    BlueprintEntry((7, 32), Entity.ROAD),
    BlueprintEntry((8, 33), Entity.ROAD),
    BlueprintEntry((9, 32), Entity.ROAD),
    BlueprintEntry((10, 33), Entity.ROAD),
    BlueprintEntry((11, 32), Entity.ROAD),
    BlueprintEntry((9, 34), Entity.ROAD),
)
