from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((10, 41), Entity.HARVESTER),
    BlueprintEntry((9, 41), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 41), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 41), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 41), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 42), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 43), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 44), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((1, 46), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 45), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 44), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 44), Entity.FOUNDRY),
    BlueprintEntry((3, 44), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 44), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 44), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((2, 37), Entity.HARVESTER),
    BlueprintEntry((2, 39), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 40), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 41), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 42), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 43), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 37), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((0, 37), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 38), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 39), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((1, 39), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 37), Entity.BARRIER),
    BlueprintEntry((11, 48), Entity.BARRIER),
    BlueprintEntry((11, 49), Entity.BARRIER),
    BlueprintEntry((2, 36), Entity.ROAD),
    BlueprintEntry((3, 37), Entity.ROAD),
    BlueprintEntry((4, 37), Entity.ROAD),
    BlueprintEntry((5, 37), Entity.ROAD),
    BlueprintEntry((6, 37), Entity.ROAD),
    BlueprintEntry((7, 37), Entity.ROAD),
    BlueprintEntry((7, 44), Entity.ROAD),
    BlueprintEntry((8, 45), Entity.ROAD),
    BlueprintEntry((9, 46), Entity.ROAD),
    BlueprintEntry((10, 47), Entity.ROAD),
    BlueprintEntry((10, 48), Entity.ROAD),
)
