from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((10, 41), Entity.HARVESTER),
    BlueprintEntry((9, 41), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 41), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 41), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 41), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 42), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 43), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 44), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((1, 46), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 45), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 44), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 44), Entity.FOUNDRY),
    BlueprintEntry((3, 44), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 44), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 44), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((2, 37), Entity.HARVESTER),
    BlueprintEntry((2, 39), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 40), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 41), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 42), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 43), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 37), Entity.BRIDGE, bridge_target=(2, 39)),
    BlueprintEntry((3, 40), Entity.ROAD),
    BlueprintEntry((4, 39), Entity.ROAD),
    BlueprintEntry((4, 38), Entity.ROAD),
)
