from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((3, 9), Entity.HARVESTER),
    BlueprintEntry((3, 1), Entity.HARVESTER),
    BlueprintEntry((2, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((1, 1), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 2), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 3), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 4), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 5), Entity.FOUNDRY),
    BlueprintEntry((1, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 9), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 11), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 14), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 19), Entity.HARVESTER),
    BlueprintEntry((1, 19), Entity.HARVESTER),
    BlueprintEntry((3, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 26), Entity.HARVESTER),
)
