from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((33, 8), Entity.HARVESTER),
    BlueprintEntry((34, 8), Entity.HARVESTER),
    BlueprintEntry((34, 9), Entity.HARVESTER),
    BlueprintEntry((35, 10), Entity.BRIDGE, bridge_target=(37, 12)),
    BlueprintEntry((37, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((38, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((39, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((34, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((35, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((35, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((33, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((33, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((39, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((39, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((39, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((39, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((39, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((39, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((39, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((39, 4), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((39, 3), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((39, 2), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((38, 2), Entity.HARVESTER),
)
