from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((33, 8), Entity.HARVESTER),
    BlueprintEntry((34, 8), Entity.HARVESTER),
    BlueprintEntry((34, 9), Entity.HARVESTER),
    BlueprintEntry((35, 10), Entity.BRIDGE, bridge_target=(37, 12)),
    BlueprintEntry((37, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((38, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((39, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((35, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((35, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((33, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((33, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((38, 2), Entity.HARVESTER),
    BlueprintEntry((32, 0), Entity.HARVESTER),
    BlueprintEntry((33, 0), Entity.BRIDGE, bridge_target=(35, 2)),
    BlueprintEntry((35, 2), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((35, 3), Entity.FOUNDRY),
    BlueprintEntry((23, 11), Entity.BARRIER),
    BlueprintEntry((23, 12), Entity.BARRIER),
    BlueprintEntry((22, 12), Entity.BARRIER),
    BlueprintEntry((21, 12), Entity.BARRIER),
    BlueprintEntry((33, 13), Entity.ROAD),
    BlueprintEntry((32, 14), Entity.ROAD),
    BlueprintEntry((31, 14), Entity.ROAD),
    BlueprintEntry((30, 14), Entity.ROAD),
    BlueprintEntry((29, 14), Entity.ROAD),
    BlueprintEntry((28, 14), Entity.ROAD),
    BlueprintEntry((27, 14), Entity.ROAD),
    BlueprintEntry((26, 14), Entity.ROAD),
    BlueprintEntry((25, 13), Entity.ROAD),
    BlueprintEntry((24, 12), Entity.ROAD),
    BlueprintEntry((24, 10), Entity.ROAD),
    BlueprintEntry((25, 9), Entity.ROAD),
    BlueprintEntry((26, 8), Entity.ROAD),
    BlueprintEntry((27, 7), Entity.ROAD),
    BlueprintEntry((28, 6), Entity.ROAD),
    BlueprintEntry((29, 5), Entity.ROAD),
    BlueprintEntry((30, 4), Entity.ROAD),
    BlueprintEntry((31, 3), Entity.ROAD),
    BlueprintEntry((32, 2), Entity.ROAD),
    BlueprintEntry((33, 1), Entity.ROAD),
    BlueprintEntry((35, 11), Entity.ROAD),
    BlueprintEntry((35, 5), Entity.BRIDGE, bridge_target=(35, 8)),
    BlueprintEntry((38, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((37, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((36, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((35, 4), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((32, 8), Entity.SENTINEL, direction=Direction.SOUTHEAST),
    BlueprintEntry((33, 7), Entity.BARRIER),
    BlueprintEntry((34, 7), Entity.BARRIER),
    BlueprintEntry((36, 8), Entity.ROAD),
    BlueprintEntry((39, 6), Entity.ROAD),
    BlueprintEntry((38, 5), Entity.ROAD),
    BlueprintEntry((37, 4), Entity.ROAD),
    BlueprintEntry((37, 9), Entity.ROAD),
    BlueprintEntry((39, 9), Entity.ROAD),
    BlueprintEntry((39, 8), Entity.ROAD),
    BlueprintEntry((39, 7), Entity.ROAD),
    BlueprintEntry((34, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((34, 12), Entity.ROAD),
    BlueprintEntry((34, 11), Entity.LAUNCHER),
)
