from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((3, 17), Entity.HARVESTER),
    BlueprintEntry((4, 16), Entity.HARVESTER),
    BlueprintEntry((4, 15), Entity.HARVESTER),
    BlueprintEntry((5, 19), Entity.HARVESTER),
    BlueprintEntry((7, 21), Entity.HARVESTER),
    BlueprintEntry((11, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 19), Entity.BRIDGE, bridge_target=(9, 18)),
    BlueprintEntry((8, 19), Entity.ROAD),
    BlueprintEntry((7, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 21), Entity.HARVESTER),
    BlueprintEntry((5, 21), Entity.HARVESTER),
    BlueprintEntry((3, 14), Entity.HARVESTER),
    BlueprintEntry((4, 14), Entity.ROAD),
    BlueprintEntry((5, 15), Entity.BRIDGE, bridge_target=(8, 15)),
    BlueprintEntry((5, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 16), Entity.BRIDGE, bridge_target=(10, 16)),
    BlueprintEntry((8, 15), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 16), Entity.ROAD),
    BlueprintEntry((10, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 15), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 15), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 15), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 15), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 15), Entity.BRIDGE, bridge_target=(5, 15)),
    BlueprintEntry((2, 14), Entity.HARVESTER),
    BlueprintEntry((1, 15), Entity.HARVESTER),
    BlueprintEntry((1, 16), Entity.HARVESTER),
    BlueprintEntry((2, 17), Entity.HARVESTER),
    BlueprintEntry((2, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 16), Entity.BRIDGE, bridge_target=(5, 16)),
    BlueprintEntry((12, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 22), Entity.BRIDGE, bridge_target=(10, 19)),
    BlueprintEntry((8, 21), Entity.ROAD),
    BlueprintEntry((9, 22), Entity.ROAD),
    BlueprintEntry((10, 23), Entity.FOUNDRY),
    BlueprintEntry((10, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 23), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 23), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 23), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 23), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 25), Entity.HARVESTER),
    BlueprintEntry((5, 23), Entity.HARVESTER),
    BlueprintEntry((11, 23), Entity.BREACH, direction=Direction.EAST),
    BlueprintEntry((6, 21), Entity.SENTINEL, direction=Direction.SOUTHEAST),
    BlueprintEntry((4, 21), Entity.SENTINEL, direction=Direction.SOUTH),
    BlueprintEntry((4, 17), Entity.SENTINEL, direction=Direction.NORTHWEST),
)
