from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((7, 12), Entity.HARVESTER),
    BlueprintEntry((6, 5), Entity.HARVESTER),
    BlueprintEntry((7, 5), Entity.HARVESTER),
    BlueprintEntry((7, 6), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 6), Entity.HARVESTER),
    BlueprintEntry((5, 6), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 7), Entity.HARVESTER),
    BlueprintEntry((5, 12), Entity.HARVESTER),
    BlueprintEntry((6, 13), Entity.HARVESTER),
    BlueprintEntry((6, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 7), Entity.FOUNDRY),
    BlueprintEntry((9, 12), Entity.HARVESTER),
    BlueprintEntry((8, 13), Entity.HARVESTER),
    BlueprintEntry((8, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 12), Entity.HARVESTER),
    BlueprintEntry((10, 13), Entity.HARVESTER),
    BlueprintEntry((10, 9), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 16), Entity.FOUNDRY),
    BlueprintEntry((8, 16), Entity.HARVESTER),
    BlueprintEntry((9, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 17), Entity.HARVESTER),
    BlueprintEntry((11, 17), Entity.HARVESTER),
    BlueprintEntry((12, 16), Entity.HARVESTER),
    BlueprintEntry((1, 16), Entity.HARVESTER),
    BlueprintEntry((2, 17), Entity.HARVESTER),
    BlueprintEntry((4, 17), Entity.HARVESTER),
    BlueprintEntry((5, 16), Entity.HARVESTER),
    BlueprintEntry((15, 16), Entity.HARVESTER),
    BlueprintEntry((18, 17), Entity.HARVESTER),
    BlueprintEntry((19, 16), Entity.HARVESTER),
    BlueprintEntry((16, 17), Entity.HARVESTER),
    BlueprintEntry((3, 16), Entity.FOUNDRY),
    BlueprintEntry((17, 16), Entity.FOUNDRY),
    BlueprintEntry((2, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((18, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((2, 5), Entity.HARVESTER),
    BlueprintEntry((3, 5), Entity.HARVESTER),
    BlueprintEntry((3, 6), Entity.HARVESTER),
    BlueprintEntry((4, 7), Entity.HARVESTER),
    BlueprintEntry((4, 3), Entity.HARVESTER),
    BlueprintEntry((3, 3), Entity.HARVESTER),
    BlueprintEntry((5, 4), Entity.HARVESTER),
    BlueprintEntry((4, 4), Entity.HARVESTER),
    BlueprintEntry((2, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 7), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 7), Entity.BRIDGE, bridge_target=(5, 8)),
    BlueprintEntry((3, 8), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 8), Entity.FOUNDRY),
    BlueprintEntry((5, 8), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((1, 12), Entity.HARVESTER),
    BlueprintEntry((2, 13), Entity.HARVESTER),
    BlueprintEntry((3, 12), Entity.HARVESTER),
    BlueprintEntry((4, 13), Entity.HARVESTER),
    BlueprintEntry((1, 20), Entity.HARVESTER),
    BlueprintEntry((2, 21), Entity.HARVESTER),
    BlueprintEntry((3, 20), Entity.HARVESTER),
    BlueprintEntry((4, 21), Entity.HARVESTER),
    BlueprintEntry((3, 19), Entity.BRIDGE, bridge_target=(3, 16)),
    BlueprintEntry((2, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 20), Entity.HARVESTER),
    BlueprintEntry((10, 21), Entity.HARVESTER),
    BlueprintEntry((11, 20), Entity.HARVESTER),
    BlueprintEntry((17, 20), Entity.HARVESTER),
    BlueprintEntry((18, 21), Entity.HARVESTER),
    BlueprintEntry((19, 20), Entity.HARVESTER),
    BlueprintEntry((19, 12), Entity.HARVESTER),
    BlueprintEntry((18, 13), Entity.HARVESTER),
    BlueprintEntry((17, 12), Entity.HARVESTER),
    BlueprintEntry((16, 13), Entity.HARVESTER),
    BlueprintEntry((15, 12), Entity.HARVESTER),
    BlueprintEntry((14, 13), Entity.HARVESTER),
    BlueprintEntry((13, 12), Entity.HARVESTER),
    BlueprintEntry((12, 13), Entity.HARVESTER),
    BlueprintEntry((15, 20), Entity.HARVESTER),
    BlueprintEntry((16, 21), Entity.HARVESTER),
    BlueprintEntry((14, 21), Entity.HARVESTER),
    BlueprintEntry((13, 20), Entity.HARVESTER),
    BlueprintEntry((12, 21), Entity.HARVESTER),
    BlueprintEntry((8, 21), Entity.HARVESTER),
    BlueprintEntry((7, 20), Entity.HARVESTER),
    BlueprintEntry((6, 21), Entity.HARVESTER),
    BlueprintEntry((5, 20), Entity.HARVESTER),
    BlueprintEntry((3, 15), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((10, 15), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((17, 15), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((17, 19), Entity.BRIDGE, bridge_target=(17, 16)),
    BlueprintEntry((18, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 14), Entity.BRIDGE, bridge_target=(10, 16)),
    BlueprintEntry((10, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 19), Entity.BRIDGE, bridge_target=(10, 16)),
    BlueprintEntry((7, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 9), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 9), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 11), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((14, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 11), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((7, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 11), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((9, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 10), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 10), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((13, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((13, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((13, 9), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((16, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((16, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((15, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((15, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((15, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((15, 8), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((16, 10), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((16, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((16, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 10), Entity.BRIDGE, bridge_target=(5, 8)),
    BlueprintEntry((2, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 10), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((7, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((2, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((1, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((0, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((0, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((0, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((0, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((0, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((13, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((14, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((15, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((16, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((17, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((19, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((20, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((20, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 14), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((0, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((0, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((0, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((0, 14), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((0, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((0, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((0, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((0, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((0, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((0, 8), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((20, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((19, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 8), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 8), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 9), Entity.BRIDGE, bridge_target=(7, 9)),
    BlueprintEntry((4, 5), Entity.BRIDGE, bridge_target=(3, 4)),
    BlueprintEntry((3, 4), Entity.BRIDGE, bridge_target=(3, 1)),
    BlueprintEntry((3, 1), Entity.FOUNDRY),
    BlueprintEntry((18, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 4), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 3), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 2), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 1), Entity.BRIDGE, bridge_target=(3, 1)),
    BlueprintEntry((5, 3), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 3), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 4), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 4), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 4), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 4), Entity.FOUNDRY),
    BlueprintEntry((10, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 9), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((17, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((16, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((16, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((16, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 1), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 2), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 2), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 2), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 2), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 3), Entity.BRIDGE, bridge_target=(8, 6)),
    BlueprintEntry((8, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 15), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((16, 15), Entity.SENTINEL, direction=Direction.WEST),
    BlueprintEntry((2, 15), Entity.SENTINEL, direction=Direction.WEST),
    BlueprintEntry((4, 15), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((3, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 10), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((1, 13), Entity.ROAD),
    BlueprintEntry((1, 14), Entity.ROAD),
    BlueprintEntry((2, 14), Entity.ROAD),
    BlueprintEntry((3, 14), Entity.ROAD),
    BlueprintEntry((3, 13), Entity.ROAD),
    BlueprintEntry((4, 14), Entity.ROAD),
    BlueprintEntry((5, 14), Entity.ROAD),
    BlueprintEntry((5, 13), Entity.ROAD),
    BlueprintEntry((6, 14), Entity.ROAD),
    BlueprintEntry((7, 14), Entity.ROAD),
    BlueprintEntry((7, 13), Entity.ROAD),
    BlueprintEntry((8, 14), Entity.ROAD),
    BlueprintEntry((9, 14), Entity.ROAD),
    BlueprintEntry((9, 13), Entity.ROAD),
    BlueprintEntry((11, 13), Entity.ROAD),
    BlueprintEntry((11, 14), Entity.ROAD),
    BlueprintEntry((12, 14), Entity.ROAD),
    BlueprintEntry((13, 14), Entity.ROAD),
    BlueprintEntry((13, 13), Entity.ROAD),
    BlueprintEntry((14, 14), Entity.ROAD),
    BlueprintEntry((15, 14), Entity.ROAD),
    BlueprintEntry((17, 14), Entity.ROAD),
    BlueprintEntry((17, 13), Entity.ROAD),
    BlueprintEntry((16, 14), Entity.ROAD),
    BlueprintEntry((18, 14), Entity.ROAD),
    BlueprintEntry((15, 13), Entity.ROAD),
    BlueprintEntry((19, 13), Entity.ROAD),
    BlueprintEntry((19, 14), Entity.ROAD),
    BlueprintEntry((8, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 22), Entity.SPLITTER, direction=Direction.SOUTH),
    BlueprintEntry((8, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 19), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((13, 19), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((5, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((16, 19), Entity.CONVEYOR, direction=Direction.EAST),
)
