from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((10, 16), Entity.FOUNDRY),
    BlueprintEntry((8, 16), Entity.HARVESTER),
    BlueprintEntry((9, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 17), Entity.HARVESTER),
    BlueprintEntry((11, 17), Entity.HARVESTER),
    BlueprintEntry((12, 16), Entity.HARVESTER),
    BlueprintEntry((1, 16), Entity.HARVESTER),
    BlueprintEntry((2, 17), Entity.HARVESTER),
    BlueprintEntry((4, 17), Entity.HARVESTER),
    BlueprintEntry((5, 16), Entity.HARVESTER),
    BlueprintEntry((15, 16), Entity.HARVESTER),
    BlueprintEntry((18, 17), Entity.HARVESTER),
    BlueprintEntry((19, 16), Entity.HARVESTER),
    BlueprintEntry((16, 17), Entity.HARVESTER),
    BlueprintEntry((3, 16), Entity.FOUNDRY),
    BlueprintEntry((17, 16), Entity.FOUNDRY),
    BlueprintEntry((2, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((18, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 20), Entity.HARVESTER),
    BlueprintEntry((4, 21), Entity.HARVESTER),
    BlueprintEntry((3, 19), Entity.BRIDGE, bridge_target=(3, 16)),
    BlueprintEntry((9, 20), Entity.HARVESTER),
    BlueprintEntry((11, 20), Entity.HARVESTER),
    BlueprintEntry((17, 20), Entity.HARVESTER),
    BlueprintEntry((18, 21), Entity.HARVESTER),
    BlueprintEntry((19, 20), Entity.HARVESTER),
    BlueprintEntry((15, 20), Entity.HARVESTER),
    BlueprintEntry((13, 20), Entity.HARVESTER),
    BlueprintEntry((12, 21), Entity.HARVESTER),
    BlueprintEntry((7, 20), Entity.HARVESTER),
    BlueprintEntry((5, 20), Entity.HARVESTER),
    BlueprintEntry((17, 19), Entity.BRIDGE, bridge_target=(17, 16)),
    BlueprintEntry((18, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 19), Entity.BRIDGE, bridge_target=(10, 16)),
    BlueprintEntry((4, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((15, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((18, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 14), Entity.BRIDGE, bridge_target=(17, 11)),
    BlueprintEntry((7, 12), Entity.HARVESTER),
    BlueprintEntry((9, 12), Entity.HARVESTER),
    BlueprintEntry((8, 13), Entity.HARVESTER),
    BlueprintEntry((8, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 12), Entity.HARVESTER),
    BlueprintEntry((10, 14), Entity.BRIDGE, bridge_target=(10, 11)),
    BlueprintEntry((10, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 9), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 12), Entity.HARVESTER),
    BlueprintEntry((3, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 23), Entity.BARRIER),
    BlueprintEntry((6, 23), Entity.BARRIER),
    BlueprintEntry((5, 23), Entity.BARRIER),
    BlueprintEntry((5, 24), Entity.BARRIER),
    BlueprintEntry((5, 25), Entity.BARRIER),
    BlueprintEntry((5, 26), Entity.BARRIER),
    BlueprintEntry((6, 26), Entity.BARRIER),
    BlueprintEntry((7, 26), Entity.BARRIER),
    BlueprintEntry((7, 25), Entity.BARRIER),
    BlueprintEntry((3, 23), Entity.BARRIER),
    BlueprintEntry((2, 23), Entity.BARRIER),
    BlueprintEntry((1, 23), Entity.BARRIER),
    BlueprintEntry((1, 24), Entity.BARRIER),
    BlueprintEntry((1, 25), Entity.BARRIER),
    BlueprintEntry((1, 26), Entity.BARRIER),
    BlueprintEntry((2, 26), Entity.BARRIER),
    BlueprintEntry((3, 26), Entity.BARRIER),
    BlueprintEntry((3, 25), Entity.BARRIER),
    BlueprintEntry((6, 9), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 14), Entity.BRIDGE, bridge_target=(6, 14)),
    BlueprintEntry((6, 14), Entity.BRIDGE, bridge_target=(6, 11)),
    BlueprintEntry((6, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 13), Entity.HARVESTER),
    BlueprintEntry((14, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((1, 12), Entity.HARVESTER),
    BlueprintEntry((2, 13), Entity.HARVESTER),
    BlueprintEntry((2, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 8), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 8), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 8), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 8), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 8), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((15, 12), Entity.HARVESTER),
)
