from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((3, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 16), Entity.HARVESTER),
    BlueprintEntry((2, 17), Entity.HARVESTER),
    BlueprintEntry((3, 18), Entity.HARVESTER),
    BlueprintEntry((11, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 7), Entity.BRIDGE, bridge_target=(7, 9)),
    BlueprintEntry((6, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 5), Entity.HARVESTER),
    BlueprintEntry((4, 6), Entity.HARVESTER),
    BlueprintEntry((4, 7), Entity.HARVESTER),
    BlueprintEntry((7, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 10), Entity.HARVESTER),
    BlueprintEntry((8, 11), Entity.HARVESTER),
    BlueprintEntry((12, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 24), Entity.HARVESTER),
    BlueprintEntry((2, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 28), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 29), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 30), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 31), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 32), Entity.HARVESTER),
    BlueprintEntry((3, 33), Entity.HARVESTER),
    BlueprintEntry((1, 31), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((1, 32), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 33), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 34), Entity.ROAD),
    BlueprintEntry((4, 33), Entity.ROAD),
    BlueprintEntry((5, 32), Entity.ROAD),
    BlueprintEntry((6, 31), Entity.ROAD),
    BlueprintEntry((7, 30), Entity.ROAD),
    BlueprintEntry((7, 29), Entity.ROAD),
    BlueprintEntry((7, 28), Entity.ROAD),
    BlueprintEntry((8, 27), Entity.ROAD),
    BlueprintEntry((7, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 26), Entity.FOUNDRY),
    BlueprintEntry((3, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 26), Entity.HARVESTER),
    BlueprintEntry((7, 27), Entity.HARVESTER),
    BlueprintEntry((4, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 24), Entity.BRIDGE, bridge_target=(4, 22)),
    BlueprintEntry((7, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 24), Entity.ROAD),
    BlueprintEntry((11, 25), Entity.FOUNDRY),
    BlueprintEntry((10, 25), Entity.HARVESTER),
    BlueprintEntry((11, 26), Entity.HARVESTER),
    BlueprintEntry((8, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 24), Entity.ROAD),
    BlueprintEntry((11, 24), Entity.BRIDGE, bridge_target=(8, 24)),
    BlueprintEntry((8, 26), Entity.ROAD),
    BlueprintEntry((12, 25), Entity.BREACH, direction=Direction.EAST),
    BlueprintEntry((13, 24), Entity.BARRIER),
    BlueprintEntry((13, 25), Entity.BARRIER),
    BlueprintEntry((13, 26), Entity.BARRIER),
    BlueprintEntry((13, 27), Entity.BARRIER),
    BlueprintEntry((12, 26), Entity.ROAD),
)
