from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((14, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 37), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((34, 45), Entity.HARVESTER),
    BlueprintEntry((35, 45), Entity.HARVESTER),
    BlueprintEntry((36, 44), Entity.HARVESTER),
    BlueprintEntry((35, 44), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((34, 44), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((33, 44), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((32, 43), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((31, 43), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((30, 43), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((29, 43), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 42), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 41), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 40), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((28, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((27, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((26, 39), Entity.FOUNDRY),
    BlueprintEntry((25, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((24, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((23, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((21, 39), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((22, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((24, 42), Entity.HARVESTER),
    BlueprintEntry((25, 42), Entity.HARVESTER),
    BlueprintEntry((27, 41), Entity.HARVESTER),
    BlueprintEntry((24, 41), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((25, 41), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((26, 41), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((26, 40), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((33, 43), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((22, 37), Entity.HARVESTER),
    BlueprintEntry((21, 37), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((21, 38), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 37), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((19, 37), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 43), Entity.HARVESTER),
    BlueprintEntry((8, 43), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 42), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 41), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 40), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 39), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 38), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 37), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 36), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 35), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 34), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((16, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 35), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 36), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 34), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 33), Entity.CONVEYOR, direction=Direction.WEST),
)
