from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((9, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 34), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((15, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 36), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 37), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((19, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((20, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((21, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((31, 44), Entity.HARVESTER),
    BlueprintEntry((34, 45), Entity.HARVESTER),
    BlueprintEntry((35, 45), Entity.HARVESTER),
    BlueprintEntry((36, 44), Entity.HARVESTER),
    BlueprintEntry((35, 44), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((34, 44), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((33, 44), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((32, 44), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((32, 43), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((31, 43), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((30, 43), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((29, 43), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 42), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 41), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 40), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((29, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((28, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((27, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((26, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((25, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((24, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((23, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 35), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((16, 36), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 37), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 38), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((21, 39), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((22, 39), Entity.CONVEYOR, direction=Direction.WEST),
)
