from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 24), Entity.HARVESTER),
    BlueprintEntry((13, 22), Entity.HARVESTER),
    BlueprintEntry((4, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 19), Entity.HARVESTER),
    BlueprintEntry((11, 20), Entity.HARVESTER),
    BlueprintEntry((12, 21), Entity.HARVESTER),
    BlueprintEntry((10, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
)
