from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 7), Entity.HARVESTER),
    BlueprintEntry((10, 1), Entity.HARVESTER),
    BlueprintEntry((1, 15), Entity.HARVESTER),
    BlueprintEntry((1, 14), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 4), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 7), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 14), Entity.HARVESTER),
    BlueprintEntry((5, 15), Entity.HARVESTER),
    BlueprintEntry((7, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 14), Entity.BRIDGE, bridge_target=(3, 13)),
    BlueprintEntry((2, 13), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 13), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 13), Entity.ROAD),
    BlueprintEntry((6, 14), Entity.ROAD),
    BlueprintEntry((6, 15), Entity.FOUNDRY),
    BlueprintEntry((8, 16), Entity.BARRIER),
    BlueprintEntry((10, 2), Entity.ROAD),
    BlueprintEntry((11, 3), Entity.BARRIER),
    BlueprintEntry((10, 13), Entity.BARRIER),
    BlueprintEntry((9, 11), Entity.HARVESTER),
    BlueprintEntry((7, 12), Entity.HARVESTER),
    BlueprintEntry((8, 12), Entity.FOUNDRY),
    BlueprintEntry((9, 12), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 11), Entity.ROAD),
    BlueprintEntry((7, 11), Entity.BRIDGE, bridge_target=(5, 10)),
    BlueprintEntry((5, 10), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 10), Entity.ROAD),
    BlueprintEntry((2, 15), Entity.ROAD),
    BlueprintEntry((2, 16), Entity.ROAD),
    BlueprintEntry((1, 17), Entity.ROAD),
    BlueprintEntry((1, 18), Entity.ROAD),
    BlueprintEntry((2, 19), Entity.BARRIER),
    BlueprintEntry((11, 1), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((3, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 4), Entity.CONVEYOR, direction=Direction.NORTH),
)
