from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((9, 18), Entity.HARVESTER),
    BlueprintEntry((9, 19), Entity.HARVESTER),
    BlueprintEntry((9, 20), Entity.HARVESTER),
    BlueprintEntry((8, 16), Entity.HARVESTER),
    BlueprintEntry((8, 18), Entity.FOUNDRY),
    BlueprintEntry((8, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 17), Entity.HARVESTER),
    BlueprintEntry((4, 19), Entity.HARVESTER),
    BlueprintEntry((3, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 16), Entity.BRIDGE, bridge_target=(8, 18)),
    BlueprintEntry((11, 16), Entity.SPLITTER, direction=Direction.SOUTH),
    BlueprintEntry((11, 15), Entity.SPLITTER, direction=Direction.SOUTH),
    BlueprintEntry((11, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 14), Entity.HARVESTER),
    BlueprintEntry((10, 15), Entity.HARVESTER),
    BlueprintEntry((12, 15), Entity.GUNNER, direction=Direction.NORTHEAST),
    BlueprintEntry((12, 16), Entity.GUNNER, direction=Direction.SOUTH),
)
