from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((2, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 11), Entity.HARVESTER),
    BlueprintEntry((5, 11), Entity.HARVESTER),
    BlueprintEntry((0, 12), Entity.HARVESTER),
    BlueprintEntry((6, 12), Entity.HARVESTER),
    BlueprintEntry((2, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 11), Entity.HARVESTER),
    BlueprintEntry((4, 11), Entity.HARVESTER),
    BlueprintEntry((2, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 11), Entity.HARVESTER),
    BlueprintEntry((2, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 12), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((1, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((15, 14), Entity.HARVESTER),
    BlueprintEntry((17, 19), Entity.HARVESTER),
    BlueprintEntry((0, 11), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((13, 14), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 14), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 14), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 14), Entity.FOUNDRY),
    BlueprintEntry((7, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 11), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 12), Entity.SENTINEL, direction=Direction.NORTH),
    BlueprintEntry((12, 16), Entity.BARRIER),
    BlueprintEntry((12, 17), Entity.BARRIER),
    BlueprintEntry((16, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 19), Entity.BRIDGE, bridge_target=(11, 16)),
    BlueprintEntry((11, 16), Entity.BRIDGE, bridge_target=(11, 14)),
    BlueprintEntry((10, 14), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 14), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 14), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 14), Entity.BRIDGE, bridge_target=(4, 14)),
    BlueprintEntry((10, 19), Entity.ROAD),
    BlueprintEntry((9, 19), Entity.ROAD),
    BlueprintEntry((8, 19), Entity.ROAD),
    BlueprintEntry((7, 18), Entity.ROAD),
)
