from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((1, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 9), Entity.ROAD),
    BlueprintEntry((0, 7), Entity.HARVESTER),
    BlueprintEntry((1, 10), Entity.HARVESTER),
    BlueprintEntry((0, 14), Entity.HARVESTER),
    BlueprintEntry((1, 8), Entity.BRIDGE, bridge_target=(1, 11)),
    BlueprintEntry((1, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 4), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 4), Entity.FOUNDRY),
    BlueprintEntry((3, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((2, 3), Entity.HARVESTER),
    BlueprintEntry((1, 3), Entity.ROAD),
    BlueprintEntry((2, 2), Entity.ROAD),
    BlueprintEntry((3, 3), Entity.ROAD),
    BlueprintEntry((4, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 3), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 2), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 2), Entity.ROAD),
    BlueprintEntry((5, 1), Entity.HARVESTER),
    BlueprintEntry((5, 5), Entity.ROAD),
    BlueprintEntry((0, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 10), Entity.ROAD),
    BlueprintEntry((1, 9), Entity.BRIDGE, bridge_target=(0, 11)),
    BlueprintEntry((4, 9), Entity.BRIDGE, bridge_target=(1, 9)),
    BlueprintEntry((0, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 12), Entity.BRIDGE, bridge_target=(0, 15)),
    BlueprintEntry((6, 10), Entity.HARVESTER),
    BlueprintEntry((5, 11), Entity.HARVESTER),
    BlueprintEntry((5, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 9), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 6), Entity.HARVESTER),
    BlueprintEntry((6, 6), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 11), Entity.ROAD),
    BlueprintEntry((7, 12), Entity.ROAD),
    BlueprintEntry((8, 14), Entity.HARVESTER),
    BlueprintEntry((9, 14), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((9, 17), Entity.FOUNDRY),
    BlueprintEntry((10, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 16), Entity.HARVESTER),
    BlueprintEntry((9, 18), Entity.HARVESTER),
    BlueprintEntry((9, 16), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((6, 12), Entity.LAUNCHER),
    BlueprintEntry((8, 13), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((8, 17), Entity.SENTINEL, direction=Direction.NORTH),
    BlueprintEntry((8, 15), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((7, 14), Entity.SENTINEL, direction=Direction.NORTHEAST),
)
