from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((1, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 7), Entity.HARVESTER),
    BlueprintEntry((1, 10), Entity.HARVESTER),
    BlueprintEntry((0, 14), Entity.HARVESTER),
    BlueprintEntry((1, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 4), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 4), Entity.FOUNDRY),
    BlueprintEntry((3, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((2, 3), Entity.HARVESTER),
    BlueprintEntry((4, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 3), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 2), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 1), Entity.HARVESTER),
    BlueprintEntry((1, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((1, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 5), Entity.BARRIER),
    BlueprintEntry((4, 5), Entity.BARRIER),
    BlueprintEntry((5, 5), Entity.BARRIER),
    BlueprintEntry((6, 5), Entity.BARRIER),
    BlueprintEntry((7, 5), Entity.BARRIER),
    BlueprintEntry((4, 1), Entity.BARRIER),
    BlueprintEntry((5, 0), Entity.BARRIER),
    BlueprintEntry((6, 1), Entity.BARRIER),
    BlueprintEntry((0, 11), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((0, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 13), Entity.BARRIER),
    BlueprintEntry((1, 9), Entity.BARRIER),
    BlueprintEntry((0, 6), Entity.BARRIER),
    BlueprintEntry((0, 15), Entity.BARRIER),
)
