from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((18, 34), Entity.HARVESTER),
    BlueprintEntry((19, 34), Entity.HARVESTER),
    BlueprintEntry((20, 34), Entity.HARVESTER),
    BlueprintEntry((21, 34), Entity.HARVESTER),
    BlueprintEntry((19, 26), Entity.SPLITTER, direction=Direction.NORTH),
    BlueprintEntry((19, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((19, 28), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((19, 29), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((19, 31), Entity.FOUNDRY),
    BlueprintEntry((19, 30), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((19, 32), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((19, 33), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 33), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((20, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((21, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 31), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((15, 31), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((16, 31), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((17, 31), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((18, 31), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((13, 30), Entity.HARVESTER),
    BlueprintEntry((13, 31), Entity.HARVESTER),
    BlueprintEntry((13, 32), Entity.HARVESTER),
    BlueprintEntry((13, 33), Entity.HARVESTER),
    BlueprintEntry((14, 33), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 32), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 30), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 32), Entity.ROAD),
    BlueprintEntry((20, 31), Entity.ROAD),
    BlueprintEntry((20, 32), Entity.ROAD),
    BlueprintEntry((20, 26), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((18, 26), Entity.BREACH, direction=Direction.NORTHWEST),
)
