from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((18, 34), Entity.HARVESTER),
    BlueprintEntry((19, 34), Entity.HARVESTER),
    BlueprintEntry((20, 34), Entity.HARVESTER),
    BlueprintEntry((21, 34), Entity.HARVESTER),
    BlueprintEntry((13, 32), Entity.HARVESTER),
    BlueprintEntry((14, 32), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 33), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 33), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((17, 34), Entity.FOUNDRY),
    BlueprintEntry((18, 32), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 31), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 30), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 29), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 28), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 25), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((20, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((19, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 35), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((19, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((20, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((21, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((22, 34), Entity.BARRIER),
    BlueprintEntry((13, 33), Entity.HARVESTER),
    BlueprintEntry((12, 34), Entity.HARVESTER),
    BlueprintEntry((13, 34), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((14, 34), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((15, 34), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((16, 34), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((17, 33), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((21, 35), Entity.SENTINEL, direction=Direction.NORTHWEST),
)
