from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((13, 29), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 28), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 27), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 26), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 26), Entity.FOUNDRY),
    BlueprintEntry((15, 27), Entity.HARVESTER),
    BlueprintEntry((15, 26), Entity.HARVESTER),
    BlueprintEntry((15, 25), Entity.HARVESTER),
    BlueprintEntry((15, 24), Entity.HARVESTER),
    BlueprintEntry((14, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 25), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 33), Entity.FOUNDRY),
    BlueprintEntry((5, 33), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 32), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 33), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 34), Entity.HARVESTER),
    BlueprintEntry((7, 34), Entity.HARVESTER),
    BlueprintEntry((6, 34), Entity.HARVESTER),
    BlueprintEntry((5, 34), Entity.HARVESTER),
    BlueprintEntry((4, 33), Entity.HARVESTER),
    BlueprintEntry((13, 23), Entity.BARRIER),
    BlueprintEntry((14, 23), Entity.BARRIER),
    BlueprintEntry((15, 23), Entity.BARRIER),
    BlueprintEntry((4, 34), Entity.BARRIER),
    BlueprintEntry((4, 32), Entity.BARRIER),
    BlueprintEntry((4, 31), Entity.BARRIER),
    BlueprintEntry((15, 33), Entity.ROAD),
    BlueprintEntry((16, 33), Entity.ROAD),
    BlueprintEntry((17, 33), Entity.ROAD),
    BlueprintEntry((18, 32), Entity.BARRIER),
    BlueprintEntry((18, 33), Entity.BARRIER),
    BlueprintEntry((18, 34), Entity.BARRIER),
    BlueprintEntry((5, 32), Entity.ROAD),
)
