from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((8, 20), Entity.HARVESTER),
    BlueprintEntry((2, 22), Entity.HARVESTER),
    BlueprintEntry((4, 26), Entity.HARVESTER),
    BlueprintEntry((4, 22), Entity.FOUNDRY),
    BlueprintEntry((3, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 20), Entity.FOUNDRY),
    BlueprintEntry((9, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 14), Entity.HARVESTER),
    BlueprintEntry((15, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 14), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((16, 14), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((17, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((17, 15), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((18, 15), Entity.FOUNDRY),
    BlueprintEntry((20, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((19, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((20, 14), Entity.HARVESTER),
    BlueprintEntry((15, 12), Entity.HARVESTER),
    BlueprintEntry((18, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 22), Entity.CONVEYOR, direction=Direction.WEST),
)
