from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((8, 20), Entity.HARVESTER),
    BlueprintEntry((2, 22), Entity.HARVESTER),
    BlueprintEntry((4, 26), Entity.HARVESTER),
    BlueprintEntry((10, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 14), Entity.HARVESTER),
    BlueprintEntry((20, 14), Entity.HARVESTER),
    BlueprintEntry((15, 12), Entity.HARVESTER),
    BlueprintEntry((18, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((18, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 25), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 25), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 25), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 25), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 19), Entity.BRIDGE, bridge_target=(8, 21)),
    BlueprintEntry((18, 15), Entity.FOUNDRY),
    BlueprintEntry((15, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 14), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((16, 14), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((17, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((17, 15), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((19, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((20, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 21), Entity.FOUNDRY),
    BlueprintEntry((2, 21), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 21), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 21), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 21), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 21), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 21), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 22), Entity.BARRIER),
    BlueprintEntry((2, 23), Entity.BARRIER),
    BlueprintEntry((3, 22), Entity.BARRIER),
    BlueprintEntry((3, 24), Entity.ROAD),
    BlueprintEntry((9, 20), Entity.ROAD),
    BlueprintEntry((7, 20), Entity.BARRIER),
    BlueprintEntry((8, 19), Entity.BARRIER),
    BlueprintEntry((14, 12), Entity.BARRIER),
    BlueprintEntry((15, 11), Entity.BARRIER),
    BlueprintEntry((16, 12), Entity.BARRIER),
    BlueprintEntry((14, 13), Entity.ROAD),
    BlueprintEntry((13, 12), Entity.ROAD),
    BlueprintEntry((14, 11), Entity.ROAD),
    BlueprintEntry((15, 10), Entity.ROAD),
    BlueprintEntry((16, 11), Entity.ROAD),
)
