from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 15), Entity.HARVESTER),
    BlueprintEntry((7, 14), Entity.HARVESTER),
    BlueprintEntry((7, 13), Entity.HARVESTER),
    BlueprintEntry((6, 12), Entity.HARVESTER),
    BlueprintEntry((5, 11), Entity.HARVESTER),
    BlueprintEntry((4, 10), Entity.HARVESTER),
    BlueprintEntry((3, 9), Entity.HARVESTER),
    BlueprintEntry((2, 8), Entity.HARVESTER),
    BlueprintEntry((7, 12), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((6, 11), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((5, 10), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((4, 9), Entity.SENTINEL, direction=Direction.NORTHWEST),
    BlueprintEntry((3, 8), Entity.SENTINEL, direction=Direction.NORTHWEST),
    BlueprintEntry((5, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 14), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 12), Entity.BRIDGE, bridge_target=(4, 15)),
    BlueprintEntry((4, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 11), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 13), Entity.LAUNCHER),
    BlueprintEntry((5, 12), Entity.ROAD),
    BlueprintEntry((2, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 11), Entity.BRIDGE, bridge_target=(2, 14)),
    BlueprintEntry((1, 11), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((1, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 5), Entity.HARVESTER),
    BlueprintEntry((1, 6), Entity.HARVESTER),
    BlueprintEntry((1, 7), Entity.HARVESTER),
    BlueprintEntry((2, 7), Entity.SENTINEL, direction=Direction.NORTH),
    BlueprintEntry((1, 4), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((0, 4), Entity.ROAD),
    BlueprintEntry((1, 3), Entity.ROAD),
    BlueprintEntry((2, 3), Entity.ROAD),
    BlueprintEntry((7, 15), Entity.BARRIER),
    BlueprintEntry((8, 14), Entity.BARRIER),
    BlueprintEntry((2, 4), Entity.HARVESTER),
    BlueprintEntry((3, 3), Entity.HARVESTER),
    BlueprintEntry((4, 3), Entity.HARVESTER),
    BlueprintEntry((5, 3), Entity.HARVESTER),
    BlueprintEntry((6, 4), Entity.HARVESTER),
    BlueprintEntry((7, 5), Entity.HARVESTER),
    BlueprintEntry((5, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 5), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((0, 11), Entity.BRIDGE, bridge_target=(0, 14)),
    BlueprintEntry((0, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 15), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((0, 15), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 4), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 5), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((0, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 7), Entity.BRIDGE, bridge_target=(1, 8)),
    BlueprintEntry((2, 6), Entity.BRIDGE, bridge_target=(0, 8)),
    BlueprintEntry((2, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 5), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((6, 3), Entity.SENTINEL, direction=Direction.SOUTHEAST),
    BlueprintEntry((3, 2), Entity.SENTINEL, direction=Direction.SOUTHEAST),
    BlueprintEntry((5, 2), Entity.SENTINEL, direction=Direction.SOUTHEAST),
    BlueprintEntry((4, 2), Entity.SENTINEL, direction=Direction.SOUTHEAST),
    BlueprintEntry((7, 4), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 4), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((8, 6), Entity.HARVESTER),
    BlueprintEntry((7, 6), Entity.FOUNDRY),
    BlueprintEntry((6, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 7), Entity.ROAD),
    BlueprintEntry((8, 13), Entity.BARRIER),
    BlueprintEntry((6, 16), Entity.BARRIER),
)
