from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((10, 1), Entity.HARVESTER),
    BlueprintEntry((11, 1), Entity.HARVESTER),
    BlueprintEntry((12, 1), Entity.HARVESTER),
    BlueprintEntry((8, 5), Entity.HARVESTER),
    BlueprintEntry((9, 5), Entity.HARVESTER),
    BlueprintEntry((7, 5), Entity.HARVESTER),
    BlueprintEntry((3, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 2), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 2), Entity.FOUNDRY),
    BlueprintEntry((12, 2), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 2), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 2), Entity.BRIDGE, bridge_target=(10, 2)),
    BlueprintEntry((13, 3), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((13, 4), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 5), Entity.HARVESTER),
    BlueprintEntry((16, 5), Entity.HARVESTER),
    BlueprintEntry((17, 5), Entity.HARVESTER),
    BlueprintEntry((1, 3), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((1, 4), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 4), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((2, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 9), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 9), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 9), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 9), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 9), Entity.HARVESTER),
    BlueprintEntry((10, 9), Entity.HARVESTER),
    BlueprintEntry((11, 9), Entity.HARVESTER),
    BlueprintEntry((8, 11), Entity.BARRIER),
    BlueprintEntry((8, 8), Entity.FOUNDRY),
    BlueprintEntry((7, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 8), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 6), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 6), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 3), Entity.ROAD),
    BlueprintEntry((10, 4), Entity.ROAD),
    BlueprintEntry((10, 5), Entity.ROAD),
    BlueprintEntry((18, 3), Entity.BARRIER),
    BlueprintEntry((12, 11), Entity.BARRIER),
    BlueprintEntry((12, 10), Entity.ROAD),
    BlueprintEntry((12, 9), Entity.ROAD),
    BlueprintEntry((12, 8), Entity.ROAD),
    BlueprintEntry((7, 9), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 1), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 10), Entity.ROAD),
)
