from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((2, 28), Entity.HARVESTER),
    BlueprintEntry((8, 25), Entity.HARVESTER),
    BlueprintEntry((10, 27), Entity.HARVESTER),
    BlueprintEntry((2, 23), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 24), Entity.ROAD),
    BlueprintEntry((3, 25), Entity.ROAD),
    BlueprintEntry((2, 26), Entity.BRIDGE, bridge_target=(2, 23)),
    BlueprintEntry((2, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 25), Entity.BRIDGE, bridge_target=(5, 23)),
    BlueprintEntry((6, 23), Entity.ROAD),
    BlueprintEntry((7, 23), Entity.ROAD),
    BlueprintEntry((8, 23), Entity.ROAD),
    BlueprintEntry((9, 23), Entity.ROAD),
    BlueprintEntry((10, 24), Entity.ROAD),
    BlueprintEntry((9, 25), Entity.ROAD),
    BlueprintEntry((9, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 25), Entity.HARVESTER),
    BlueprintEntry((11, 25), Entity.ROAD),
    BlueprintEntry((10, 25), Entity.ROAD),
    BlueprintEntry((15, 25), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((11, 27), Entity.SENTINEL, direction=Direction.EAST),
)
