from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((2, 28), Entity.HARVESTER),
    BlueprintEntry((8, 25), Entity.HARVESTER),
    BlueprintEntry((10, 27), Entity.HARVESTER),
    BlueprintEntry((2, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 25), Entity.BRIDGE, bridge_target=(5, 23)),
    BlueprintEntry((6, 23), Entity.ROAD),
    BlueprintEntry((7, 23), Entity.ROAD),
    BlueprintEntry((8, 23), Entity.ROAD),
    BlueprintEntry((9, 23), Entity.ROAD),
    BlueprintEntry((10, 24), Entity.ROAD),
    BlueprintEntry((9, 25), Entity.ROAD),
    BlueprintEntry((9, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 25), Entity.HARVESTER),
    BlueprintEntry((11, 25), Entity.ROAD),
    BlueprintEntry((15, 25), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((11, 27), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((6, 2), Entity.HARVESTER),
    BlueprintEntry((4, 4), Entity.HARVESTER),
    BlueprintEntry((5, 4), Entity.FOUNDRY),
    BlueprintEntry((5, 2), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 3), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 4), Entity.ROAD),
    BlueprintEntry((4, 3), Entity.BARRIER),
    BlueprintEntry((3, 4), Entity.BARRIER),
    BlueprintEntry((4, 5), Entity.BARRIER),
    BlueprintEntry((4, 6), Entity.ROAD),
    BlueprintEntry((3, 5), Entity.ROAD),
    BlueprintEntry((3, 26), Entity.BRIDGE, bridge_target=(3, 23)),
    BlueprintEntry((2, 26), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 24), Entity.ROAD),
    BlueprintEntry((3, 25), Entity.ROAD),
    BlueprintEntry((4, 26), Entity.ROAD),
    BlueprintEntry((5, 25), Entity.ROAD),
    BlueprintEntry((6, 26), Entity.ROAD),
)
