from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((6, 2), Entity.HARVESTER),
    BlueprintEntry((5, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 3), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 2), Entity.FOUNDRY),
    BlueprintEntry((4, 4), Entity.HARVESTER),
    BlueprintEntry((4, 3), Entity.BARRIER),
    BlueprintEntry((3, 4), Entity.BARRIER),
    BlueprintEntry((4, 5), Entity.BARRIER),
    BlueprintEntry((5, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 21), Entity.BARRIER),
    BlueprintEntry((6, 20), Entity.BARRIER),
    BlueprintEntry((6, 19), Entity.BARRIER),
    BlueprintEntry((6, 18), Entity.BARRIER),
    BlueprintEntry((6, 17), Entity.BARRIER),
    BlueprintEntry((6, 16), Entity.BARRIER),
    BlueprintEntry((6, 15), Entity.BARRIER),
    BlueprintEntry((6, 14), Entity.BARRIER),
    BlueprintEntry((6, 13), Entity.BARRIER),
    BlueprintEntry((6, 12), Entity.BARRIER),
    BlueprintEntry((6, 10), Entity.BARRIER),
    BlueprintEntry((6, 11), Entity.BARRIER),
    BlueprintEntry((6, 9), Entity.BARRIER),
    BlueprintEntry((6, 8), Entity.BARRIER),
    BlueprintEntry((6, 7), Entity.BARRIER),
    BlueprintEntry((6, 6), Entity.BARRIER),
    BlueprintEntry((7, 4), Entity.BARRIER),
    BlueprintEntry((7, 3), Entity.BARRIER),
    BlueprintEntry((7, 2), Entity.BARRIER),
    BlueprintEntry((7, 1), Entity.BARRIER),
    BlueprintEntry((7, 0), Entity.BARRIER),
    BlueprintEntry((5, 4), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 1), Entity.HARVESTER),
    BlueprintEntry((4, 1), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 1), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 2), Entity.BARRIER),
    BlueprintEntry((2, 1), Entity.BARRIER),
    BlueprintEntry((3, 0), Entity.BARRIER),
    BlueprintEntry((2, 24), Entity.BARRIER),
)
