from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((3, 34), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 33), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 32), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 31), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 30), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 29), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 28), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 27), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 26), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 25), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 30), Entity.HARVESTER),
    BlueprintEntry((6, 24), Entity.HARVESTER),
    BlueprintEntry((3, 19), Entity.ROAD),
    BlueprintEntry((3, 18), Entity.ROAD),
    BlueprintEntry((3, 17), Entity.ROAD),
    BlueprintEntry((3, 16), Entity.ROAD),
    BlueprintEntry((3, 14), Entity.ROAD),
    BlueprintEntry((3, 13), Entity.ROAD),
    BlueprintEntry((3, 15), Entity.ROAD),
    BlueprintEntry((4, 12), Entity.ROAD),
    BlueprintEntry((5, 11), Entity.ROAD),
    BlueprintEntry((6, 10), Entity.ROAD),
    BlueprintEntry((7, 9), Entity.ROAD),
    BlueprintEntry((8, 9), Entity.ROAD),
    BlueprintEntry((9, 9), Entity.ROAD),
    BlueprintEntry((10, 9), Entity.ROAD),
    BlueprintEntry((11, 10), Entity.ROAD),
    BlueprintEntry((12, 11), Entity.ROAD),
    BlueprintEntry((13, 12), Entity.ROAD),
    BlueprintEntry((13, 13), Entity.ROAD),
    BlueprintEntry((13, 14), Entity.ROAD),
    BlueprintEntry((14, 15), Entity.ROAD),
    BlueprintEntry((14, 16), Entity.ROAD),
    BlueprintEntry((14, 17), Entity.ROAD),
    BlueprintEntry((14, 18), Entity.ROAD),
    BlueprintEntry((14, 20), Entity.ROAD),
    BlueprintEntry((14, 19), Entity.ROAD),
    BlueprintEntry((14, 21), Entity.ROAD),
    BlueprintEntry((14, 22), Entity.ROAD),
    BlueprintEntry((14, 23), Entity.ROAD),
    BlueprintEntry((14, 24), Entity.ROAD),
    BlueprintEntry((14, 25), Entity.ROAD),
    BlueprintEntry((14, 26), Entity.ROAD),
    BlueprintEntry((14, 27), Entity.BARRIER),
    BlueprintEntry((13, 28), Entity.ROAD),
    BlueprintEntry((12, 29), Entity.ROAD),
    BlueprintEntry((11, 31), Entity.HARVESTER),
    BlueprintEntry((12, 32), Entity.HARVESTER),
    BlueprintEntry((11, 32), Entity.FOUNDRY),
    BlueprintEntry((10, 31), Entity.HARVESTER),
    BlueprintEntry((9, 31), Entity.BRIDGE, bridge_target=(11, 32)),
    BlueprintEntry((10, 30), Entity.ROAD),
    BlueprintEntry((11, 30), Entity.ROAD),
    BlueprintEntry((11, 33), Entity.HARVESTER),
    BlueprintEntry((10, 32), Entity.BRIDGE, bridge_target=(7, 32)),
    BlueprintEntry((7, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 32), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 33), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 34), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 30), Entity.BARRIER),
    BlueprintEntry((12, 10), Entity.ROAD),
    BlueprintEntry((16, 11), Entity.BARRIER),
    BlueprintEntry((13, 27), Entity.ROAD),
    BlueprintEntry((12, 31), Entity.ROAD),
    BlueprintEntry((4, 32), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 34), Entity.BARRIER),
    BlueprintEntry((10, 35), Entity.BARRIER),
    BlueprintEntry((11, 35), Entity.BARRIER),
    BlueprintEntry((3, 23), Entity.ROAD),
    BlueprintEntry((3, 22), Entity.ROAD),
    BlueprintEntry((3, 21), Entity.ROAD),
    BlueprintEntry((3, 20), Entity.ROAD),
    BlueprintEntry((14, 3), Entity.ROAD),
    BlueprintEntry((15, 2), Entity.BARRIER),
    BlueprintEntry((14, 0), Entity.BARRIER),
    BlueprintEntry((13, 2), Entity.ROAD),
    BlueprintEntry((13, 1), Entity.ROAD),
    BlueprintEntry((10, 7), Entity.ROAD),
    BlueprintEntry((11, 6), Entity.ROAD),
    BlueprintEntry((12, 5), Entity.ROAD),
    BlueprintEntry((13, 4), Entity.ROAD),
)
