from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((6, 19), Entity.HARVESTER),
    BlueprintEntry((7, 20), Entity.HARVESTER),
    BlueprintEntry((8, 22), Entity.BRIDGE, bridge_target=(8, 25)),
    BlueprintEntry((9, 24), Entity.ROAD),
    BlueprintEntry((9, 23), Entity.ROAD),
    BlueprintEntry((12, 19), Entity.HARVESTER),
    BlueprintEntry((9, 20), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 27), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 27), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 27), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 27), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 27), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 27), Entity.HARVESTER),
    BlueprintEntry((3, 20), Entity.HARVESTER),
    BlueprintEntry((2, 21), Entity.HARVESTER),
    BlueprintEntry((7, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 20), Entity.FOUNDRY),
    BlueprintEntry((6, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 20), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 20), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 20), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((13, 17), Entity.BARRIER),
    BlueprintEntry((13, 18), Entity.BARRIER),
    BlueprintEntry((13, 19), Entity.BARRIER),
    BlueprintEntry((13, 20), Entity.BARRIER),
    BlueprintEntry((13, 21), Entity.BARRIER),
    BlueprintEntry((10, 23), Entity.BARRIER),
    BlueprintEntry((10, 24), Entity.BARRIER),
    BlueprintEntry((10, 28), Entity.BARRIER),
    BlueprintEntry((12, 18), Entity.ROAD),
    BlueprintEntry((11, 19), Entity.ROAD),
    BlueprintEntry((8, 17), Entity.BARRIER),
)
