from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((6, 19), Entity.HARVESTER),
    BlueprintEntry((7, 20), Entity.HARVESTER),
    BlueprintEntry((7, 19), Entity.FOUNDRY),
    BlueprintEntry((8, 22), Entity.BRIDGE, bridge_target=(8, 25)),
    BlueprintEntry((9, 24), Entity.ROAD),
    BlueprintEntry((9, 23), Entity.ROAD),
    BlueprintEntry((12, 19), Entity.HARVESTER),
    BlueprintEntry((11, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 18), Entity.BRIDGE, bridge_target=(9, 20)),
    BlueprintEntry((9, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 27), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 27), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 27), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 27), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 27), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 27), Entity.HARVESTER),
    BlueprintEntry((3, 20), Entity.HARVESTER),
    BlueprintEntry((2, 21), Entity.HARVESTER),
    BlueprintEntry((4, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 20), Entity.BRIDGE, bridge_target=(7, 19)),
    BlueprintEntry((7, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 22), Entity.CONVEYOR, direction=Direction.EAST),
)
