from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((20, 33), Entity.HARVESTER),
    BlueprintEntry((13, 36), Entity.HARVESTER),
    BlueprintEntry((10, 35), Entity.ROAD),
    BlueprintEntry((19, 35), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((19, 36), Entity.FOUNDRY),
    BlueprintEntry((19, 37), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((19, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((19, 39), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 39), Entity.HARVESTER),
    BlueprintEntry((13, 34), Entity.BARRIER),
    BlueprintEntry((12, 34), Entity.BARRIER),
    BlueprintEntry((11, 34), Entity.BARRIER),
    BlueprintEntry((7, 35), Entity.BARRIER),
    BlueprintEntry((6, 35), Entity.BARRIER),
    BlueprintEntry((5, 35), Entity.BARRIER),
    BlueprintEntry((2, 38), Entity.BARRIER),
    BlueprintEntry((2, 39), Entity.BARRIER),
    BlueprintEntry((3, 38), Entity.ROAD),
    BlueprintEntry((9, 34), Entity.BARRIER),
    BlueprintEntry((21, 38), Entity.BARRIER),
    BlueprintEntry((21, 37), Entity.BARRIER),
    BlueprintEntry((21, 39), Entity.BARRIER),
    BlueprintEntry((21, 36), Entity.BARRIER),
    BlueprintEntry((21, 35), Entity.BARRIER),
    BlueprintEntry((21, 34), Entity.BARRIER),
    BlueprintEntry((20, 34), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((20, 37), Entity.ROAD),
    BlueprintEntry((4, 38), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 37), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 37), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 37), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 38), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 39), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 39), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((15, 37), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 37), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 38), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((16, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 38), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 36), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((15, 34), Entity.BARRIER),
    BlueprintEntry((17, 34), Entity.BARRIER),
    BlueprintEntry((21, 33), Entity.BARRIER),
    BlueprintEntry((17, 33), Entity.BARRIER),
    BlueprintEntry((12, 35), Entity.ROAD),
    BlueprintEntry((14, 36), Entity.ROAD),
    BlueprintEntry((11, 36), Entity.ROAD),
    BlueprintEntry((14, 35), Entity.ROAD),
    BlueprintEntry((13, 35), Entity.ROAD),
    BlueprintEntry((16, 35), Entity.ROAD),
    BlueprintEntry((19, 34), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((17, 36), Entity.HARVESTER),
    BlueprintEntry((17, 35), Entity.ROAD),
    BlueprintEntry((18, 34), Entity.ROAD),
    BlueprintEntry((6, 36), Entity.ROAD),
    BlueprintEntry((5, 37), Entity.ROAD),
    BlueprintEntry((7, 36), Entity.ROAD),
    BlueprintEntry((8, 37), Entity.ROAD),
)
