from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((13, 17), Entity.HARVESTER),
    BlueprintEntry((12, 17), Entity.HARVESTER),
    BlueprintEntry((14, 17), Entity.HARVESTER),
    BlueprintEntry((13, 16), Entity.FOUNDRY),
    BlueprintEntry((14, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((13, 18), Entity.HARVESTER),
    BlueprintEntry((12, 18), Entity.BRIDGE, bridge_target=(13, 16)),
    BlueprintEntry((13, 15), Entity.BRIDGE, bridge_target=(12, 13)),
    BlueprintEntry((9, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 10), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 11), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 11), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 14), Entity.ROAD),
    BlueprintEntry((12, 15), Entity.ROAD),
    BlueprintEntry((15, 17), Entity.HARVESTER),
    BlueprintEntry((15, 16), Entity.BRIDGE, bridge_target=(13, 15)),
    BlueprintEntry((15, 18), Entity.BRIDGE, bridge_target=(15, 16)),
    BlueprintEntry((14, 18), Entity.HARVESTER),
    BlueprintEntry((16, 17), Entity.ROAD),
    BlueprintEntry((11, 17), Entity.ROAD),
)
