from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((20, 30), Entity.HARVESTER),
    BlueprintEntry((20, 33), Entity.HARVESTER),
    BlueprintEntry((17, 36), Entity.HARVESTER),
    BlueprintEntry((13, 36), Entity.HARVESTER),
    BlueprintEntry((5, 36), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 36), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 36), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 36), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 36), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((20, 32), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 31), Entity.FOUNDRY),
    BlueprintEntry((19, 31), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 31), Entity.BRIDGE, bridge_target=(16, 33)),
    BlueprintEntry((17, 32), Entity.ROAD),
    BlueprintEntry((16, 33), Entity.BRIDGE, bridge_target=(14, 35)),
    BlueprintEntry((17, 35), Entity.BRIDGE, bridge_target=(14, 35)),
    BlueprintEntry((11, 35), Entity.BRIDGE, bridge_target=(9, 36)),
    BlueprintEntry((12, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 35), Entity.ROAD),
    BlueprintEntry((15, 34), Entity.ROAD),
    BlueprintEntry((16, 35), Entity.ROAD),
    BlueprintEntry((18, 34), Entity.ROAD),
    BlueprintEntry((19, 34), Entity.ROAD),
    BlueprintEntry((18, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((19, 35), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((19, 36), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((19, 37), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((19, 38), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((19, 39), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 39), Entity.HARVESTER),
)
