from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((13, 17), Entity.HARVESTER),
    BlueprintEntry((14, 17), Entity.HARVESTER),
    BlueprintEntry((9, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 10), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 11), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 11), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 14), Entity.ROAD),
    BlueprintEntry((12, 15), Entity.BRIDGE, bridge_target=(12, 12)),
    BlueprintEntry((15, 17), Entity.HARVESTER),
    BlueprintEntry((11, 17), Entity.BARRIER),
    BlueprintEntry((17, 16), Entity.BARRIER),
    BlueprintEntry((17, 15), Entity.BARRIER),
    BlueprintEntry((13, 19), Entity.BARRIER),
    BlueprintEntry((12, 19), Entity.BARRIER),
    BlueprintEntry((11, 18), Entity.BARRIER),
    BlueprintEntry((14, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 13), Entity.ROAD),
    BlueprintEntry((14, 14), Entity.BARRIER),
    BlueprintEntry((10, 14), Entity.BARRIER),
    BlueprintEntry((10, 12), Entity.ROAD),
    BlueprintEntry((10, 8), Entity.BARRIER),
    BlueprintEntry((10, 9), Entity.BARRIER),
    BlueprintEntry((11, 9), Entity.BARRIER),
    BlueprintEntry((13, 11), Entity.BARRIER),
    BlueprintEntry((13, 10), Entity.BARRIER),
    BlueprintEntry((6, 10), Entity.BARRIER),
    BlueprintEntry((6, 7), Entity.BARRIER),
    BlueprintEntry((10, 7), Entity.BARRIER),
    BlueprintEntry((6, 8), Entity.BARRIER),
    BlueprintEntry((9, 13), Entity.BARRIER),
    BlueprintEntry((15, 16), Entity.FOUNDRY),
    BlueprintEntry((13, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((15, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 16), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((15, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((16, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((16, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 18), Entity.HARVESTER),
    BlueprintEntry((12, 17), Entity.HARVESTER),
    BlueprintEntry((12, 16), Entity.CONVEYOR, direction=Direction.NORTH),
)
