from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((3, 4), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 10), Entity.FOUNDRY),
    BlueprintEntry((7, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 10), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 10), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 10), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 10), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 9), Entity.HARVESTER),
    BlueprintEntry((8, 10), Entity.HARVESTER),
    BlueprintEntry((8, 11), Entity.HARVESTER),
    BlueprintEntry((3, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 11), Entity.HARVESTER),
    BlueprintEntry((2, 12), Entity.HARVESTER),
    BlueprintEntry((1, 12), Entity.HARVESTER),
    BlueprintEntry((2, 10), Entity.ROAD),
    BlueprintEntry((1, 11), Entity.BRIDGE, bridge_target=(3, 10)),
    BlueprintEntry((1, 13), Entity.HARVESTER),
    BlueprintEntry((4, 3), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 3), Entity.ROAD),
    BlueprintEntry((6, 3), Entity.ROAD),
    BlueprintEntry((7, 3), Entity.ROAD),
    BlueprintEntry((8, 3), Entity.ROAD),
    BlueprintEntry((9, 3), Entity.ROAD),
    BlueprintEntry((10, 4), Entity.ROAD),
    BlueprintEntry((10, 2), Entity.ROAD),
    BlueprintEntry((10, 3), Entity.ROAD),
    BlueprintEntry((11, 1), Entity.BARRIER),
    BlueprintEntry((11, 2), Entity.BARRIER),
    BlueprintEntry((11, 3), Entity.BARRIER),
    BlueprintEntry((11, 4), Entity.BARRIER),
    BlueprintEntry((11, 5), Entity.BARRIER),
    BlueprintEntry((5, 13), Entity.HARVESTER),
    BlueprintEntry((2, 13), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 9), Entity.HARVESTER),
    BlueprintEntry((6, 9), Entity.ROAD),
    BlueprintEntry((7, 8), Entity.ROAD),
    BlueprintEntry((8, 8), Entity.BRIDGE, bridge_target=(6, 10)),
    BlueprintEntry((4, 4), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 12), Entity.BRIDGE, bridge_target=(4, 9)),
    BlueprintEntry((4, 11), Entity.ROAD),
    BlueprintEntry((4, 13), Entity.HARVESTER),
    BlueprintEntry((5, 12), Entity.CONVEYOR, direction=Direction.WEST),
)
