from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((4, 19), Entity.HARVESTER),
    BlueprintEntry((3, 19), Entity.FOUNDRY),
    BlueprintEntry((5, 19), Entity.HARVESTER),
    BlueprintEntry((6, 19), Entity.BRIDGE, bridge_target=(3, 19)),
    BlueprintEntry((6, 18), Entity.BRIDGE, bridge_target=(3, 18)),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 19), Entity.HARVESTER),
    BlueprintEntry((10, 19), Entity.HARVESTER),
    BlueprintEntry((11, 19), Entity.HARVESTER),
    BlueprintEntry((9, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 18), Entity.ROAD),
    BlueprintEntry((5, 18), Entity.ROAD),
    BlueprintEntry((12, 19), Entity.BRIDGE, bridge_target=(9, 19)),
    BlueprintEntry((9, 19), Entity.FOUNDRY),
    BlueprintEntry((10, 18), Entity.ROAD),
    BlueprintEntry((11, 18), Entity.ROAD),
    BlueprintEntry((15, 19), Entity.HARVESTER),
    BlueprintEntry((16, 19), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((16, 18), Entity.BARRIER),
    BlueprintEntry((12, 18), Entity.ROAD),
    BlueprintEntry((13, 18), Entity.ROAD),
    BlueprintEntry((14, 18), Entity.ROAD),
    BlueprintEntry((15, 18), Entity.ROAD),
)
