from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((4, 19), Entity.HARVESTER),
    BlueprintEntry((3, 19), Entity.FOUNDRY),
    BlueprintEntry((5, 19), Entity.HARVESTER),
    BlueprintEntry((6, 19), Entity.BRIDGE, bridge_target=(3, 19)),
    BlueprintEntry((5, 18), Entity.BRIDGE, bridge_target=(2, 18)),
    BlueprintEntry((6, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 18), Entity.BRIDGE, bridge_target=(8, 18)),
    BlueprintEntry((7, 19), Entity.HARVESTER),
    BlueprintEntry((10, 19), Entity.HARVESTER),
    BlueprintEntry((11, 19), Entity.HARVESTER),
    BlueprintEntry((12, 19), Entity.FOUNDRY),
    BlueprintEntry((9, 19), Entity.BRIDGE, bridge_target=(12, 19)),
    BlueprintEntry((13, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 19), Entity.HARVESTER),
    BlueprintEntry((1, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 4), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 3), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 1), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 2), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((0, 1), Entity.HARVESTER),
    BlueprintEntry((1, 0), Entity.HARVESTER),
    BlueprintEntry((3, 18), Entity.ROAD),
    BlueprintEntry((4, 18), Entity.ROAD),
    BlueprintEntry((9, 18), Entity.ROAD),
    BlueprintEntry((10, 18), Entity.ROAD),
    BlueprintEntry((13, 19), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((12, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((2, 1), Entity.ROAD),
    BlueprintEntry((3, 0), Entity.BARRIER),
    BlueprintEntry((3, 1), Entity.BARRIER),
    BlueprintEntry((16, 19), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((14, 19), Entity.LAUNCHER),
    BlueprintEntry((16, 18), Entity.BARRIER),
)
