[package]
name = "pyrust-translate"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "pyrust-translate"
path = "src/main.rs"

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
proc-macro2 = { version = "1", features = ["span-locations"] }

[lints]
workspace = true
