[package]
name = "libre-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
paste = "1.0.15"
pyo3 = { version = "0.23.5", features = ["auto-initialize"], optional = true }
pyo3-ffi = { version = "0.23.5", optional = true }
rand = "0.10.1"
rustc-hash = "2.1"

[lints]
workspace = true

[features]
pyo3 = ["dep:pyo3", "dep:pyo3-ffi"]
