[package]
name = "titan"
version = "0.1.0"
edition.workspace = true

[dependencies]
titan-blueprint = { path = "../titan-blueprint" }
titan-bugnav = { path = "../titan-bugnav" }
titan-replay = { path = "../titan-replay" }
titan-core.workspace = true
eframe.workspace = true

[lints]
workspace = true
