PRESSURE_HIGH = 0.6
PRESSURE_ANCHOR_MAX = 0.5
PRESSURE_SPLIT = 0.7
PRESSURE_DEFENSE_MAX = 0.4

BRIDGE_MIN_SAVINGS = 6

CLAIM_TTL = 30
THREAT_TTL = 16
PRESSURE_TTL = 20
BREAK_TTL = 24

REPULSION_JITTER = 0.3

RAID_MIN_HARVESTERS = 2
DEFENSE_MIN_HARVESTERS = 2

SPAWN_TI_BUFFER = 100

RAID_ROUND_THRESHOLD = 100
RAID_EXPLORE_TIMEOUT = 80
RAID_LATE_EXPLORE_ROUND = 200

RAIDER_SPAWN_INTERVAL_EARLY = 30
RAIDER_SPAWN_INTERVAL_LATE = 15
RAIDER_SPAWN_TI_EARLY = 200
RAIDER_SPAWN_TI_LATE = 500
RAIDER_SPAWN_ROUND_EARLY = 80
RAIDER_SPAWN_ROUND_LATE = 200

MAX_BUILDERS = 10
INITIAL_EXPLORERS = 4

CIPHER = 0x2120B7E8
