use std::fs;
use std::path::{Path, PathBuf};

use crate::blueprint::{BlueprintEntry, Direction, Entity};

pub fn blueprints_dir() -> PathBuf {
    let manifest = env!("CARGO_MANIFEST_DIR");
    Path::new(manifest).join("..").join("blueprints").canonicalize().unwrap_or_else(|_| {
        Path::new(manifest).join("..").join("blueprints")
    })
}

pub fn load_bp(map_name: &str) -> Option<Vec<BlueprintEntry>> {
    let path = blueprints_dir().join(format!("{map_name}.bp"));
    let text = fs::read_to_string(&path).ok()?;
    let mut out = Vec::new();
    for (lineno, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        match parse_line(line) {
            Ok(e) => out.push(e),
            Err(msg) => {
                eprintln!("{}:{}: {msg}", path.display(), lineno + 1);
                return None;
            }
        }
    }
    Some(out)
}

fn parse_line(line: &str) -> Result<BlueprintEntry, String> {
    let mut toks = line.split_whitespace();
    let x: i32 = toks
        .next()
        .ok_or("missing x")?
        .parse()
        .map_err(|_| "bad x".to_string())?;
    let y: i32 = toks
        .next()
        .ok_or("missing y")?
        .parse()
        .map_err(|_| "bad y".to_string())?;
    let kind_s = toks.next().ok_or("missing kind")?;
    let kind = Entity::from_name(kind_s).ok_or_else(|| format!("unknown entity: {kind_s}"))?;

    let mut direction = None;
    let mut bridge_target = None;
    let mut phase: i32 = 0;
    for tok in toks {
        if let Some(v) = tok.strip_prefix("dir=") {
            direction = Some(Direction::from_name(v).ok_or_else(|| format!("bad dir: {v}"))?);
        } else if let Some(v) = tok.strip_prefix("bridge=") {
            let (bx, by) = v
                .split_once(',')
                .ok_or_else(|| format!("bad bridge: {v}"))?;
            let bx: i32 = bx.parse().map_err(|_| format!("bad bridge x: {bx}"))?;
            let by: i32 = by.parse().map_err(|_| format!("bad bridge y: {by}"))?;
            bridge_target = Some((bx, by));
        } else if let Some(v) = tok.strip_prefix("phase=") {
            phase = v.parse().map_err(|_| format!("bad phase: {v}"))?;
        }
    }
    Ok(BlueprintEntry {
        pos: (x, y),
        kind,
        direction,
        bridge_target,
        phase,
    })
}

pub fn write_bp(map_name: &str, entries: &[BlueprintEntry]) -> Result<PathBuf, String> {
    let dir = blueprints_dir();
    fs::create_dir_all(&dir).map_err(|e| format!("mkdir: {e}"))?;
    let path = dir.join(format!("{map_name}.bp"));
    let mut ordered: Vec<BlueprintEntry> = entries.to_vec();
    ordered.sort_by_key(|e| (e.phase, e.pos.1, e.pos.0));
    let mut s = format!("# blueprint: {map_name}\n");
    for e in &ordered {
        s.push_str(&format!("{} {} {}", e.pos.0, e.pos.1, e.kind.name()));
        if e.kind.is_directional()
            && let Some(d) = e.direction {
                s.push_str(&format!(" dir={}", d.name()));
            }
        if e.kind == Entity::Bridge
            && let Some((bx, by)) = e.bridge_target {
                s.push_str(&format!(" bridge={bx},{by}"));
            }
        if e.phase != 0 {
            s.push_str(&format!(" phase={}", e.phase));
        }
        s.push('\n');
    }
    fs::write(&path, s).map_err(|e| format!("write: {e}"))?;
    regenerate_index()?;
    Ok(path)
}

fn map_name_to_enum(name: &str) -> String {
    name.to_uppercase()
}

pub fn regenerate_index() -> Result<PathBuf, String> {
    let dir = blueprints_dir();
    let mut names: Vec<String> = fs::read_dir(&dir)
        .map_err(|e| format!("read_dir: {e}"))?
        .filter_map(Result::ok)
        .filter_map(|e| {
            let p = e.path();
            if p.extension().is_some_and(|x| x == "bp") {
                p.file_stem()
                    .and_then(|s| s.to_str())
                    .map(std::string::ToString::to_string)
            } else {
                None
            }
        })
        .collect();
    names.sort();

    let mut s = String::new();
    s.push_str("# generated by blueprint-editor (and scripts/migrate_blueprints.py)\n");
    s.push_str("# do not edit by hand; source: *.bp files in this directory\n\n");
    s.push_str("from blueprint import BlueprintEntry, Direction, Entity\n\n");
    s.push_str("from hardcode.known import KnownMap\n\n");
    s.push_str("__all__ = [\"BLUEPRINTS\"]\n\n");
    s.push_str("BLUEPRINTS: dict[KnownMap, tuple[BlueprintEntry, ...]] = {\n");
    for name in &names {
        let Some(mut entries) = load_bp(name) else {
            continue;
        };
        entries.sort_by_key(|e| (e.phase, e.pos.1, e.pos.0));
        s.push_str(&format!("    KnownMap.{}: (\n", map_name_to_enum(name)));
        for e in &entries {
            let mut parts = vec![
                format!("({}, {})", e.pos.0, e.pos.1),
                format!("Entity.{}", e.kind.name()),
            ];
            if e.kind.is_directional()
                && let Some(d) = e.direction {
                    parts.push(format!("direction=Direction.{}", d.name()));
                }
            if e.kind == Entity::Bridge
                && let Some((bx, by)) = e.bridge_target {
                    parts.push(format!("bridge_target=({bx}, {by})"));
                }
            s.push_str(&format!("        BlueprintEntry({}),\n", parts.join(", ")));
        }
        s.push_str("    ),\n");
    }
    s.push_str("}\n");

    let path = dir.join("_generated.py");
    fs::write(&path, s).map_err(|e| format!("write generated: {e}"))?;
    Ok(path)
}
