PRESSURE_HIGH = 0.6
PRESSURE_ANCHOR_MAX = 0.5
PRESSURE_SPLIT = 0.7
PRESSURE_DEFENSE_MAX = 0.4

BRIDGE_MIN_SAVINGS = 6

CLAIM_TTL = 30
THREAT_TTL = 16
PRESSURE_TTL = 20
BREAK_TTL = 24

REPULSION_JITTER = 0.3

RAID_MIN_HARVESTERS = 3
DEFENSE_MIN_HARVESTERS = 2

SPAWN_TI_BUFFER = 200
SPAWN_INITIAL_CAP = 4
SPAWN_SURPLUS_TURNS = 40

PATROL_IDLE_LIMIT = 30
BUILDCHAIN_WAIT_LIMIT = 80

CIPHER = 0x2120B7E8
