[package]
name = "v"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.34.1"
image = "0.25.10"
prost = "0.14.3"

[build-dependencies]
prost-build = "0.14.3"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cast_possible_truncation = "allow"
cast_sign_loss = "allow"
cast_precision_loss = "allow"
