//! Bake the opening into a self-contained Python file. The bot
//! `import`s it (no runtime file I/O — just a Python import, which
//! the sandbox allows) and asks `play(c, birth)` each turn.
//!
//! The opening describes one player's plan. If the bot is loaded as
//! team B at runtime it must reflect coordinates before calling
//! `play`; that's outside the editor's responsibility.
//!
//! ## Identity
//!
//! Engine ids interleave between teams in the real game, so they
//! aren't a stable lookup key — the id we observe locally won't
//! match the id our bot sees at runtime. Instead, every unit is
//! identified by `(birth_turn, birth_x, birth_y)`: the round on
//! which it appeared and the tile it appeared on. That tuple is
//! unique because:
//!   - Cores exist from turn 0 at fixed map-data positions.
//!   - A core spawns at most one builder per turn (`action_cooldown`
//!     limits it). The builder's birth tile is the spawn target.
//!   - A builder builds at most one turret per turn for the same
//!     reason. The turret's birth tile is the build target.
//!
//! ## Bot integration
//!
//! ```python
//! from .opening_xxx import play
//!
//! class Player:
//!     def __init__(self):
//!         self.birth = None  # (turn, x, y) — set on first run
//!
//!     def run(self, c):
//!         if self.birth is None:
//!             x, y = c.get_position()
//!             self.birth = (c.get_current_round(), x, y)
//!         play(c, self.birth)
//! ```

use std::path::Path;

use crate::opening::{Action, Opening};
use crate::sim::Sim;

/// Resimulate the opening to its horizon to capture each unit's
/// birth (turn, tile), then emit a `.py` file with a single
/// `OPENING` table keyed by birth tuple. Each value is a list of
/// per-relative-turn action lists.
pub fn write_python(opening: &Opening, out: &Path) -> Result<(), String> {
    let mut sim = Sim::from_map(&opening.map_path)?;
    let horizon = opening.horizon;
    let _ = sim.seek(
        opening,
        crate::sim::Cursor {
            turn: horizon,
            unit_idx: 0,
        },
    );

    let mut s = String::new();
    s.push_str("# generated by titan-opening — do not edit by hand.\n");
    s.push_str(&format!("# map: {}\n", opening.map_path.display()));
    s.push_str(&format!("# horizon: {horizon}\n\n"));

    s.push_str(PLAY_HELPER);
    s.push_str("\n\n");

    s.push_str("OPENING = {\n");

    // Sort by birth tuple for deterministic output.
    let mut keys: Vec<u32> = opening.team.units.keys().copied().collect();
    keys.sort_by_key(|&op_id| sim.birth.get(&op_id).copied());

    for op_id in keys {
        let Some(plan) = opening.team.units.get(&op_id) else {
            continue;
        };
        let Some(&(birth_t, bx, by)) = sim.birth.get(&op_id) else {
            // Unit was never reached during sim (e.g. its parent's
            // creating action errored out). Skip — runtime can't
            // identify it anyway.
            continue;
        };
        // Emit `(birth_turn, x, y): [ [...] for each turn from birth ],`
        // — relative-turn indexing means the bot looks up
        // `OPENING[birth][round - birth_turn]`.
        s.push_str(&format!("    ({birth_t}, {bx}, {by}): [\n"));
        for (rel, slot) in plan.actions.iter().enumerate() {
            let _ = rel;
            s.push_str("        [");
            for (i, action) in slot.items.iter().enumerate() {
                if i > 0 {
                    s.push_str(", ");
                }
                s.push_str(&action_to_python(action));
            }
            s.push_str("],\n");
        }
        s.push_str("    ],\n");
    }

    s.push_str("}\n");

    std::fs::write(out, s).map_err(|e| format!("write {}: {e}", out.display()))?;
    Ok(())
}

fn action_to_python(a: &Action) -> String {
    match a {
        Action::Move { dir } => format!("(\"move\", {dir})"),
        Action::Spawn { dir } => format!("(\"spawn\", {dir})"),
        Action::BuildConveyor { x, y, dir } => format!("(\"build_conveyor\", {x}, {y}, {dir})"),
        Action::BuildArmouredConveyor { x, y, dir } => {
            format!("(\"build_armoured_conveyor\", {x}, {y}, {dir})")
        }
        Action::BuildSplitter { x, y, dir } => format!("(\"build_splitter\", {x}, {y}, {dir})"),
        Action::BuildBridge { x, y, tx, ty } => format!("(\"build_bridge\", {x}, {y}, {tx}, {ty})"),
        Action::BuildHarvester { x, y } => format!("(\"build_harvester\", {x}, {y})"),
        Action::BuildRoad { x, y } => format!("(\"build_road\", {x}, {y})"),
        Action::BuildBarrier { x, y } => format!("(\"build_barrier\", {x}, {y})"),
        Action::BuildGunner { x, y, dir } => format!("(\"build_gunner\", {x}, {y}, {dir})"),
        Action::BuildSentinel { x, y, dir } => format!("(\"build_sentinel\", {x}, {y}, {dir})"),
        Action::BuildBreach { x, y, dir } => format!("(\"build_breach\", {x}, {y}, {dir})"),
        Action::BuildLauncher { x, y } => format!("(\"build_launcher\", {x}, {y})"),
        Action::BuildFoundry { x, y } => format!("(\"build_foundry\", {x}, {y})"),
        Action::Destroy { x, y } => format!("(\"destroy\", {x}, {y})"),
        Action::Heal { x, y } => format!("(\"heal\", {x}, {y})"),
        Action::Attack { x, y } => format!("(\"attack\", {x}, {y})"),
        Action::PlaceMarker { x, y, value } => format!("(\"marker\", {x}, {y}, {value})"),
        Action::Rotate { dir } => format!("(\"rotate\", {dir})"),
    }
}

/// Inlined dispatcher. Bot does:
///
/// ```python
/// from .opening_xxx import play, OPENING
/// # in run(): if not play(c, self.birth): ...
/// ```
///
/// Returns True while the table still drives this unit; False once
/// the unit is past its scripted lifetime so the bot can fall
/// through to dynamic logic.
const PLAY_HELPER: &str = r#"_DIR_DELTAS = (
    (0, -1),  # 0  N
    (1, -1),  # 1  NE
    (1, 0),   # 2  E
    (1, 1),   # 3  SE
    (0, 1),   # 4  S
    (-1, 1),  # 5  SW
    (-1, 0),  # 6  W
    (-1, -1), # 7  NW
    (0, 0),   # 8  Centre
)


def play(c, birth):
    """Drive a unit from its birth identity. `birth` is the tuple
    `(birth_turn, birth_x, birth_y)` the bot recorded on its first
    `run()`. Returns True while the opening still scripts this
    unit, False once exhausted (fall through to dynamic logic)."""
    plan = OPENING.get(birth)
    if plan is None:
        return False
    rel = c.get_current_round() - birth[0]
    if rel < 0 or rel >= len(plan):
        return False
    actions = plan[rel]
    cx, cy = c.get_position()
    for entry in actions:
        op = entry[0]
        if op == "move":
            c.move(entry[1])
        elif op == "spawn":
            dx, dy = _DIR_DELTAS[entry[1]]
            c.spawn_builder((cx + dx, cy + dy))
        elif op == "build_conveyor":
            c.build_conveyor((entry[1], entry[2]), entry[3])
        elif op == "build_armoured_conveyor":
            c.build_armoured_conveyor((entry[1], entry[2]), entry[3])
        elif op == "build_splitter":
            c.build_splitter((entry[1], entry[2]), entry[3])
        elif op == "build_bridge":
            c.build_bridge((entry[1], entry[2]), (entry[3], entry[4]))
        elif op == "build_harvester":
            c.build_harvester((entry[1], entry[2]))
        elif op == "build_road":
            c.build_road((entry[1], entry[2]))
        elif op == "build_barrier":
            c.build_barrier((entry[1], entry[2]))
        elif op == "build_gunner":
            c.build_gunner((entry[1], entry[2]), entry[3])
        elif op == "build_sentinel":
            c.build_sentinel((entry[1], entry[2]), entry[3])
        elif op == "build_breach":
            c.build_breach((entry[1], entry[2]), entry[3])
        elif op == "build_launcher":
            c.build_launcher((entry[1], entry[2]))
        elif op == "build_foundry":
            c.build_foundry((entry[1], entry[2]))
        elif op == "destroy":
            c.destroy((entry[1], entry[2]))
        elif op == "heal":
            c.heal((entry[1], entry[2]))
        elif op == "attack":
            c.fire((entry[1], entry[2]))
        elif op == "marker":
            c.place_marker((entry[1], entry[2]), entry[3])
        elif op == "rotate":
            c.rotate(entry[1])
    return True
"#;
