//! Bake the opening into a self-contained Python file. The bot
//! `import`s it (no runtime file I/O — just a Python import, which the
//! sandbox allows) and calls `play(c, TEAM_A)` (or `TEAM_B`) each turn.

use std::path::Path;

use crate::opening::{Action, Opening};
use crate::sim::Sim;

/// Resimulate the opening to its horizon to capture the engine-ID
/// mapping, then emit a `.py` file with `TEAM_A`, `TEAM_B`, and a
/// `play()` dispatcher.
pub fn write_python(opening: &Opening, out: &Path) -> Result<(), String> {
    let mut sim = Sim::from_map(&opening.map_path)?;
    let horizon = opening.horizon;
    let _ = sim.seek(
        opening,
        crate::sim::Cursor {
            turn: horizon,
            unit_idx: 0,
        },
    );

    // opening_id → engine_id, per team.
    let mut opening_to_engine: [std::collections::HashMap<u32, i32>; 2] =
        [Default::default(), Default::default()];
    for (&engine_id, &(team, op_id)) in &sim.engine_to_opening {
        opening_to_engine[team as usize].insert(op_id, engine_id);
    }

    let mut s = String::new();
    s.push_str("# generated by titan-opening — do not edit by hand.\n");
    s.push_str(&format!("# map: {}\n", opening.map_path.display()));
    s.push_str(&format!("# horizon: {horizon}\n\n"));

    s.push_str(PLAY_HELPER);
    s.push_str("\n\n");

    s.push_str("TEAM_A = {\n");
    write_team(&mut s, opening, 0, &opening_to_engine[0]);
    s.push_str("}\n\n");

    s.push_str("TEAM_B = {\n");
    write_team(&mut s, opening, 1, &opening_to_engine[1]);
    s.push_str("}\n");

    std::fs::write(out, s).map_err(|e| format!("write {}: {e}", out.display()))?;
    Ok(())
}

fn write_team(
    out: &mut String,
    opening: &Opening,
    team_idx: usize,
    op_to_engine: &std::collections::HashMap<u32, i32>,
) {
    let team = &opening.teams[team_idx];
    // Sort by (turn, engine_id) for deterministic output.
    let mut rows: Vec<(usize, i32, Vec<Action>)> = Vec::new();
    for (&op_id, plan) in &team.units {
        let Some(&engine_id) = op_to_engine.get(&op_id) else {
            continue;
        };
        for (rel, slot) in plan.actions.iter().enumerate() {
            if slot.items.is_empty() {
                continue;
            }
            let turn = plan.spawn_turn + rel;
            rows.push((turn, engine_id, slot.items.clone()));
        }
    }
    rows.sort_by_key(|&(turn, eid, _)| (turn, eid));

    for (turn, eid, items) in rows {
        out.push_str(&format!("    ({turn}, {eid}): ["));
        for (i, action) in items.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&action_to_python(action));
        }
        out.push_str("],\n");
    }
}

fn action_to_python(a: &Action) -> String {
    match a {
        Action::Move { dir } => format!("(\"move\", {dir})"),
        Action::Spawn { dir } => format!("(\"spawn\", {dir})"),
        Action::BuildConveyor { x, y, dir } => format!("(\"build_conveyor\", {x}, {y}, {dir})"),
        Action::BuildArmouredConveyor { x, y, dir } => {
            format!("(\"build_armoured_conveyor\", {x}, {y}, {dir})")
        }
        Action::BuildSplitter { x, y, dir } => format!("(\"build_splitter\", {x}, {y}, {dir})"),
        Action::BuildBridge { x, y, tx, ty } => format!("(\"build_bridge\", {x}, {y}, {tx}, {ty})"),
        Action::BuildHarvester { x, y } => format!("(\"build_harvester\", {x}, {y})"),
        Action::BuildRoad { x, y } => format!("(\"build_road\", {x}, {y})"),
        Action::BuildBarrier { x, y } => format!("(\"build_barrier\", {x}, {y})"),
        Action::BuildGunner { x, y, dir } => format!("(\"build_gunner\", {x}, {y}, {dir})"),
        Action::BuildSentinel { x, y, dir } => format!("(\"build_sentinel\", {x}, {y}, {dir})"),
        Action::BuildBreach { x, y, dir } => format!("(\"build_breach\", {x}, {y}, {dir})"),
        Action::BuildLauncher { x, y } => format!("(\"build_launcher\", {x}, {y})"),
        Action::BuildFoundry { x, y } => format!("(\"build_foundry\", {x}, {y})"),
        Action::Destroy { x, y } => format!("(\"destroy\", {x}, {y})"),
        Action::Heal { x, y } => format!("(\"heal\", {x}, {y})"),
        Action::Attack { x, y } => format!("(\"attack\", {x}, {y})"),
        Action::PlaceMarker { x, y, value } => format!("(\"marker\", {x}, {y}, {value})"),
        Action::Rotate { dir } => format!("(\"rotate\", {dir})"),
    }
}

/// Inlined dispatcher. Bots `from .opening_xxx import play, TEAM_A` and
/// call `play(c, TEAM_A)` once per `run()`. Returns True while the
/// opening is still driving; False once exhausted, so the bot can fall
/// through to dynamic logic.
const PLAY_HELPER: &str = r#"_DIR_DELTAS = (
    (0, -1),  # 0  N
    (1, -1),  # 1  NE
    (1, 0),   # 2  E
    (1, 1),   # 3  SE
    (0, 1),   # 4  S
    (-1, 1),  # 5  SW
    (-1, 0),  # 6  W
    (-1, -1), # 7  NW
    (0, 0),   # 8  Centre
)


def play(c, table):
    actions = table.get((c.get_current_round(), c.get_id()))
    if not actions:
        return False
    cx, cy = c.get_position()
    for entry in actions:
        op = entry[0]
        if op == "move":
            c.move(entry[1])
        elif op == "spawn":
            dx, dy = _DIR_DELTAS[entry[1]]
            c.spawn_builder((cx + dx, cy + dy))
        elif op == "build_conveyor":
            c.build_conveyor((entry[1], entry[2]), entry[3])
        elif op == "build_armoured_conveyor":
            c.build_armoured_conveyor((entry[1], entry[2]), entry[3])
        elif op == "build_splitter":
            c.build_splitter((entry[1], entry[2]), entry[3])
        elif op == "build_bridge":
            c.build_bridge((entry[1], entry[2]), (entry[3], entry[4]))
        elif op == "build_harvester":
            c.build_harvester((entry[1], entry[2]))
        elif op == "build_road":
            c.build_road((entry[1], entry[2]))
        elif op == "build_barrier":
            c.build_barrier((entry[1], entry[2]))
        elif op == "build_gunner":
            c.build_gunner((entry[1], entry[2]), entry[3])
        elif op == "build_sentinel":
            c.build_sentinel((entry[1], entry[2]), entry[3])
        elif op == "build_breach":
            c.build_breach((entry[1], entry[2]), entry[3])
        elif op == "build_launcher":
            c.build_launcher((entry[1], entry[2]))
        elif op == "build_foundry":
            c.build_foundry((entry[1], entry[2]))
        elif op == "destroy":
            c.destroy((entry[1], entry[2]))
        elif op == "heal":
            c.heal((entry[1], entry[2]))
        elif op == "attack":
            c.fire((entry[1], entry[2]))
        elif op == "marker":
            c.place_marker((entry[1], entry[2]), entry[3])
        elif op == "rotate":
            c.rotate(entry[1])
    return True
"#;
