"""Hardcoded map data for known official maps.

Key: (w, h, core_a_x, core_a_y)
Value: (encoded_tiles_b64, core_b)
Tiles: 4 tiles packed per byte (2 bits each), base64 encoded.
Tile values: 0=empty, 1=wall, 2=ore_ti, 3=ore_ax
"""

import base64

from cambc import Environment, Position

__all__ = ["MAPS", "decode"]


_TILE_TO_ENV: dict[int, Environment] = {
    0: Environment.EMPTY,
    1: Environment.WALL,
    2: Environment.ORE_TITANIUM,
    3: Environment.ORE_AXIONITE,
}


def _encode(tiles: list[int]) -> str:
    packed = bytearray()
    for i in range(0, len(tiles), 4):
        b = 0
        for j in range(4):
            if i + j < len(tiles):
                b |= (tiles[i + j] & 3) << (j * 2)
        packed.append(b)
    return base64.b64encode(bytes(packed)).decode("ascii")


def decode(data: str, n: int) -> list[Environment]:
    packed = base64.b64decode(data)
    tiles: list[Environment] = []
    for b in packed:
        for j in range(4):
            if len(tiles) >= n:
                break
            tiles.append(_TILE_TO_ENV[(b >> (j * 2)) & 3])
    return tiles


MAPS: dict[tuple[int, int, Position], tuple[str, Position]] = {
    # arena
    (25, 25, Position(8, 10)): (
        "AAAAAAAAAAAAAAAAAAAAVFUAAAAAgAAUAACAAAAAAQAAAAAgBAAAAAAAQAAAAMAAAAEAAgAAAAQAAABABRIAAAAAAEAAAABAwAAAAAAAAQAAAAAMBAAAAAQAAAAAABBCBQAAAEAAAAAAAgABAAwAAAAEAAAAAABAIAAAAAAAAQAACAAAUAAIAAAAAFRVAAAAAAAAAAAAAAAAAAAAAA==",
        Position(16, 14),
    ),
    # battlebot
    (21, 29, Position(4, 4)): (
        "AAAAAABQVVVVVUEAAAAABAEAAAAQBAAgAEAQAAAAAEFAAAIEBAEBABAQBBAgEEAQQABAAEEABEEABAFAUQAQBEAABEAQQgBAIEFAAAAEBAFBURAQBMRFTUAQECgKAUFAoCgEBAEEAAQQhEAABEgQCBQFCEEBAAEABRQAAAAFQAHMAAUAFDADBQAAAQABAABQUQEAAAAQAAAA",
        Position(16, 4),
    ),
    # chemistry_class
    (40, 40, Position(14, 23)): (
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAwAAAAAzAAAAAAzAAAAADAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAIAACACAAAAAIAIAACAAAAQBAAAAgAAAAAAEAQAAAAAAAAAABAEAAAAAAAAIAAQBAAIAAAAAIgAEAQAIgAAAAAgABAEAAgAAAAAAAAQBAAAAAAAAAAAEAQAAAAAAFBQABAEAAUFAABAEAAQBAAEAQAAQBAAEAQABAEAAEAQABAEAAQBAAAQQAAQBAABBAAAEEAAEAQAAQQAAAQAARAEQAAQAAAEAAEQBEAAEAAAAQAEEAQQAEAAAAEABNAHEABAAEAIghBAAQSCIAFAIAAQAAAEAAgBkAAgYAAACQgABhCAAEgAACEAAgRAVVUVAABUVVUBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        Position(25, 23),
    ),
    # cinnamon_roll
    (30, 30, Position(2, 27)): (
        "AAAAAAAAAAAAAAAAAAAAAABQVRUAAAAAUAAAFAAAAEAAgAAUAAAAAQAAAAQAAARAVQUAAQAQQAEABRAAAAEBIAABBAAEBAAAEEAAQBBAVSAEBAAkAcEQQEAAQAQEVAQEBABEQFB0QBABQAQhXQQkEQBEGBB1SBABQAQBHQUBEQAQEBAVEBABAAEBBENAGAAQEAhVAQQBAAEEAAAQEAAQQAAIQEAAAARQAEABBABAAFBVARAAABAAAABAAAAAFAACAAEAAAAUAAAFAAAAAFRVBQAAAAAAAAAAAAAAAAAAAAAA",
        Position(27, 2),
    ),
    # corridors
    (31, 31, Position(5, 15)): (
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAUBAQEBAQEAAEBAQEBAQEAAEBAQEBAQEICEhISEhISFAQEBAQEBAABAQEBAQEBAABAQEBAQEBCAhITExISEhQEBAQEBAQAAQEBAQEBAQAAQEBAQEBAQgASExMSEBIUBAQEBAQEAAEBAQEBAQEAAEBAQEBAQEICEhMTEhISFAQEBAQEBAABAQEBAQEBAABAQEBAQEBCAhISEhISEhQEBAQEBAQAAQEBAQEBAQAAQEBAQEBAQAAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        Position(25, 15),
    ),
    # default_large1
    (40, 40, Position(11, 25)): (
        "AAAAAAAAAgAAAAAgAAAAAAAAAAAAAAIAVVVVBQACMAAAUAAAAFQAAAAAABUAAAAABQAAAEABAAAAABQAACBQAAAAAABQAAAAFAAAAAAAQAAAAAUAAAAAMAAAAAwBAAAAA6gAAABAAAAAAQAAAAAAQAAAAAEAAAAAAFAACAAFAAAAAAAQAAAABAAAACAAAAAAAAQAAAAAAAAAAAAQAAAAAAAAAAAAUAAAAAAAAAAAAEABQAEAAAAAAAAAVFUAAAAAAAAADAAAAAAAAAAAMAAAAAAAAABVFQAAAAAAAABAAUABAAAAAAAAAAAABQAAAAAAAAAAAAQAAAAAAAAAAAAQAAAAAAAIAAAAEAAAAAQAAAAAAFAAIAAFAAAAAABAAAAAAQAAAAAAQAAAAAEAAAAqwAAAAEAwAAAADAAAAABQAAAAAQAAAAAAFAAAAAUAAAAAAAUIAAAUAAAAAEABAAAAUAAAAABUAAAAAAAVAAAABQAADIAAUFVVVQCAAAAAAAAAAAAAAAgAAAAAgAAAAAAAAA==",
        Position(28, 14),
    ),
    # default_large2
    (50, 30, Position(3, 16)): (
        "AAAAAAAAAAAAAAAAAAAAAAAgDIMAAAAAAAAAAAAIAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAUIAAAAAAACBQAAAFABAAAAAAAAVAAAAAAUAFBVVVUAQAEAAABABVBVVVVVABUAAAAAWEAFAAAAFVACAAAAAAUFAAAAAAUFAAAAAFAAAAAAAABQAAAAAAAFAAAAAAAABQAAACBQACAAAIAAUIAAAAAABQAAAAAAAAUAAAAAVAAAAAAAAFABAAAAQAEAQgEUCAAUAAAAABUAABRAAQBABQAAAFAAAEABFAAAUAAAAAAAAAIUQAEIAAAAAAAAAABAARQAAAAAAAAAACAAFEABgAAAAAAAACAAUAFUAIAAAAAAACAAABVABQCAAAAAACAAAFTwUAEAgAAACAgAAEABABQAAAACAgAAAAAVAEAFAAAAAAAAAEBVwDBQFQAAAAAAAFVVAAAAUFUFAAAAAFBVAQwAA1RVAAAAAAAAAAAAAAAAAAAA",
        Position(46, 16),
    ),
    # default_medium1
    (30, 30, Position(10, 19)): (
        "AAAAAAAAAAAAAAAAAAAAMAAAgAIAgAAAAAAIAAAAQFUAAAAEAAAABAAAQAEAAEAAAABQCAAoBAAAAAQAAEIAAABAVQAAAAAEAAAAAAAAQAAAAAAAAAAEAAAACAAAQAAAAAAAAMAAAAAAAAAA4FUBAAAAQFULAAAAAAAAAAMAAAAAAAABAAAgAAAAEAAAAAAAAAABAAAAAAAAEAAAAABVAQAAAIEAABAAAAAQKAAgBQAAAAEAAEABAAAQAAAAEAAAAFUBAAAAIAAAAAACAIACAAAMAAAAAAAAAAAAAAAAAAAA",
        Position(19, 10),
    ),
    # default_medium2
    (30, 30, Position(3, 3)): (
        "AAAAAAAAAAAAAAQAAQAAAABAABAAAAAAADTAAQAAAABAABAAAAAAAAQAAQAAAABAABAAAAAACAAAAAIAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAQBAAAIACBAAAAQAAAAAAQBAAFRVARAAAAQAAAAAAQBAAAAAABAAAAQAAAAAAQAAAIAgAAAAAAAACAIAAAACAMAwAAAIIABAABAAgAAAAAQAAQAAAABAABAAAABUBQQAAVUBAABAABAAAACAAgQAASgAIAhAABAAggAAAwAAAAwAAAAACAIAAAAAAAAAAAAA",
        Position(26, 3),
    ),
    # default_small1
    (20, 20, Position(1, 1)): (
        "AAAAAAAAIAAAAAAAAAAAAAFVAQJAAQAAAAAAAAQAgCAIFAAAAAAAAADAAAAEAAAMAAQQADAAABAAAAMAAAAAAAAAFCAIAgAQAAAAAAAAQAGAQFVAAAAAAAAAAAAACAAAAAAAAA==",
        Position(18, 18),
    ),
    # default_small2
    (21, 21, Position(10, 1)): (
        "AAAAAAAgAAAAAAIAAAAAAAABABAAABQgUAAAQAFQAAACVFUAAkAAAEAAUIEACBUAADADAAAAAAAAAAAAMwAAUIEACBUABAAABAACVFUAAgAUAAUAABQgUAAAEAAAAQAAAAAAAAIAAAAgAAAAAAAA",
        Position(10, 19),
    ),
    # dna
    (21, 50, Position(10, 48)): (
        "AAAAAAAAAAAAAAAAAAAAAIAAAMAAAFpV1QMAIAAAAwCAAgAPAABoVQ8AAIDKDwAAAKADAAAAwAoAAADwowIAAPBVKQAA8ACAAgDAAAAIAMBXVaUAAAMAAAIADAAACABwVVUlAMADAKAAAAwAgAAA8FWVAgAAD4ACAADwowIAAAC8AAAAAOADAAAAqPwAAAAoAA8AAGhV9QAAIAAAAwCgAAA8AIBVVdUAAAIAAAMACAAADACgVVU9AAACADAAACgA8AAAgFb1AAAAqPwAAAAAOgAAAACsAAAAAD8qAAAAX5UCAAAPACgAAAwAgAAAfFVVCgAwAAAgAAAAAAAAAAAAAAAAAAAAAAA=",
        Position(10, 1),
    ),
    # face
    (20, 20, Position(5, 7)): (
        "AIAAAgAMAAAAMEBVAFUBEABBAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAgAFAAgAAAUAAAAABQAAAAAVQAAAAAAAAAAgQBCAAABAEAAABQAFAAIQFUBIAAAAAAAAAwAMAAAAAAAAA==",
        Position(14, 7),
    ),
    # galaxy
    (40, 40, Position(4, 35)): (
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAACAAACAAAAAFQAAAAAAAAAAUAEAAAAAAAAAABQACAAAAAAAAAAFAAADAAAAAAAAAQAAAAAAAACAQAAAAAAACAAAAFAAQFUFAAAAAAAQMBQAUAEAAAAAEAAFAAAUAAAAABQAAQKAQAEAAAAEQAAAAAAFAAAABEIAVAEABAAAAARAAAAUABAAQAAQQAAAQABAAEAAUAABDEABAwFAwEABMEAABQABAAEAAQAAAQQAAQAEABQAAAEQAAAAEABAFQCBEAAAAFAAAAAAARAAAABAAQKAQAAUAAAAABQAAFAABAAAAABABQAUDAQAAAAAAFBVAQAFAAAAIAAAAAAAAQIAAAAAAAAAQAAAAAAAAMAAAFAAAAAAAAAAIAAUAAAAAAAAAABABQAAAAAAAAAAVAAAAAIAAAIAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        Position(35, 4),
    ),
    # hooks
    (31, 31, Position(3, 22)): (
        "AAAAAAAAAAAAABAAAAAAgAoABCoAAAAAAgCBAEBVAQAAQAAAEAAAAFQVVAEEAAAAAAABAAEAAAAAQABAAAAAAIASGhAAAEBVgAQGAAAAEAAAAQEAAAAEAEBAAAAAAAAAABBQVQEACgA8BABAAIBQFQMBABBAAADETAAABBAAAAFTFQgABABA8ACAAgBVFRAAAAAAAAAABAQAQAAAAAABAQAQAAAAQEIIVAUAABCQEgoAAAAABAAEAAAAAAABAAEAAAAAQABVUFUAAAAQAAAEAAAAVQUACAEAAgAAAKBCAIAKAAAAABAAAAAAAAAAAAAAAA==",
        Position(27, 8),
    ),
    # hourglass
    (27, 45, Position(13, 43)): (
        "BAEAAAAQBAEBAAAAAUEAAQAAEEAQAAEAAAEQFAABABAABQQABUABQAABAKgKABBAAAAAAAAEUACAAABAARAAACAAEAAEACAAAAQABQCAAEABAAEAAAAQAEAAACIABABQAAgAQAEAEACAABAAABQAAAAFAAAUgABQAAAAFAACBQAAABQAUAAAAACUqgUAAAAA1F8AAAAAAAQEAAAAAED9BQAAAACUqgUAAABAAQAFAAAAFAACBQAAQAEIAAUAABQAAAAFAAABAAgAAQBQAAgAQAEABAAgAkAAAAEAAAAQAFAAAAgAFAAEACAAAAQAAQAAAgABUACAAABAAQQAAAAAQAABAKgKABBAAFAAFAAEFAABABAABQEQAAAQAEEAAQAAEEAQEAAAABAQBAEAAAAQBA==",
        Position(13, 1),
    ),
    # landscape
    (30, 30, Position(3, 2)): (
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAACoAAAAAFRVAQMAAAAVAEAxAIAABAAAQAUAKhAAAAAABcBQAAAAAABVVQAAAAAAAAAAIAACAAIACKCoiqqKqiqqAAAAAAAAAAAAAAAAAAAAiqqoqqiqogoCIAAgAIAAAAAAAAAAAAAAAAAAUFUFAQAAAFAADEUAAABUAKACUAEAFAMACABAVRUwAAAAAAAAgAoAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        Position(3, 27),
    ),
    # minimaze
    (25, 25, Position(1, 23)): (
        "KAMAAQCjIAAABAAAUlUIEIBUFQBBQEAQAAAEoSlBAEAQhIAEQQBBEAAQBAEkQVVVEAaQBMANQBhAFQAEAFUAABACEgAAAEAwQwAAFVBVVRVQQUAAAEBAAAEAAgIAAQQAQAAABABUBUFVAAAQEAQBAQBVQBAEVAEAIEEQAgAAAARBAAAAVBUEVQUAAACYAAAAAABgAgAAAAAAAQAAAA==",
        Position(23, 23),
    ),
    # pls_buy_cucats_merch
    (49, 49, Position(13, 17)): (
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAEEAAMwgAAAAAAAAAEEEEMIgAAAAAAAAAQERAAAgIAAAAAAAAAAEAAYAIAAAAAAAAAAQABAAIAAAAAAAAABAAEAAAAAAAAAAAABAAAAEAgAAAAAAAAAARBAEFAAAAAAAAAABBEBBBgIgAAAAAAAAQABAEBAAAAAAAAAAAFRAQEIAAAABVVRUAEAABQQAAAAoEAEAAQAAEBAEAAIIQAAABAAFAEAQAAwgCAQAQAAQARAQAP4ACBABAABAAQBAAMAAAEAAAAUAAAEEAAAAAAgEAEAARAUQAAAAAAAQAQABEBFAAIAAAIlJVVVVBVRUAIAIAAAAAAAAAAAAAAAIAAAIAAAAAAAAADAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAACAAACAAAAAAAAAAAAAAAiAFBVBVVVVRUiAgAgABRARAAEAEAAAAAAAEQAEQEQAAABAgAAAAQBAAQAAQAQAAAwABAEABAABABAAArwA0BEAEAAEAAAAYIAA0AQBAABAAEAEAgCAABBQAAEAAQAQIACAAAEAQEQAFBVVQEAAAgQEBBQAQAAAAAAAABAQBAAEAAAAAAAAIgIBBEQBAEAAAAAAAAAQAFBEAEAAAAAAAAIAAABABAAAAAAAAAAAAAQABAAAAAAAAAAgABAAEAAAAAAAAAAgAgAAQABAAAAAAAAgIAABEQEAAAAAAAAAIgwQAQRAAAAAAAAAIAwAwQQAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        Position(35, 31),
    ),
    # shish_kebab
    (20, 20, Position(2, 2)): (
        "AAAAAAAAACAABQAAAEABAAAAVQAAAEBgIAAAQEMAAABQFQAACAQHAAAAJAQAAABUAQAAQBUAAAAQGAAAANAQIAAAVAUAAADBAQAACAkBAAAAVQAAAEABAAAAUAAIAAAAAAAAAA==",
        Position(17, 17),
    ),
    # thread_of_connection
    (20, 20, Position(3, 16)): (
        "AAAAAQAAAEABAAAAQAAAgApQAAAgIBAIAAiAEAIACAUTQgEIFFMIVSAQTCAAgFBMgQAAQjEFAgAIMQQIVSDFFCBAgcRQIACABAIgACAECAgAAAWgAgAAAQAAAEABAAAAQAAAAA==",
        Position(16, 3),
    ),
    # tree_of_life
    (39, 30, Position(4, 22)): (
        "AAAIAAIgAAgAACAAgAAAAAgAIAAAAwAAMwAAMAAAAAAAAQABAAAAAAIIcABAAwggAABUBUAABEBVAAAAABRAQAAFAAAAACBQAAAUIAAAAAAAQABAAAAAAAAAAEIABAIAAAAAAABAQAAAAAAAAAAAEBAAAAAAAAAAAAQEAAAAAAAAAAABAQAAAAAAAABAQAAAAAAAAAAAEBAAAAAAAAAAAAQEAAAAAAAAAAABAQAAAAAAAAAQAAEAAAAAAAAABEAAAAAAAAAAAAEQAAAAAAAAAFAAFAAAAAAAAAABABAAAAAAAEBVVVVVBQAAQFUFAAAAAFRVQAWAAAgAgAAIQAUAAAAAAAAAAAAAAIAAAAAACAAAIAAAAAgIAAAAAgAAAAAAAAAAAAA=",
        Position(34, 22),
    ),
    # wasteland
    (40, 40, Position(3, 36)): (
        "AARAAIEAREAAAAABAgAEAFAEAAABAAAlAFAAEAEAAFIVAAEgYQQAAAEQBAREAAFQAAAAgABQAUAEBAAAMAEgBMAFEBQBAAAAAREEBUEQEQRAUREEBRAEBARBBEBENIREQAAABRQQgABBQABRFBEQAAAQABFVABAABFQQFUEFYBRAFQQBEQRQAAEBQVCARAAFAQBBQGAEAAQQAAABAAAUFAARAIQEAxQEASFABEgBEBQEQVUAQAABAAEQBQwBBRBAABFACAFAAEFBAAFAIAFEAAEEUEAwUARAAEAAAQBVQRAUBEAhEAFIQBAUwBASAEQAFBQAAEAAAAQQABAJAUEAQFAAEQIFQUBAAAUQREAQVAEUCVBBVAQVEAAEAFVEAAQAAAREFEUAAUEAAgQUUAAAARESHBEBEEEQEBAEUBBERQEQRARBUBBEQAAAAEAUBFADEAhADAAAEBABQAUAAgAAAAVAABEQEARAAAAQSQhAAFSFAABABAAFAFgAAEAAABAFABAAgEAAAAABEQBCAAEQAA==",
        Position(36, 3),
    ),
}
