"""One-shot migrator: per-map .py blueprints -> .bp text + _generated.py.

Run once; delete old .py files after verification.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

from blueprint import DIRECTIONAL, BlueprintEntry, Entity

ROOT = Path(__file__).resolve().parents[1]
BLUEPRINTS_DIR = ROOT / "pkg" / "blueprint" / "blueprints"
KNOWN_PY = ROOT / "pkg" / "blueprint" / "src" / "blueprint" / "known.py"


def load_py_blueprint(path: Path) -> tuple[BlueprintEntry, ...] | None:
    spec = importlib.util.spec_from_file_location(f"_bp_{path.stem}", path)
    if spec is None or spec.loader is None:
        return None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    entries = getattr(mod, "BLUEPRINT", None)
    if not isinstance(entries, tuple):
        return None
    return entries


def render_bp(entries: tuple[BlueprintEntry, ...], map_name: str) -> str:
    lines = [f"# blueprint: {map_name}"]
    for e in entries:
        parts = [str(e.pos[0]), str(e.pos[1]), e.kind.name]
        if e.kind in DIRECTIONAL and e.direction is not None:
            parts.append(f"dir={e.direction.name}")
        if e.kind == Entity.BRIDGE and e.bridge_target is not None:
            bx, by = e.bridge_target
            parts.append(f"bridge={bx},{by}")
        lines.append(" ".join(parts))
    return "\n".join(lines) + "\n"


def load_known_map_names() -> set[str]:
    if not KNOWN_PY.exists():
        msg = f"expected KnownMap at {KNOWN_PY}"
        raise FileNotFoundError(msg)
    spec = importlib.util.spec_from_file_location("_known_probe", KNOWN_PY)
    if spec is None or spec.loader is None:
        msg = "could not load known.py"
        raise RuntimeError(msg)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return {m.value for m in mod.KnownMap}


def render_generated(all_entries: dict[str, tuple[BlueprintEntry, ...]]) -> str:
    header = [
        "# generated by scripts/migrate_blueprints.py (and the blueprint editor)",
        "# do not edit by hand; source: *.bp files in this directory",
        "",
        "from blueprint import BlueprintEntry, Direction, Entity",
        "",
        "from hardcode.known import KnownMap",
        "",
        "__all__ = [\"BLUEPRINTS\"]",
        "",
        "BLUEPRINTS: dict[KnownMap, tuple[BlueprintEntry, ...]] = {",
    ]
    body: list[str] = []
    for map_name in sorted(all_entries):
        entries = all_entries[map_name]
        body.append(f"    KnownMap.{map_name.upper()}: (")
        for e in entries:
            parts = [f"({e.pos[0]}, {e.pos[1]})", f"Entity.{e.kind.name}"]
            if e.kind in DIRECTIONAL and e.direction is not None:
                parts.append(f"direction=Direction.{e.direction.name}")
            if e.kind == Entity.BRIDGE and e.bridge_target is not None:
                bx, by = e.bridge_target
                parts.append(f"bridge_target=({bx}, {by})")
            body.append(f"        BlueprintEntry({', '.join(parts)}),")
        body.append("    ),")
    return "\n".join([*header, *body, "}", ""])


def main() -> None:
    known_names = load_known_map_names()

    py_files = sorted(
        p for p in BLUEPRINTS_DIR.glob("*.py") if p.stem != "__init__"
    )
    all_entries: dict[str, tuple[BlueprintEntry, ...]] = {}
    for p in py_files:
        if p.stem not in known_names:
            print(f"skip {p.stem}: not in KnownMap", file=sys.stderr)
            continue
        entries = load_py_blueprint(p)
        if entries is None:
            print(f"skip {p.stem}: no BLUEPRINT tuple", file=sys.stderr)
            continue
        bp_path = BLUEPRINTS_DIR / f"{p.stem}.bp"
        bp_path.write_text(render_bp(entries, p.stem))
        all_entries[p.stem] = entries
        print(f"wrote {bp_path.relative_to(ROOT)}")

    generated = BLUEPRINTS_DIR / "_generated.py"
    generated.write_text(render_generated(all_entries))
    print(f"wrote {generated.relative_to(ROOT)}  ({len(all_entries)} maps)")


if __name__ == "__main__":
    main()
