"""Regenerate pkg/blueprint/blueprints/_generated.py from .bp sources.

Same output format as the Rust editor's regenerate_index() — run this
without opening the editor.
"""

from __future__ import annotations

import sys
from pathlib import Path

from blueprint import DIRECTIONAL, BlueprintEntry, Direction, Entity
from blueprint.known import KnownMap

ROOT = Path(__file__).resolve().parents[1]
BP_DIR = ROOT / "pkg" / "blueprint" / "blueprints"


def parse_bp(path: Path) -> list[BlueprintEntry]:
    entries: list[BlueprintEntry] = []
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        toks = line.split()
        x = int(toks[0])
        y = int(toks[1])
        kind = Entity[toks[2]]
        direction: Direction | None = None
        bridge_target: tuple[int, int] | None = None
        phase = 0
        for tok in toks[3:]:
            if tok.startswith("dir="):
                direction = Direction[tok[4:]]
            elif tok.startswith("bridge="):
                bx, by = tok[len("bridge=") :].split(",")
                bridge_target = (int(bx), int(by))
            elif tok.startswith("phase="):
                phase = int(tok[len("phase=") :])
        entries.append(
            BlueprintEntry(
                pos=(x, y),
                kind=kind,
                direction=direction,
                bridge_target=bridge_target,
                phase=phase,
            )
        )
    return entries


def render(entries: list[BlueprintEntry]) -> str:
    parts_all: list[str] = []
    entries = sorted(entries, key=lambda e: (e.phase, e.pos[1], e.pos[0]))
    for e in entries:
        parts = [f"({e.pos[0]}, {e.pos[1]})", f"Entity.{e.kind.name}"]
        if e.kind in DIRECTIONAL and e.direction is not None:
            parts.append(f"direction=Direction.{e.direction.name}")
        if e.kind == Entity.BRIDGE and e.bridge_target is not None:
            bx, by = e.bridge_target
            parts.append(f"bridge_target=({bx}, {by})")
        parts.append(f"phase={e.phase}")
        parts_all.append(f"        BlueprintEntry({', '.join(parts)}),")
    return "\n".join(parts_all)


def main() -> None:
    known = {m.value: m for m in KnownMap}
    all_maps: dict[str, list[BlueprintEntry]] = {}
    for bp in sorted(BP_DIR.glob("*.bp")):
        if bp.stem not in known:
            print(f"skip {bp.stem}: not in KnownMap", file=sys.stderr)
            continue
        all_maps[bp.stem] = parse_bp(bp)

    lines = [
        "# generated by blueprint-editor",
        "# do not edit by hand; source: *.bp files in this directory",
        "",
        "from blueprint import BlueprintEntry, Direction, Entity",
        "from hardcode.known import KnownMap",
        "",
        '__all__ = ["BLUEPRINTS"]',
        "",
        "BLUEPRINTS: dict[KnownMap, tuple[BlueprintEntry, ...]] = {",
    ]
    for name in sorted(all_maps):
        lines.append(f"    KnownMap.{name.upper()}: (")
        lines.append(render(all_maps[name]))
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    out = BP_DIR / "_generated.py"
    out.write_text("\n".join(lines))
    print(f"wrote {out.relative_to(ROOT)} ({len(all_maps)} maps)")


if __name__ == "__main__":
    main()
