PRESSURE_HIGH = 0.6
PRESSURE_ANCHOR_MAX = 0.5
PRESSURE_SPLIT = 0.7
PRESSURE_DEFENSE_MAX = 0.4

BRIDGE_MIN_SAVINGS = 6

CLAIM_TTL = 30
THREAT_TTL = 16
PRESSURE_TTL = 20
BREAK_TTL = 24

REPULSION_JITTER = 0.3

RAID_MIN_HARVESTERS = 6
DEFENSE_MIN_HARVESTERS = 2

SPAWN_TI_BUFFER = 100

PATROL_IDLE_LIMIT = 15

INITIAL_BUILDERS = 4
MAX_ECON_BUILDERS = 8

CIPHER = 0x2120B7E8
