from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((12, 22), Entity.HARVESTER),
    BlueprintEntry((13, 23), Entity.HARVESTER),
    BlueprintEntry((13, 22), Entity.HARVESTER),
    BlueprintEntry((12, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 27), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((17, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 26), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((17, 23), Entity.HARVESTER),
    BlueprintEntry((13, 25), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((23, 25), Entity.HARVESTER),
    BlueprintEntry((23, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((25, 24), Entity.HARVESTER),
    BlueprintEntry((24, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((22, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((21, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((20, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((19, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 25), Entity.BARRIER),
    BlueprintEntry((5, 24), Entity.BARRIER),
    BlueprintEntry((5, 23), Entity.BARRIER),
    BlueprintEntry((6, 23), Entity.BARRIER),
    BlueprintEntry((23, 22), Entity.BARRIER),
    BlueprintEntry((24, 22), Entity.BARRIER),
    BlueprintEntry((25, 22), Entity.BARRIER),
    BlueprintEntry((26, 22), Entity.BARRIER),
    BlueprintEntry((27, 22), Entity.BARRIER),
    BlueprintEntry((11, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 21), Entity.BARRIER),
    BlueprintEntry((10, 21), Entity.BARRIER),
    BlueprintEntry((12, 21), Entity.BARRIER),
    BlueprintEntry((13, 21), Entity.BARRIER),
    BlueprintEntry((14, 21), Entity.BARRIER),
    BlueprintEntry((13, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 24), Entity.FOUNDRY),
    BlueprintEntry((14, 23), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 23), Entity.BRIDGE, bridge_target=(14, 23)),
    BlueprintEntry((20, 23), Entity.LAUNCHER),
)
