from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((7, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 9), Entity.HARVESTER),
    BlueprintEntry((7, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 7), Entity.HARVESTER),
    BlueprintEntry((7, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 6), Entity.SENTINEL, direction=Direction.SOUTHEAST),
    BlueprintEntry((8, 5), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 14), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((9, 5), Entity.HARVESTER),
    BlueprintEntry((9, 2), Entity.HARVESTER),
    BlueprintEntry((8, 4), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 4), Entity.HARVESTER),
    BlueprintEntry((9, 3), Entity.HARVESTER),
    BlueprintEntry((8, 3), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 2), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 10), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((9, 11), Entity.HARVESTER),
    BlueprintEntry((9, 12), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((8, 9), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 11), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 8), Entity.BARRIER),
    BlueprintEntry((9, 1), Entity.BARRIER),
    BlueprintEntry((7, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 14), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 15), Entity.HARVESTER),
    BlueprintEntry((9, 16), Entity.HARVESTER),
    BlueprintEntry((8, 15), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 17), Entity.BARRIER),
)
