from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((7, 16), Entity.BARRIER),
    BlueprintEntry((8, 16), Entity.BARRIER),
    BlueprintEntry((2, 16), Entity.BARRIER),
    BlueprintEntry((1, 17), Entity.BARRIER),
    BlueprintEntry((1, 18), Entity.BARRIER),
    BlueprintEntry((3, 17), Entity.HARVESTER),
    BlueprintEntry((4, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 16), Entity.BARRIER),
    BlueprintEntry((5, 16), Entity.BARRIER),
    BlueprintEntry((10, 26), Entity.HARVESTER),
    BlueprintEntry((9, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 18), Entity.FOUNDRY),
    BlueprintEntry((10, 27), Entity.HARVESTER),
    BlueprintEntry((9, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 23), Entity.BARRIER),
    BlueprintEntry((11, 22), Entity.BARRIER),
    BlueprintEntry((11, 21), Entity.BARRIER),
    BlueprintEntry((11, 19), Entity.BARRIER),
    BlueprintEntry((11, 18), Entity.BARRIER),
    BlueprintEntry((11, 20), Entity.BARRIER),
    BlueprintEntry((11, 26), Entity.BARRIER),
    BlueprintEntry((11, 27), Entity.BARRIER),
    BlueprintEntry((11, 28), Entity.BARRIER),
    BlueprintEntry((3, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 18), Entity.HARVESTER),
    BlueprintEntry((5, 19), Entity.ROAD),
    BlueprintEntry((6, 20), Entity.ROAD),
    BlueprintEntry((8, 21), Entity.ROAD),
    BlueprintEntry((7, 20), Entity.ROAD),
    BlueprintEntry((9, 22), Entity.ROAD),
    BlueprintEntry((10, 22), Entity.ROAD),
    BlueprintEntry((3, 20), Entity.BRIDGE, bridge_target=(4, 18)),
    BlueprintEntry((3, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 18), Entity.ROAD),
    BlueprintEntry((2, 17), Entity.BARRIER),
)
