from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 27), Entity.HARVESTER),
    BlueprintEntry((5, 28), Entity.HARVESTER),
    BlueprintEntry((5, 29), Entity.HARVESTER),
    BlueprintEntry((4, 27), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 29), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 30), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 31), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 32), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 30), Entity.HARVESTER),
    BlueprintEntry((5, 31), Entity.HARVESTER),
    BlueprintEntry((5, 32), Entity.HARVESTER),
    BlueprintEntry((5, 24), Entity.HARVESTER),
    BlueprintEntry((5, 25), Entity.HARVESTER),
    BlueprintEntry((5, 26), Entity.HARVESTER),
    BlueprintEntry((4, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 25), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 26), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 39), Entity.HARVESTER),
    BlueprintEntry((3, 30), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 31), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 32), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 33), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 33), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 34), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 35), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 36), Entity.FOUNDRY),
    BlueprintEntry((5, 33), Entity.HARVESTER),
    BlueprintEntry((5, 34), Entity.HARVESTER),
    BlueprintEntry((5, 35), Entity.HARVESTER),
    BlueprintEntry((5, 36), Entity.HARVESTER),
    BlueprintEntry((6, 15), Entity.HARVESTER),
    BlueprintEntry((6, 16), Entity.BRIDGE, bridge_target=(4, 18)),
    BlueprintEntry((6, 38), Entity.BRIDGE, bridge_target=(4, 36)),
    BlueprintEntry((5, 23), Entity.HARVESTER),
    BlueprintEntry((5, 22), Entity.HARVESTER),
    BlueprintEntry((5, 21), Entity.HARVESTER),
    BlueprintEntry((4, 20), Entity.FOUNDRY),
    BlueprintEntry((4, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 23), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 25), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 26), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 20), Entity.HARVESTER),
    BlueprintEntry((4, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 19), Entity.BARRIER),
    BlueprintEntry((7, 14), Entity.BARRIER),
    BlueprintEntry((7, 16), Entity.BARRIER),
    BlueprintEntry((7, 38), Entity.BARRIER),
    BlueprintEntry((7, 40), Entity.BARRIER),
    BlueprintEntry((5, 18), Entity.BARRIER),
)
