from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((9, 17), Entity.HARVESTER),
    BlueprintEntry((10, 16), Entity.HARVESTER),
    BlueprintEntry((11, 17), Entity.HARVESTER),
    BlueprintEntry((10, 18), Entity.HARVESTER),
    BlueprintEntry((10, 17), Entity.BRIDGE, bridge_target=(12, 19)),
    BlueprintEntry((12, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((20, 30), Entity.HARVESTER),
    BlueprintEntry((19, 30), Entity.BRIDGE, bridge_target=(16, 30)),
    BlueprintEntry((11, 31), Entity.HARVESTER),
    BlueprintEntry((12, 31), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((13, 31), Entity.BRIDGE, bridge_target=(15, 30)),
    BlueprintEntry((15, 30), Entity.FOUNDRY),
    BlueprintEntry((16, 30), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 29), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((15, 28), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((15, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((15, 26), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((15, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 16), Entity.SENTINEL, direction=Direction.SOUTHEAST),
    BlueprintEntry((9, 18), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((11, 30), Entity.BARRIER),
    BlueprintEntry((10, 31), Entity.BARRIER),
    BlueprintEntry((11, 32), Entity.BARRIER),
    BlueprintEntry((14, 30), Entity.ROAD),
    BlueprintEntry((15, 31), Entity.ROAD),
    BlueprintEntry((20, 29), Entity.ROAD),
)
