from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((11, 16), Entity.BARRIER),
    BlueprintEntry((4, 17), Entity.BARRIER),
    BlueprintEntry((16, 17), Entity.BARRIER),
    BlueprintEntry((13, 16), Entity.BARRIER),
    BlueprintEntry((14, 16), Entity.BARRIER),
    BlueprintEntry((11, 15), Entity.BARRIER),
    BlueprintEntry((10, 16), Entity.HARVESTER),
    BlueprintEntry((10, 15), Entity.BARRIER),
    BlueprintEntry((18, 17), Entity.BARRIER),
    BlueprintEntry((19, 17), Entity.BARRIER),
    BlueprintEntry((12, 16), Entity.BARRIER),
    BlueprintEntry((8, 16), Entity.BARRIER),
    BlueprintEntry((7, 16), Entity.BARRIER),
    BlueprintEntry((6, 16), Entity.BARRIER),
    BlueprintEntry((9, 15), Entity.BARRIER),
    BlueprintEntry((10, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 23), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 24), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 25), Entity.BRIDGE, bridge_target=(10, 28)),
    BlueprintEntry((9, 16), Entity.BARRIER),
    BlueprintEntry((4, 18), Entity.FOUNDRY),
    BlueprintEntry((4, 19), Entity.HARVESTER),
    BlueprintEntry((10, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 16), Entity.HARVESTER),
    BlueprintEntry((2, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((3, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((5, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((0, 15), Entity.BARRIER),
    BlueprintEntry((1, 15), Entity.BARRIER),
    BlueprintEntry((2, 15), Entity.BARRIER),
)
