from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 44), Entity.HARVESTER),
    BlueprintEntry((6, 44), Entity.HARVESTER),
    BlueprintEntry((5, 45), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 45), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 45), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((2, 45), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((1, 46), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 41), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 40), Entity.HARVESTER),
    BlueprintEntry((5, 43), Entity.HARVESTER),
    BlueprintEntry((0, 39), Entity.BARRIER),
    BlueprintEntry((1, 39), Entity.BARRIER),
    BlueprintEntry((2, 39), Entity.BARRIER),
    BlueprintEntry((3, 39), Entity.BARRIER),
    BlueprintEntry((4, 39), Entity.BARRIER),
    BlueprintEntry((5, 39), Entity.BARRIER),
    BlueprintEntry((7, 39), Entity.BARRIER),
    BlueprintEntry((8, 39), Entity.BARRIER),
    BlueprintEntry((6, 39), Entity.BARRIER),
    BlueprintEntry((1, 45), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 43), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 42), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 42), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((1, 43), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 44), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 42), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 42), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((2, 40), Entity.HARVESTER),
    BlueprintEntry((1, 42), Entity.FOUNDRY),
    BlueprintEntry((2, 41), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((2, 42), Entity.CONVEYOR, direction=Direction.WEST),
)
