from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((21, 5), Entity.HARVESTER),
    BlueprintEntry((21, 7), Entity.HARVESTER),
    BlueprintEntry((24, 4), Entity.BARRIER),
    BlueprintEntry((24, 9), Entity.BARRIER),
    BlueprintEntry((10, 15), Entity.BARRIER),
    BlueprintEntry((14, 16), Entity.BARRIER),
    BlueprintEntry((18, 12), Entity.BARRIER),
    BlueprintEntry((19, 11), Entity.BARRIER),
    BlueprintEntry((12, 13), Entity.HARVESTER),
    BlueprintEntry((14, 12), Entity.BRIDGE, bridge_target=(16, 10)),
    BlueprintEntry((12, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((16, 10), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((13, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((21, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((21, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((21, 10), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((20, 10), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((19, 10), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 10), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 10), Entity.FOUNDRY),
    BlueprintEntry((17, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((17, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((20, 5), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 12), Entity.BARRIER),
    BlueprintEntry((8, 11), Entity.BARRIER),
)
