from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 7), Entity.HARVESTER),
    BlueprintEntry((13, 11), Entity.HARVESTER),
    BlueprintEntry((6, 2), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 2), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 2), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 2), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 2), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 2), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 11), Entity.HARVESTER),
    BlueprintEntry((12, 12), Entity.BARRIER),
    BlueprintEntry((13, 12), Entity.BARRIER),
    BlueprintEntry((14, 12), Entity.BARRIER),
    BlueprintEntry((15, 2), Entity.BARRIER),
    BlueprintEntry((15, 1), Entity.BARRIER),
    BlueprintEntry((15, 0), Entity.BARRIER),
    BlueprintEntry((3, 2), Entity.BARRIER),
    BlueprintEntry((3, 1), Entity.BARRIER),
    BlueprintEntry((3, 0), Entity.BARRIER),
    BlueprintEntry((6, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 3), Entity.BARRIER),
    BlueprintEntry((9, 3), Entity.BARRIER),
    BlueprintEntry((10, 3), Entity.BARRIER),
    BlueprintEntry((9, 2), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 3), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 4), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 7), Entity.HARVESTER),
    BlueprintEntry((12, 7), Entity.FOUNDRY),
    BlueprintEntry((12, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 4), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 3), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((6, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 7), Entity.ROAD),
    BlueprintEntry((13, 8), Entity.BARRIER),
    BlueprintEntry((13, 6), Entity.BARRIER),
    BlueprintEntry((5, 12), Entity.LAUNCHER),
    BlueprintEntry((4, 11), Entity.BARRIER),
    BlueprintEntry((5, 10), Entity.BARRIER),
    BlueprintEntry((5, 8), Entity.BARRIER),
    BlueprintEntry((4, 7), Entity.BARRIER),
    BlueprintEntry((5, 6), Entity.BARRIER),
)
