from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((12, 36), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 36), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 37), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 38), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 39), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 40), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 41), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 42), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 43), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 44), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 45), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 46), Entity.HARVESTER),
    BlueprintEntry((8, 46), Entity.HARVESTER),
    BlueprintEntry((12, 46), Entity.HARVESTER),
    BlueprintEntry((5, 41), Entity.HARVESTER),
    BlueprintEntry((5, 42), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 43), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 44), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 41), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 42), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 40), Entity.HARVESTER),
    BlueprintEntry((6, 44), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 44), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 44), Entity.FOUNDRY),
    BlueprintEntry((9, 44), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 31), Entity.BARRIER),
    BlueprintEntry((10, 44), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 45), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 45), Entity.BRIDGE, bridge_target=(9, 45)),
    BlueprintEntry((9, 45), Entity.CONVEYOR, direction=Direction.WEST),
)
