from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((11, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 9), Entity.HARVESTER),
    BlueprintEntry((11, 11), Entity.HARVESTER),
    BlueprintEntry((11, 10), Entity.BARRIER),
    BlueprintEntry((11, 13), Entity.BRIDGE, bridge_target=(11, 15)),
    BlueprintEntry((11, 15), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 16), Entity.BARRIER),
    BlueprintEntry((13, 14), Entity.BARRIER),
    BlueprintEntry((14, 5), Entity.HARVESTER),
    BlueprintEntry((14, 7), Entity.HARVESTER),
    BlueprintEntry((13, 8), Entity.HARVESTER),
    BlueprintEntry((12, 12), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 5), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 6), Entity.FOUNDRY),
    BlueprintEntry((14, 6), Entity.BARRIER),
    BlueprintEntry((15, 7), Entity.BARRIER),
    BlueprintEntry((14, 8), Entity.SENTINEL, direction=Direction.SOUTHWEST),
    BlueprintEntry((13, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 6), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 11), Entity.HARVESTER),
    BlueprintEntry((7, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 12), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((6, 11), Entity.BARRIER),
    BlueprintEntry((8, 11), Entity.FOUNDRY),
    BlueprintEntry((8, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 11), Entity.BARRIER),
    BlueprintEntry((7, 10), Entity.SENTINEL, direction=Direction.SOUTHEAST),
    BlueprintEntry((13, 9), Entity.BARRIER),
)
