from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((13, 16), Entity.HARVESTER),
    BlueprintEntry((6, 18), Entity.HARVESTER),
    BlueprintEntry((11, 10), Entity.HARVESTER),
    BlueprintEntry((11, 11), Entity.HARVESTER),
    BlueprintEntry((12, 12), Entity.HARVESTER),
    BlueprintEntry((12, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 6), Entity.HARVESTER),
    BlueprintEntry((12, 11), Entity.HARVESTER),
    BlueprintEntry((13, 13), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 13), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 8), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 9), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 10), Entity.FOUNDRY),
    BlueprintEntry((13, 10), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 9), Entity.SENTINEL, direction=Direction.SOUTHEAST),
    BlueprintEntry((13, 15), Entity.BARRIER),
    BlueprintEntry((14, 16), Entity.BARRIER),
    BlueprintEntry((13, 17), Entity.BARRIER),
    BlueprintEntry((5, 18), Entity.BARRIER),
    BlueprintEntry((6, 17), Entity.BARRIER),
    BlueprintEntry((6, 19), Entity.BARRIER),
    BlueprintEntry((10, 10), Entity.BARRIER),
    BlueprintEntry((10, 11), Entity.BARRIER),
)
