from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((4, 6), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 7), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 9), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 10), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 11), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 15), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 14), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 13), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 12), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 16), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((18, 20), Entity.HARVESTER),
    BlueprintEntry((19, 20), Entity.HARVESTER),
    BlueprintEntry((20, 19), Entity.HARVESTER),
    BlueprintEntry((19, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 19), Entity.BRIDGE, bridge_target=(14, 19)),
    BlueprintEntry((14, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 19), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 20), Entity.HARVESTER),
    BlueprintEntry((9, 20), Entity.HARVESTER),
    BlueprintEntry((9, 19), Entity.FOUNDRY),
    BlueprintEntry((8, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 19), Entity.HARVESTER),
    BlueprintEntry((5, 19), Entity.HARVESTER),
    BlueprintEntry((7, 20), Entity.HARVESTER),
    BlueprintEntry((7, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((9, 21), Entity.BARRIER),
    BlueprintEntry((10, 20), Entity.BARRIER),
    BlueprintEntry((8, 21), Entity.BARRIER),
    BlueprintEntry((7, 21), Entity.BARRIER),
    BlueprintEntry((6, 20), Entity.BARRIER),
    BlueprintEntry((5, 20), Entity.BARRIER),
    BlueprintEntry((4, 19), Entity.BARRIER),
)
