from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((10, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((11, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 22), Entity.HARVESTER),
    BlueprintEntry((13, 21), Entity.HARVESTER),
    BlueprintEntry((15, 17), Entity.HARVESTER),
    BlueprintEntry((16, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 16), Entity.HARVESTER),
    BlueprintEntry((15, 18), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 21), Entity.FOUNDRY),
    BlueprintEntry((14, 22), Entity.HARVESTER),
    BlueprintEntry((15, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 23), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((13, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 24), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((13, 20), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((17, 16), Entity.BARRIER),
    BlueprintEntry((17, 17), Entity.BARRIER),
    BlueprintEntry((17, 18), Entity.BARRIER),
    BlueprintEntry((17, 19), Entity.BARRIER),
    BlueprintEntry((15, 16), Entity.BARRIER),
    BlueprintEntry((14, 16), Entity.BARRIER),
    BlueprintEntry((13, 16), Entity.BARRIER),
    BlueprintEntry((14, 23), Entity.SENTINEL, direction=Direction.NORTHEAST),
    BlueprintEntry((14, 17), Entity.LAUNCHER),
)
