from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((3, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 22), Entity.HARVESTER),
    BlueprintEntry((11, 23), Entity.HARVESTER),
    BlueprintEntry((10, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 21), Entity.BARRIER),
    BlueprintEntry((11, 21), Entity.BARRIER),
    BlueprintEntry((1, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((1, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((3, 16), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 15), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 14), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 12), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 11), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 10), Entity.HARVESTER),
    BlueprintEntry((11, 11), Entity.HARVESTER),
    BlueprintEntry((11, 10), Entity.ROAD),
    BlueprintEntry((10, 11), Entity.FOUNDRY),
    BlueprintEntry((9, 11), Entity.BRIDGE, bridge_target=(6, 11)),
    BlueprintEntry((4, 11), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 11), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 11), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 10), Entity.ROAD),
    BlueprintEntry((8, 9), Entity.ROAD),
    BlueprintEntry((9, 10), Entity.ROAD),
    BlueprintEntry((4, 8), Entity.BRIDGE, bridge_target=(4, 11)),
    BlueprintEntry((3, 7), Entity.HARVESTER),
    BlueprintEntry((3, 8), Entity.HARVESTER),
    BlueprintEntry((2, 10), Entity.ROAD),
    BlueprintEntry((1, 9), Entity.ROAD),
    BlueprintEntry((1, 8), Entity.ROAD),
    BlueprintEntry((1, 6), Entity.ROAD),
    BlueprintEntry((1, 7), Entity.ROAD),
    BlueprintEntry((1, 5), Entity.ROAD),
    BlueprintEntry((2, 4), Entity.ROAD),
    BlueprintEntry((3, 5), Entity.ROAD),
    BlueprintEntry((6, 14), Entity.BARRIER),
    BlueprintEntry((6, 15), Entity.BARRIER),
    BlueprintEntry((4, 7), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((7, 19), Entity.HARVESTER),
    BlueprintEntry((7, 20), Entity.BRIDGE, bridge_target=(7, 23)),
    BlueprintEntry((6, 7), Entity.BARRIER),
    BlueprintEntry((7, 7), Entity.BARRIER),
    BlueprintEntry((10, 9), Entity.SENTINEL, direction=Direction.EAST),
    BlueprintEntry((12, 11), Entity.BARRIER),
    BlueprintEntry((13, 11), Entity.BARRIER),
    BlueprintEntry((13, 10), Entity.BARRIER),
    BlueprintEntry((13, 9), Entity.BARRIER),
)
