from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((7, 21), Entity.HARVESTER),
    BlueprintEntry((8, 20), Entity.BRIDGE, bridge_target=(11, 20)),
    BlueprintEntry((5, 21), Entity.HARVESTER),
    BlueprintEntry((5, 19), Entity.HARVESTER),
    BlueprintEntry((5, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((11, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((12, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 31), Entity.HARVESTER),
    BlueprintEntry((3, 32), Entity.HARVESTER),
    BlueprintEntry((3, 33), Entity.HARVESTER),
    BlueprintEntry((2, 33), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 32), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 31), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 30), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 29), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 28), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((4, 19), Entity.BARRIER),
    BlueprintEntry((5, 18), Entity.BARRIER),
    BlueprintEntry((6, 19), Entity.BARRIER),
    BlueprintEntry((4, 21), Entity.BARRIER),
    BlueprintEntry((2, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 27), Entity.HARVESTER),
    BlueprintEntry((6, 26), Entity.HARVESTER),
    BlueprintEntry((6, 28), Entity.HARVESTER),
    BlueprintEntry((4, 27), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 28), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 28), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 26), Entity.FOUNDRY),
    BlueprintEntry((2, 25), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 24), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 29), Entity.BARRIER),
    BlueprintEntry((6, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((7, 28), Entity.BARRIER),
    BlueprintEntry((7, 26), Entity.BARRIER),
    BlueprintEntry((6, 27), Entity.BARRIER),
    BlueprintEntry((5, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 22), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((6, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 26), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 25), Entity.CONVEYOR, direction=Direction.SOUTH),
)
