from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((13, 22), Entity.HARVESTER),
    BlueprintEntry((4, 22), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((5, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 19), Entity.HARVESTER),
    BlueprintEntry((11, 20), Entity.HARVESTER),
    BlueprintEntry((12, 21), Entity.HARVESTER),
    BlueprintEntry((10, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((10, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((24, 20), Entity.HARVESTER),
    BlueprintEntry((24, 21), Entity.HARVESTER),
    BlueprintEntry((24, 22), Entity.HARVESTER),
    BlueprintEntry((24, 23), Entity.HARVESTER),
    BlueprintEntry((23, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((23, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((23, 23), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((23, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((22, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((21, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((20, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((19, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((18, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((17, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((16, 22), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((15, 22), Entity.FOUNDRY),
    BlueprintEntry((15, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((13, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 23), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((14, 22), Entity.HARVESTER),
    BlueprintEntry((13, 21), Entity.HARVESTER),
    BlueprintEntry((12, 20), Entity.HARVESTER),
    BlueprintEntry((11, 19), Entity.HARVESTER),
    BlueprintEntry((12, 19), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((13, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((14, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((15, 21), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((9, 19), Entity.SENTINEL, direction=Direction.SOUTHEAST),
    BlueprintEntry((13, 20), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((14, 21), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((10, 18), Entity.BARRIER),
    BlueprintEntry((11, 18), Entity.BARRIER),
)
