from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((5, 7), Entity.HARVESTER),
    BlueprintEntry((10, 1), Entity.HARVESTER),
    BlueprintEntry((10, 2), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 2), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((12, 5), Entity.HARVESTER),
    BlueprintEntry((14, 4), Entity.HARVESTER),
    BlueprintEntry((12, 8), Entity.BARRIER),
    BlueprintEntry((12, 7), Entity.HARVESTER),
    BlueprintEntry((10, 7), Entity.BRIDGE, bridge_target=(8, 5)),
    BlueprintEntry((10, 8), Entity.HARVESTER),
    BlueprintEntry((11, 7), Entity.FOUNDRY),
    BlueprintEntry((11, 8), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((14, 5), Entity.BARRIER),
    BlueprintEntry((13, 4), Entity.FOUNDRY),
    BlueprintEntry((13, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((12, 4), Entity.BRIDGE, bridge_target=(10, 2)),
    BlueprintEntry((8, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 4), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 3), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((8, 2), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 2), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 2), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 2), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 2), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((5, 6), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 5), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 4), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((5, 3), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 7), Entity.BARRIER),
    BlueprintEntry((5, 8), Entity.BARRIER),
    BlueprintEntry((6, 7), Entity.BARRIER),
    BlueprintEntry((9, 1), Entity.BARRIER),
    BlueprintEntry((10, 0), Entity.BARRIER),
    BlueprintEntry((7, 7), Entity.BARRIER),
    BlueprintEntry((8, 7), Entity.BARRIER),
    BlueprintEntry((3, 0), Entity.BARRIER),
    BlueprintEntry((4, 6), Entity.BARRIER),
    BlueprintEntry((4, 5), Entity.BARRIER),
    BlueprintEntry((4, 4), Entity.BARRIER),
    BlueprintEntry((4, 3), Entity.BARRIER),
    BlueprintEntry((12, 0), Entity.BARRIER),
    BlueprintEntry((12, 1), Entity.BARRIER),
    BlueprintEntry((12, 2), Entity.BARRIER),
    BlueprintEntry((11, 1), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((11, 2), Entity.CONVEYOR, direction=Direction.WEST),
)
