from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((7, 17), Entity.BRIDGE, bridge_target=(5, 16)),
    BlueprintEntry((5, 16), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 18), Entity.BARRIER),
    BlueprintEntry((5, 14), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 14), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 14), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 12), Entity.ROAD),
    BlueprintEntry((9, 13), Entity.ROAD),
    BlueprintEntry((10, 13), Entity.BRIDGE, bridge_target=(7, 13)),
    BlueprintEntry((10, 12), Entity.HARVESTER),
    BlueprintEntry((7, 13), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((8, 17), Entity.HARVESTER),
    BlueprintEntry((8, 15), Entity.BARRIER),
    BlueprintEntry((6, 16), Entity.ROAD),
    BlueprintEntry((8, 11), Entity.ROAD),
    BlueprintEntry((9, 10), Entity.ROAD),
    BlueprintEntry((9, 9), Entity.ROAD),
    BlueprintEntry((11, 9), Entity.BARRIER),
    BlueprintEntry((10, 8), Entity.ROAD),
    BlueprintEntry((10, 7), Entity.ROAD),
    BlueprintEntry((11, 6), Entity.ROAD),
    BlueprintEntry((11, 5), Entity.ROAD),
    BlueprintEntry((13, 5), Entity.BARRIER),
    BlueprintEntry((12, 4), Entity.ROAD),
    BlueprintEntry((12, 3), Entity.ROAD),
    BlueprintEntry((13, 1), Entity.ROAD),
    BlueprintEntry((13, 2), Entity.ROAD),
    BlueprintEntry((14, 0), Entity.BARRIER),
    BlueprintEntry((6, 19), Entity.BARRIER),
    BlueprintEntry((5, 17), Entity.ROAD),
    BlueprintEntry((5, 18), Entity.ROAD),
    BlueprintEntry((3, 21), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 22), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((2, 23), Entity.ROAD),
    BlueprintEntry((2, 24), Entity.ROAD),
    BlueprintEntry((14, 28), Entity.HARVESTER),
    BlueprintEntry((8, 26), Entity.HARVESTER),
    BlueprintEntry((8, 25), Entity.FOUNDRY),
    BlueprintEntry((8, 27), Entity.ROAD),
    BlueprintEntry((9, 28), Entity.BRIDGE, bridge_target=(9, 25)),
    BlueprintEntry((10, 29), Entity.ROAD),
    BlueprintEntry((11, 28), Entity.BRIDGE, bridge_target=(9, 28)),
    BlueprintEntry((12, 29), Entity.ROAD),
    BlueprintEntry((7, 26), Entity.ROAD),
    BlueprintEntry((9, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 26), Entity.BARRIER),
    BlueprintEntry((8, 24), Entity.ROAD),
    BlueprintEntry((7, 25), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((6, 25), Entity.BRIDGE, bridge_target=(3, 25)),
    BlueprintEntry((3, 25), Entity.BRIDGE, bridge_target=(3, 22)),
    BlueprintEntry((3, 20), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 19), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 18), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((3, 17), Entity.CONVEYOR, direction=Direction.NORTH),
    BlueprintEntry((4, 25), Entity.ROAD),
    BlueprintEntry((5, 26), Entity.ROAD),
    BlueprintEntry((13, 28), Entity.BRIDGE, bridge_target=(11, 28)),
    BlueprintEntry((15, 27), Entity.BARRIER),
    BlueprintEntry((6, 24), Entity.BARRIER),
)
