from blueprint import BlueprintEntry, Direction, Entity

BLUEPRINT: tuple[BlueprintEntry, ...] = (
    BlueprintEntry((6, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((4, 17), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((3, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 17), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((2, 16), Entity.HARVESTER),
    BlueprintEntry((4, 16), Entity.HARVESTER),
    BlueprintEntry((6, 16), Entity.HARVESTER),
    BlueprintEntry((7, 17), Entity.HARVESTER),
    BlueprintEntry((8, 17), Entity.HARVESTER),
    BlueprintEntry((9, 17), Entity.HARVESTER),
    BlueprintEntry((13, 21), Entity.HARVESTER),
    BlueprintEntry((12, 22), Entity.HARVESTER),
    BlueprintEntry((4, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((4, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((2, 15), Entity.BARRIER),
    BlueprintEntry((4, 15), Entity.BARRIER),
    BlueprintEntry((5, 16), Entity.BARRIER),
    BlueprintEntry((6, 15), Entity.BARRIER),
    BlueprintEntry((5, 17), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((11, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((1, 16), Entity.BARRIER),
    BlueprintEntry((3, 16), Entity.BARRIER),
    BlueprintEntry((12, 18), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 19), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 20), Entity.CONVEYOR, direction=Direction.SOUTH),
    BlueprintEntry((12, 21), Entity.FOUNDRY),
    BlueprintEntry((11, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((9, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((8, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((7, 21), Entity.CONVEYOR, direction=Direction.WEST),
    BlueprintEntry((10, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((8, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((7, 18), Entity.CONVEYOR, direction=Direction.EAST),
    BlueprintEntry((9, 16), Entity.BARRIER),
    BlueprintEntry((8, 16), Entity.BARRIER),
    BlueprintEntry((7, 16), Entity.SENTINEL, direction=Direction.SOUTHEAST),
    BlueprintEntry((14, 20), Entity.HARVESTER),
    BlueprintEntry((13, 20), Entity.BRIDGE, bridge_target=(12, 21)),
)
