"""Hardcoded map data for known official maps.

Key: (w, h, core_a_x, core_a_y)
Value: (encoded_tiles_b64, core_b)
Tiles: 4 tiles packed per byte (2 bits each), base64 encoded.
Tile values: 0=empty, 1=wall, 2=ore_ti, 3=ore_ax
"""

import base64

from cambc import Environment

__all__ = ["MAPS", "decode"]


_TILE_TO_ENV: dict[int, Environment] = {
    0: Environment.EMPTY,
    1: Environment.WALL,
    2: Environment.ORE_TITANIUM,
    3: Environment.ORE_AXIONITE,
}


def _encode(tiles: list[int]) -> str:
    packed = bytearray()
    for i in range(0, len(tiles), 4):
        b = 0
        for j in range(4):
            if i + j < len(tiles):
                b |= (tiles[i + j] & 3) << (j * 2)
        packed.append(b)
    return base64.b64encode(bytes(packed)).decode("ascii")


def decode(data: str, n: int) -> list[Environment]:
    packed = base64.b64decode(data)
    tiles: list[Environment] = []
    for b in packed:
        for j in range(4):
            if len(tiles) >= n:
                break
            tiles.append(_TILE_TO_ENV[(b >> (j * 2)) & 3])
    return tiles


MAPS: dict[tuple[int, int, int, int], tuple[str, tuple[int, int]]] = {
    # arena
    (25, 25, 8, 10): (
        "AAAAAAAAAAAAAAAAAAAAVFUAAAAAgAAUAACAAAAAAQAAAAAgBAAAAAAAQAAAAMAAAAEAAgAAAAQAAABABRIAAAAAAEAAAABAwAAAAAAAAQAAAAAMBAAAAAQAAAAAABBCBQAAAEAAAAAAAgABAAwAAAAEAAAAAABAIAAAAAAAAQAACAAAUAAIAAAAAFRVAAAAAAAAAAAAAAAAAAAAAA==",
        (16, 14),
    ),
    # battlebot
    (21, 29, 4, 4): (
        "AAAAAABQVVVVVUEAAAAABAEAAAAQBAAgAEAQAAAAAEFAAAIEBAEBABAQBBAgEEAQQABAAEEABEEABAFAUQAQBEAABEAQQgBAIEFAAAAEBAFBURAQBMRFTUAQECgKAUFAoCgEBAEEAAQQhEAABEgQCBQFCEEBAAEABRQAAAAFQAHMAAUAFDADBQAAAQABAABQUQEAAAAQAAAA",
        (16, 4),
    ),
    # chemistry_class
    (40, 40, 14, 23): (
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAwAAAAAzAAAAAAzAAAAADAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAIAACACAAAAAIAIAACAAAAQBAAAAgAAAAAAEAQAAAAAAAAAABAEAAAAAAAAIAAQBAAIAAAAAIgAEAQAIgAAAAAgABAEAAgAAAAAAAAQBAAAAAAAAAAAEAQAAAAAAFBQABAEAAUFAABAEAAQBAAEAQAAQBAAEAQABAEAAEAQABAEAAQBAAAQQAAQBAABBAAAEEAAEAQAAQQAAAQAARAEQAAQAAAEAAEQBEAAEAAAAQAEEAQQAEAAAAEABNAHEABAAEAIghBAAQSCIAFAIAAQAAAEAAgBkAAgYAAACQgABhCAAEgAACEAAgRAVVUVAABUVVUBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        (25, 23),
    ),
    # cinnamon_roll
    (30, 30, 2, 27): (
        "AAAAAAAAAAAAAAAAAAAAAABQVRUAAAAAUAAAFAAAAEAAgAAUAAAAAQAAAAQAAARAVQUAAQAQQAEABRAAAAEBIAABBAAEBAAAEEAAQBBAVSAEBAAkAcEQQEAAQAQEVAQEBABEQFB0QBABQAQhXQQkEQBEGBB1SBABQAQBHQUBEQAQEBAVEBABAAEBBENAGAAQEAhVAQQBAAEEAAAQEAAQQAAIQEAAAARQAEABBABAAFBVARAAABAAAABAAAAAFAACAAEAAAAUAAAFAAAAAFRVBQAAAAAAAAAAAAAAAAAAAAAA",
        (27, 2),
    ),
    # corridors
    (31, 31, 5, 15): (
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAUBAQEBAQEAAEBAQEBAQEAAEBAQEBAQEICEhISEhISFAQEBAQEBAABAQEBAQEBAABAQEBAQEBCAhITExISEhQEBAQEBAQAAQEBAQEBAQAAQEBAQEBAQgASExMSEBIUBAQEBAQEAAEBAQEBAQEAAEBAQEBAQEICEhMTEhISFAQEBAQEBAABAQEBAQEBAABAQEBAQEBCAhISEhISEhQEBAQEBAQAAQEBAQEBAQAAQEBAQEBAQAAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        (25, 15),
    ),
    # default_large1
    (40, 40, 11, 25): (
        "AAAAAAAAAgAAAAAgAAAAAAAAAAAAAAIAVVVVBQACMAAAUAAAAFQAAAAAABUAAAAABQAAAEABAAAAABQAACBQAAAAAABQAAAAFAAAAAAAQAAAAAUAAAAAMAAAAAwBAAAAA6gAAABAAAAAAQAAAAAAQAAAAAEAAAAAAFAACAAFAAAAAAAQAAAABAAAACAAAAAAAAQAAAAAAAAAAAAQAAAAAAAAAAAAUAAAAAAAAAAAAEABQAEAAAAAAAAAVFUAAAAAAAAADAAAAAAAAAAAMAAAAAAAAABVFQAAAAAAAABAAUABAAAAAAAAAAAABQAAAAAAAAAAAAQAAAAAAAAAAAAQAAAAAAAIAAAAEAAAAAQAAAAAAFAAIAAFAAAAAABAAAAAAQAAAAAAQAAAAAEAAAAqwAAAAEAwAAAADAAAAABQAAAAAQAAAAAAFAAAAAUAAAAAAAUIAAAUAAAAAEABAAAAUAAAAABUAAAAAAAVAAAABQAADIAAUFVVVQCAAAAAAAAAAAAAAAgAAAAAgAAAAAAAAA==",
        (28, 14),
    ),
    # default_large2
    (50, 30, 3, 16): (
        "AAAAAAAAAAAAAAAAAAAAAAAgDIMAAAAAAAAAAAAIAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAUIAAAAAAACBQAAAFABAAAAAAAAVAAAAAAUAFBVVVUAQAEAAABABVBVVVVVABUAAAAAWEAFAAAAFVACAAAAAAUFAAAAAAUFAAAAAFAAAAAAAABQAAAAAAAFAAAAAAAABQAAACBQACAAAIAAUIAAAAAABQAAAAAAAAUAAAAAVAAAAAAAAFABAAAAQAEAQgEUCAAUAAAAABUAABRAAQBABQAAAFAAAEABFAAAUAAAAAAAAAIUQAEIAAAAAAAAAABAARQAAAAAAAAAACAAFEABgAAAAAAAACAAUAFUAIAAAAAAACAAABVABQCAAAAAACAAAFTwUAEAgAAACAgAAEABABQAAAACAgAAAAAVAEAFAAAAAAAAAEBVwDBQFQAAAAAAAFVVAAAAUFUFAAAAAFBVAQwAA1RVAAAAAAAAAAAAAAAAAAAA",
        (46, 16),
    ),
    # default_medium1
    (30, 30, 10, 19): (
        "AAAAAAAAAAAAAAAAAAAAMAAAgAIAgAAAAAAIAAAAQFUAAAAEAAAABAAAQAEAAEAAAABQCAAoBAAAAAQAAEIAAABAVQAAAAAEAAAAAAAAQAAAAAAAAAAEAAAACAAAQAAAAAAAAMAAAAAAAAAA4FUBAAAAQFULAAAAAAAAAAMAAAAAAAABAAAgAAAAEAAAAAAAAAABAAAAAAAAEAAAAABVAQAAAIEAABAAAAAQKAAgBQAAAAEAAEABAAAQAAAAEAAAAFUBAAAAIAAAAAACAIACAAAMAAAAAAAAAAAAAAAAAAAA",
        (19, 10),
    ),
    # default_medium2
    (30, 30, 3, 3): (
        "AAAAAAAAAAAAAAQAAQAAAABAABAAAAAAADTAAQAAAABAABAAAAAAAAQAAQAAAABAABAAAAAACAAAAAIAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAQBAAAIACBAAAAQAAAAAAQBAAFRVARAAAAQAAAAAAQBAAAAAABAAAAQAAAAAAQAAAIAgAAAAAAAACAIAAAACAMAwAAAIIABAABAAgAAAAAQAAQAAAABAABAAAABUBQQAAVUBAABAABAAAACAAgQAASgAIAhAABAAggAAAwAAAAwAAAAACAIAAAAAAAAAAAAA",
        (26, 3),
    ),
    # default_small1
    (20, 20, 1, 1): (
        "AAAAAAAAIAAAAAAAAAAAAAFVAQJAAQAAAAAAAAQAgCAIFAAAAAAAAADAAAAEAAAMAAQQADAAABAAAAMAAAAAAAAAFCAIAgAQAAAAAAAAQAGAQFVAAAAAAAAAAAAACAAAAAAAAA==",
        (18, 18),
    ),
    # default_small2
    (21, 21, 10, 1): (
        "AAAAAAAgAAAAAAIAAAAAAAABABAAABQgUAAAQAFQAAACVFUAAkAAAEAAUIEACBUAADADAAAAAAAAAAAAMwAAUIEACBUABAAABAACVFUAAgAUAAUAABQgUAAAEAAAAQAAAAAAAAIAAAAgAAAAAAAA",
        (10, 19),
    ),
    # dna
    (21, 50, 10, 48): (
        "AAAAAAAAAAAAAAAAAAAAAIAAAMAAAFpV1QMAIAAAAwCAAgAPAABoVQ8AAIDKDwAAAKADAAAAwAoAAADwowIAAPBVKQAA8ACAAgDAAAAIAMBXVaUAAAMAAAIADAAACABwVVUlAMADAKAAAAwAgAAA8FWVAgAAD4ACAADwowIAAAC8AAAAAOADAAAAqPwAAAAoAA8AAGhV9QAAIAAAAwCgAAA8AIBVVdUAAAIAAAMACAAADACgVVU9AAACADAAACgA8AAAgFb1AAAAqPwAAAAAOgAAAACsAAAAAD8qAAAAX5UCAAAPACgAAAwAgAAAfFVVCgAwAAAgAAAAAAAAAAAAAAAAAAAAAAA=",
        (10, 1),
    ),
    # face
    (20, 20, 5, 7): (
        "AIAAAgAMAAAAMEBVAFUBEABBAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAgAFAAgAAAUAAAAABQAAAAAVQAAAAAAAAAAgQBCAAABAEAAABQAFAAIQFUBIAAAAAAAAAwAMAAAAAAAAA==",
        (14, 7),
    ),
    # galaxy
    (40, 40, 4, 35): (
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAACAAACAAAAAFQAAAAAAAAAAUAEAAAAAAAAAABQACAAAAAAAAAAFAAADAAAAAAAAAQAAAAAAAACAQAAAAAAACAAAAFAAQFUFAAAAAAAQMBQAUAEAAAAAEAAFAAAUAAAAABQAAQKAQAEAAAAEQAAAAAAFAAAABEIAVAEABAAAAARAAAAUABAAQAAQQAAAQABAAEAAUAABDEABAwFAwEABMEAABQABAAEAAQAAAQQAAQAEABQAAAEQAAAAEABAFQCBEAAAAFAAAAAAARAAAABAAQKAQAAUAAAAABQAAFAABAAAAABABQAUDAQAAAAAAFBVAQAFAAAAIAAAAAAAAQIAAAAAAAAAQAAAAAAAAMAAAFAAAAAAAAAAIAAUAAAAAAAAAABABQAAAAAAAAAAVAAAAAIAAAIAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        (35, 4),
    ),
    # hooks
    (31, 31, 3, 22): (
        "AAAAAAAAAAAAABAAAAAAgAoABCoAAAAAAgCBAEBVAQAAQAAAEAAAAFQVVAEEAAAAAAABAAEAAAAAQABAAAAAAIASGhAAAEBVgAQGAAAAEAAAAQEAAAAEAEBAAAAAAAAAABBQVQEACgA8BABAAIBQFQMBABBAAADETAAABBAAAAFTFQgABABA8ACAAgBVFRAAAAAAAAAABAQAQAAAAAABAQAQAAAAQEIIVAUAABCQEgoAAAAABAAEAAAAAAABAAEAAAAAQABVUFUAAAAQAAAEAAAAVQUACAEAAgAAAKBCAIAKAAAAABAAAAAAAAAAAAAAAA==",
        (27, 8),
    ),
    # hourglass
    (27, 45, 13, 43): (
        "BAEAAAAQBAEBAAAAAUEAAQAAEEAQAAEAAAEQFAABABAABQQABUABQAABAKgKABBAAAAAAAAEUACAAABAARAAACAAEAAEACAAAAQABQCAAEABAAEAAAAQAEAAACIABABQAAgAQAEAEACAABAAABQAAAAFAAAUgABQAAAAFAACBQAAABQAUAAAAACUqgUAAAAA1F8AAAAAAAQEAAAAAED9BQAAAACUqgUAAABAAQAFAAAAFAACBQAAQAEIAAUAABQAAAAFAAABAAgAAQBQAAgAQAEABAAgAkAAAAEAAAAQAFAAAAgAFAAEACAAAAQAAQAAAgABUACAAABAAQQAAAAAQAABAKgKABBAAFAAFAAEFAABABAABQEQAAAQAEEAAQAAEEAQEAAAABAQBAEAAAAQBA==",
        (13, 1),
    ),
    # landscape
    (30, 30, 3, 2): (
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAACoAAAAAFRVAQMAAAAVAEAxAIAABAAAQAUAKhAAAAAABcBQAAAAAABVVQAAAAAAAAAAIAACAAIACKCoiqqKqiqqAAAAAAAAAAAAAAAAAAAAiqqoqqiqogoCIAAgAIAAAAAAAAAAAAAAAAAAUFUFAQAAAFAADEUAAABUAKACUAEAFAMACABAVRUwAAAAAAAAgAoAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        (3, 27),
    ),
    # minimaze
    (25, 25, 1, 23): (
        "KAMAAQCjIAAABAAAUlUIEIBUFQBBQEAQAAAEoSlBAEAQhIAEQQBBEAAQBAEkQVVVEAaQBMANQBhAFQAEAFUAABACEgAAAEAwQwAAFVBVVRVQQUAAAEBAAAEAAgIAAQQAQAAABABUBUFVAAAQEAQBAQBVQBAEVAEAIEEQAgAAAARBAAAAVBUEVQUAAACYAAAAAABgAgAAAAAAAQAAAA==",
        (23, 23),
    ),
    # pls_buy_cucats_merch
    (49, 49, 13, 17): (
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAEEAAMwgAAAAAAAAAEEEEMIgAAAAAAAAAQERAAAgIAAAAAAAAAAEAAYAIAAAAAAAAAAQABAAIAAAAAAAAABAAEAAAAAAAAAAAABAAAAEAgAAAAAAAAAARBAEFAAAAAAAAAABBEBBBgIgAAAAAAAAQABAEBAAAAAAAAAAAFRAQEIAAAABVVRUAEAABQQAAAAoEAEAAQAAEBAEAAIIQAAABAAFAEAQAAwgCAQAQAAQARAQAP4ACBABAABAAQBAAMAAAEAAAAUAAAEEAAAAAAgEAEAARAUQAAAAAAAQAQABEBFAAIAAAIlJVVVVBVRUAIAIAAAAAAAAAAAAAAAIAAAIAAAAAAAAADAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAACAAACAAAAAAAAAAAAAAAiAFBVBVVVVRUiAgAgABRARAAEAEAAAAAAAEQAEQEQAAABAgAAAAQBAAQAAQAQAAAwABAEABAABABAAArwA0BEAEAAEAAAAYIAA0AQBAABAAEAEAgCAABBQAAEAAQAQIACAAAEAQEQAFBVVQEAAAgQEBBQAQAAAAAAAABAQBAAEAAAAAAAAIgIBBEQBAEAAAAAAAAAQAFBEAEAAAAAAAAIAAABABAAAAAAAAAAAAAQABAAAAAAAAAAgABAAEAAAAAAAAAAgAgAAQABAAAAAAAAgIAABEQEAAAAAAAAAIgwQAQRAAAAAAAAAIAwAwQQAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
        (35, 31),
    ),
    # shish_kebab
    (20, 20, 2, 2): (
        "AAAAAAAAACAABQAAAEABAAAAVQAAAEBgIAAAQEMAAABQFQAACAQHAAAAJAQAAABUAQAAQBUAAAAQGAAAANAQIAAAVAUAAADBAQAACAkBAAAAVQAAAEABAAAAUAAIAAAAAAAAAA==",
        (17, 17),
    ),
    # thread_of_connection
    (20, 20, 3, 16): (
        "AAAAAQAAAEABAAAAQAAAgApQAAAgIBAIAAiAEAIACAUTQgEIFFMIVSAQTCAAgFBMgQAAQjEFAgAIMQQIVSDFFCBAgcRQIACABAIgACAECAgAAAWgAgAAAQAAAEABAAAAQAAAAA==",
        (16, 3),
    ),
    # tree_of_life
    (39, 30, 4, 22): (
        "AAAIAAIgAAgAACAAgAAAAAgAIAAAAwAAMwAAMAAAAAAAAQABAAAAAAIIcABAAwggAABUBUAABEBVAAAAABRAQAAFAAAAACBQAAAUIAAAAAAAQABAAAAAAAAAAEIABAIAAAAAAABAQAAAAAAAAAAAEBAAAAAAAAAAAAQEAAAAAAAAAAABAQAAAAAAAABAQAAAAAAAAAAAEBAAAAAAAAAAAAQEAAAAAAAAAAABAQAAAAAAAAAQAAEAAAAAAAAABEAAAAAAAAAAAAEQAAAAAAAAAFAAFAAAAAAAAAABABAAAAAAAEBVVVVVBQAAQFUFAAAAAFRVQAWAAAgAgAAIQAUAAAAAAAAAAAAAAIAAAAAACAAAIAAAAAgIAAAAAgAAAAAAAAAAAAA=",
        (34, 22),
    ),
    # wasteland
    (40, 40, 3, 36): (
        "AARAAIEAREAAAAABAgAEAFAEAAABAAAlAFAAEAEAAFIVAAEgYQQAAAEQBAREAAFQAAAAgABQAUAEBAAAMAEgBMAFEBQBAAAAAREEBUEQEQRAUREEBRAEBARBBEBENIREQAAABRQQgABBQABRFBEQAAAQABFVABAABFQQFUEFYBRAFQQBEQRQAAEBQVCARAAFAQBBQGAEAAQQAAABAAAUFAARAIQEAxQEASFABEgBEBQEQVUAQAABAAEQBQwBBRBAABFACAFAAEFBAAFAIAFEAAEEUEAwUARAAEAAAQBVQRAUBEAhEAFIQBAUwBASAEQAFBQAAEAAAAQQABAJAUEAQFAAEQIFQUBAAAUQREAQVAEUCVBBVAQVEAAEAFVEAAQAAAREFEUAAUEAAgQUUAAAARESHBEBEEEQEBAEUBBERQEQRARBUBBEQAAAAEAUBFADEAhADAAAEBABQAUAAgAAAAVAABEQEARAAAAQSQhAAFSFAABABAAFAFgAAEAAABAFABAAgEAAAAABEQBCAAEQAA==",
        (36, 3),
    ),
}
