from hardcode.known import KnownMap
from hardcode.opening import Opening, register
from hardcode.opening.dsl import (
    NE,
    NW,
    SE,
    SW,
    DslTurn,
    E,
    N,
    S,
    W,
    ba,
    br,
    c,
    f,
    h,
    ln,
)

_B1: list[DslTurn] = [
    c(E, W) | E,
    E.rd(),
    h(SE) | None,
    br(S, (2, -2)) | None,
    ln(SW) | None,
    N.turn(),
    c(E, W) | None,
    c(SE, N) | None,
    c(W, S) | None,
    N.turn(),
    NE.turn(),
    S.rd(),
    ln(E) | None,
    f(SE) | None,
    S.turn(),
    ba(SE) | None,
    N.turn(),
    NE.turn(),
    SE.rd(),
    S.rd(),
    S.rd(),
    ba(SW) | None,
    S.rd(),
    S.rd(),
    W.rd(),
    ba(W) | None,
]

_B2: list[DslTurn] = [
    NE.turn(),
    c(NE, W) | NE,
    N.rd(),
    NE.rd(),
    E.rd(),
    NE.rd(),
    NE.rd(),
    E.rd(),
    SE.rd(),
    br(S, (-2, 0)) | None,
    c(SE, W) | SE,
    h(E) | None,
    N.rd(),
    ba(E) | S,
    S.rd(),
    ba(E) | None,
    SE.rd(),
    NE.rd(),
    ba(N) | None,
    SW.turn(),
    NW.turn(),
    N.turn(),
    NW.turn(),
    ln(SW) | None,
    W.rd(),
    br(SW, (-2, 2)) | None,
]

register(
    KnownMap.GALAXY,
    Opening(
        core_spawns=[(1, -1), (1, 0)],
        builder_scripts=[_B1, _B2],
    ),
)
